// Package apisurface is the AIDOS Runtime emitter for the EMITTED APP'S COMPLETE API
// SURFACE (S90, EPIC 9): a deterministic projection of the WHOLE set of a project's
// Kernel operations into
//
//   - a Hono/TS ROUTER (ADR 0040): one route per operation — a create-mutate operation →
//     POST /<entities>, a read operation → GET /<entities> — each handler delegating to
//     the Go SIDECAR interpreter callback (ADR 0040 Déc.7, OQ-0040-interpréteur TRANCHÉE
//     = callback vers un service-interpréteur Go) and ENFORCING the operation's policy
//     (an authorize step → the handler asks the interpreter; a DENY → HTTP 403, never the
//     mutate);
//   - a per-app OPENAPI 3.1 document (byte-stable) describing every emitted path;
//   - a Pact SUITE — ONE contract per operation (generalising the single
//     createOrder.pact.json the S36 api emitter produced for AIDOS itself).
//
// It is the app-builder counterpart of the S36 Go API projection (back/runtime/generators
// EmitAPI/EmitContract), but: (a) it spans the FULL operation set, not just createOrder;
// (b) it targets Hono/TS (the user app, ADR 0040), not Go; (c) it emits a per-app OpenAPI;
// (d) the handler reaches the business rule through a CALLBACK to the Go sidecar
// interpreter, never re-implementing a rule in TS.
//
// THE CONTRACT IS DETERMINISM (CLAUDE.md §6/§8, determinism-first):
//
//	EmitRouter(spec), EmitOpenAPI(spec) and EmitPactSuite(spec) are PURE, TOTAL functions
//	of their canonicalised input — no clock, no RNG, no map-iteration-order leak, no
//	absolute path; stable operation/path ordering, fixed key order, "\n" newlines. So the
//	same Kernel cut → byte-identical surface on every run/machine (the S90 done-criterion:
//	"property — l'OpenAPI est byte-stable depuis le Kernel").
//
// THE INTERPRETER-PARITY LAW (S90 done-criterion: "le callback interpréteur Go donne le
// même verdict que l'interpréteur natif"). The emitted handler holds NO business rule: it
// hands the command to the Go sidecar, which runs the SAME operation.Interpret AIDOS runs
// natively. SidecarVerdict(op, input, deps) is the exact function the sidecar exposes; it
// is operation.Interpret behind a JSON boundary. The parity mirror pins
// SidecarVerdict == operation.Interpret for the same (op, input, deps) — a DENY in one is
// a DENY in the other, a persisted row in one is a persisted row in the other.
//
// THE WALL (CLAUDE.md §2). An emitter only READS Kernel sources (operations + the entity
// each touches + whether it authorizes) and WRITES projections BELOW the line
// (gen/<project>/api/…). It writes no truth. A malformed spec is a typed BlockReason (the
// S13 shape) — never a panic, never an invented route/path/policy.
package apisurface

import (
	"errors"
	"sort"
	"strings"

	"github.com/steph-frtech/aidos/back/kernel/entities"
	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// protectedMarker is the exact header text every emitted file carries — mirrors the S87
// honoemit / S35 emitter marker so a hand-edit of gen/ is forbidden and drift is computable.
const protectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// Verb is the closed set of HTTP verbs the surface maps an operation to. A create-mutate
// operation → POST ; a read-only operation → GET. The set is CLOSED so the matrix stays
// enumerable and no method is invented.
type Verb string

const (
	// VerbPost — a create-mutate operation (it persists a row).
	VerbPost Verb = "POST"
	// VerbGet — a read-only operation (it loads, persists nothing).
	VerbGet Verb = "GET"
)

// Op is one operation the API surface projects, read from the Kernel cut (the emitter
// authors none of it):
//   - Name      — the operation name (the route key, the Pact provider name);
//   - Entity    — the entity the operation touches (its attributes shape the request/
//     response body and the OpenAPI schema);
//   - Verb      — POST (create) or GET (read); derived from the operation, pinned here so
//     the closed set is explicit;
//   - Authorize — whether the operation carries an authorize step (a Policy). When true the
//     emitted handler enforces it: the sidecar's DENY → HTTP 403.
//   - Async     — an async operation (S73) gets no synchronous HTTP route (it is wired in
//     the worker, S87) and no Pact interaction; it still appears in the spec for completeness.
type Op struct {
	Name      string
	Entity    entities.Entity
	Verb      Verb
	Authorize bool
	Async     bool
	// Input is the operation's INPUT schema (the command payload the POST request carries),
	// read from the Kernel operation's Input source. It is DISTINCT from Entity (the response
	// schema): createOrder's input is {cartId}, its response is an Order. When empty the
	// request body falls back to the entity's required attributes (a plain CRUD create whose
	// input IS the entity). The emitter authors neither — it reads the operation's two schemas.
	Input []entities.Attribute
}

// ApiSpec is the surface emitter's input: the project namespace + the FULL set of the
// project's operations. "Émission déterministe du routage CRUD + operation complet" — the
// emitter wires EVERY sync operation; it never invents or omits one.
type ApiSpec struct {
	Project string
	Ops     []Op
}

// Validation sentinels. A malformed spec is a BlockReason at the boundary; these are the
// internal causes folded into the explanation (the S13 shape, never a new code).
var (
	ErrNoProject    = errors.New("apisurface: spec pins no project")
	ErrNoOps        = errors.New("apisurface: spec pins no operations")
	ErrOpNoName     = errors.New("apisurface: operation pins no name")
	ErrOpNoEntity   = errors.New("apisurface: operation pins no entity")
	ErrUnknownVerb  = errors.New("apisurface: operation pins an unknown HTTP verb")
	ErrEntityNoAttr = errors.New("apisurface: operation's entity pins no attributes")
)

// block renders the canonical S13 BlockReason for a malformed spec. It carries a non-empty
// how_to_fix (no prison) and folds the cause into the explanation so the panel and
// `aidos explain` name the missing pin.
func block(cause error) blockreason.BlockReason {
	return blockreason.BlockReason{
		Code:     blockreason.CodeOutOfScope,
		Severity: blockreason.SeverityBlocking,
		Explanation: "Émission de la surface API refusée : la source (operations du Kernel) est malformée ou vide (" +
			cause.Error() + "). Un emitter REND exactement ce que la source épingle ; il n'invente jamais une route, " +
			"un chemin OpenAPI, une policy ni un verbe (honnêteté). Une operation sans nom, sans entité ou sans attributs " +
			"n'est pas projetable.",
		HowToFix: []string{
			"pin_the_source : complétez la source dans le Kernel (operations nommées, chacune liée à une entité typée).",
			"use_a_known_verb : chaque operation porte un verbe du jeu fermé (POST création / GET lecture) ; un verbe inconnu n'est jamais deviné.",
			"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
		},
	}
}

// validate checks the spec is projectable: a project namespace, ≥ 1 operation, every op
// pins a name + an entity with ≥ 1 attribute + a known verb. It invents nothing.
func validate(s ApiSpec) error {
	if s.Project == "" {
		return ErrNoProject
	}
	if len(s.Ops) == 0 {
		return ErrNoOps
	}
	for _, op := range s.Ops {
		if op.Name == "" {
			return ErrOpNoName
		}
		if op.Entity.Name == "" {
			return ErrOpNoEntity
		}
		if len(op.Entity.Attributes) == 0 {
			return ErrEntityNoAttr
		}
		if op.Verb != VerbPost && op.Verb != VerbGet {
			return ErrUnknownVerb
		}
	}
	return nil
}

// syncOps returns the spec's SYNC operations in CANONICAL name order (so map/source order
// never leaks into the bytes). An async operation has no synchronous HTTP route (it is
// wired in the worker, S87) — it is filtered out of the router/OpenAPI/Pact surface.
func syncOps(s ApiSpec) []Op {
	out := make([]Op, 0, len(s.Ops))
	for _, op := range s.Ops {
		if !op.Async {
			out = append(out, op)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// PathOf maps an operation to its REST path deterministically: /<plural lower entity>. It
// coins no path the source does not pin (honesty). A POST creates at the collection; a GET
// lists the collection — both at the same canonical collection path.
func PathOf(op Op) string {
	return "/" + pluralize(strings.ToLower(op.Entity.Name))
}

// inputAttrs returns the operation's request-body schema: its declared Input when non-empty,
// else the entity's REQUIRED attributes (the plain-CRUD fallback where input IS the entity).
func inputAttrs(op Op) []entities.Attribute {
	if len(op.Input) > 0 {
		return op.Input
	}
	out := make([]entities.Attribute, 0, len(op.Entity.Attributes))
	for _, a := range op.Entity.Attributes {
		if a.Required {
			out = append(out, a)
		}
	}
	return out
}

// pluralize is the same naive pluralizer the S36 api emitter uses, kept local so the path
// is byte-identical to the Go projection's route (one rule across planes).
func pluralize(name string) string {
	if name == "" {
		return name
	}
	if strings.HasSuffix(name, "s") {
		return name
	}
	if strings.HasSuffix(name, "y") {
		return name[:len(name)-1] + "ies"
	}
	return name + "s"
}
