// Package honoemit is the AIDOS Runtime emitter for the EMITTED APP'S SERVER (S87):
// a deterministic, bootable Hono/TS service projected from the project's Kernel
// operations — main + router + middleware + a /healthz health check + one handler per
// SYNC operation + the async/worker wiring (S73/S74) — plus a NEW projection target
// TargetPulumiProgram that emits a Pulumi/TS infra program from a StackManifest
// (ADR 0043). It is the app-builder counterpart of the S36 Go API projection: where
// S36 emits Go handlers for AIDOS itself, honoemit emits the USER APP's TS server
// (Hono/functional TS — ADR 0040 — never Go for the user app).
//
// THE CONTRACT IS DETERMINISM (CLAUDE.md §6/§8, determinism-first):
//
//	EmitServer(spec) and EmitPulumiProgram(manifest) are PURE, TOTAL functions of
//	their canonicalised input — no clock, no RNG, no map-iteration-order leak, no
//	absolute path; stable operation/service ordering, fixed import order, "\n"
//	newlines. So the same Kernel cut → byte-identical scaffold on every run/machine
//	(the S87 done-criterion: "même Kernel → scaffold byte-identique qui compile").
//
// THE EMITTED CODE IS FN02-PURE (ADR 0036 / ADR 0040). Every emitted module is pure
// functional TS: no top-level mutable binding (`let`/`var` at module scope), no
// hidden global state — dependencies (the operation interpreter callback, the outbox,
// the dispatcher) arrive as PARAMETERS, never as ambient singletons. The reproducibility
// + purity mirrors (honoemit_property_test.go) pin both: byte-stability AND that the
// emitted bytes carry no module-scope mutable binding.
//
// THE WALL (CLAUDE.md §2). An emitter only READS Kernel sources (operations, the
// StackManifest) and WRITES projections BELOW the line (gen/<project>/server/…). It
// writes no truth. A malformed spec/manifest is a typed BlockReason (the S13 shape) —
// never a panic, never an invented route/service/role.
//
// OpenQuestion OQ-S87-stackmanifest (forward-dependency, CLAUDE.md §6 bootstrap
// exception). The StackManifest is the DP02 first-class kernel record kind, NOT YET
// built (grep stack_manifest = 0). honoemit therefore models the StackManifest as the
// JSON body the Pulumi emitter CONSUMES (a StackManifest value: app name + services +
// volumes + network), content-addressed via S02's Hash(Canonicalize(body)). When DP02
// lands the kernel `stack_manifest` kind, the decoder binds to it; the emitter is
// unchanged. honoemit coins no new kernel kind (the wall). This is a documented
// OpenQuestion, not a failing residual.
package honoemit

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/steph-frtech/aidos/back/kernel/operation"
	"github.com/steph-frtech/aidos/back/kernel/records"
	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// protectedMarker is the exact header text every emitted file carries — mirrors the S35
// emitter marker so a hand-edit of gen/ is forbidden and the drift is computable.
const protectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// The emit targets honoemit renders. The set is CLOSED — one Kernel cut → exactly these
// projections at S87 — so the matrix stays enumerable and no target is invented.
const (
	// TargetHonoServer — the emitted app's bootable Hono/TS server (main+router+
	// middleware+health+sync handlers). Lands under gen/<project>/server/server.ts.
	TargetHonoServer = "hono-server"
	// TargetHonoWorker — the emitted app's async worker entrypoint (drains the outbox,
	// dispatches typed effects). Lands under gen/<project>/server/worker.ts.
	TargetHonoWorker = "hono-worker"
	// TargetPulumiProgram — the emitted app's Pulumi/TS infra program (ADR 0043),
	// projected from the StackManifest. Lands under gen/<project>/infra/index.ts.
	TargetPulumiProgram = "pulumi-program"
	// TargetPulumiScaffold — the Pulumi project scaffold (Pulumi.yaml + package.json) the
	// per-project×env stack emitter (EmitPulumiStack) ships so `pulumi up` boots. Lands under
	// gen/<project>/infra/{Pulumi.yaml,package.json}.
	TargetPulumiScaffold = "pulumi-scaffold"
)

// targetOrder is the canonical enumeration order (declared, never from map iteration).
var targetOrder = []string{TargetHonoServer, TargetHonoWorker, TargetPulumiProgram, TargetPulumiScaffold}

// Targets returns every honoemit target in canonical order.
func Targets() []string {
	out := make([]string, len(targetOrder))
	copy(out, targetOrder)
	return out
}

// Op is one operation the server projects: its NAME (the route key) + whether it is
// ASYNC (S73 — an async op gets a worker dispatcher, never a sync HTTP handler) and, for
// an async op, its trigger. The emitter never authors an op; it reads the Kernel cut.
type Op struct {
	Name  string
	Async bool
	// Trigger is the async trigger (S73) — meaningful only when Async is true.
	Trigger operation.AsyncTrigger
}

// ServerSpec is the Hono server emitter's input: the project namespace + the FULL set of
// the project's Kernel operations (sync AND async). "câblé sur TOUTES les operations du
// Kernel" — the emitter wires every operation; a sync op → an HTTP handler, an async op →
// a worker dispatcher. The emitter never invents or omits an operation.
//
// Entities + WebDir carry the VIEW the server SERVES (the React view derived from the tree,
// EmitWebApp). Both are OPTIONAL and purely additive — an empty Entities/WebDir emits the
// SAME pure API server it always did (the no-fork guarantee):
//   - Entities  : the entity names the list views read; the server emits one read route
//     GET /entities/<entity> per name (so the served view's list fetches resolve).
//   - WebDir     : the relative path (inside the server image) of the BUILT React dist/. When
//     set, the server mounts the static React build (serveStatic) on GET / + a SPA
//     catch-all — so the app SERVES the view alongside the API (same origin).
type ServerSpec struct {
	Project  string
	Ops      []Op
	Entities []string
	WebDir   string
}

// Validation sentinels. A malformed spec/manifest is a BlockReason at the boundary; these
// are the internal causes folded into the explanation (the S13 shape, never a new code).
var (
	ErrNoProject       = errors.New("honoemit: spec/manifest pins no project")
	ErrNoOps           = errors.New("honoemit: server spec pins no operations")
	ErrOpNoName        = errors.New("honoemit: operation pins no name")
	ErrAsyncBadTrigger = errors.New("honoemit: async operation pins an unknown trigger kind")
	ErrNoServices      = errors.New("honoemit: manifest pins no services")
	ErrServiceNoName   = errors.New("honoemit: service pins no name")
	ErrServiceNoImage  = errors.New("honoemit: service pins no image")
	ErrUnknownRole     = errors.New("honoemit: service pins an unknown role")
	ErrNoServer        = errors.New("honoemit: manifest declares no service role=server")
	ErrDupInternalPort = errors.New("honoemit: two services pin the same internal port")
	ErrNoEnv           = errors.New("honoemit: stack pins no environment (project×env)")
)

// block renders the canonical S13 BlockReason for a malformed spec/manifest. It carries a
// non-empty how_to_fix (no prison) and folds the cause into the explanation so the panel
// and `aidos explain` name the missing pin.
func block(cause error) blockreason.BlockReason {
	return blockreason.BlockReason{
		Code:     blockreason.CodeOutOfScope,
		Severity: blockreason.SeverityBlocking,
		Explanation: "Émission refusée : la source (operations du Kernel ou StackManifest) est malformée ou vide (" +
			cause.Error() + "). Un emitter REND exactement ce que la source épingle ; il n'invente jamais une route, " +
			"un service, un rôle ni un trigger (honnêteté). Une source sans nom ni contenu n'est pas projetable.",
		HowToFix: []string{
			"pin_the_source : complétez la source dans le Kernel (operations nommées / manifest avec services typés).",
			"use_a_known_role : chaque service porte un rôle du jeu fermé ; un rôle inconnu n'est jamais deviné.",
			"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
		},
	}
}

// validateServer checks the spec is projectable: a project namespace, ≥ 1 operation, every
// op pins a name, and every async op pins a known trigger kind. It invents nothing.
func validateServer(s ServerSpec) error {
	if s.Project == "" {
		return ErrNoProject
	}
	if len(s.Ops) == 0 {
		return ErrNoOps
	}
	for _, op := range s.Ops {
		if op.Name == "" {
			return ErrOpNoName
		}
		if op.Async && !operation.IsTriggerKind(string(op.Trigger.Kind)) {
			return ErrAsyncBadTrigger
		}
	}
	return nil
}

// syncOps / asyncOps split the spec's operations in CANONICAL name order (so map/source
// order never leaks into the bytes). A sync op → an HTTP handler; an async op → a worker
// dispatcher. The split is a pure filter over the closed Async flag.
func syncOps(s ServerSpec) []Op  { return filterOps(s, false) }
func asyncOps(s ServerSpec) []Op { return filterOps(s, true) }

func filterOps(s ServerSpec, async bool) []Op {
	out := make([]Op, 0, len(s.Ops))
	for _, op := range s.Ops {
		if op.Async == async {
			out = append(out, op)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// serverSourceBody re-serialises the spec into a canonical, key-sorted JSON body so the
// SourceHash is a content address: same spec (modulo input order) → same hash. It walks the
// CANONICAL op order so input order never leaks (S02 Canonicalize reused, never forked).
func serverSourceBody(s ServerSpec) ([]byte, error) {
	type opView struct {
		Name    string `json:"name"`
		Async   bool   `json:"async"`
		Trigger string `json:"trigger,omitempty"`
		At      string `json:"at,omitempty"`
	}
	ops := make([]opView, 0, len(s.Ops))
	all := append([]Op(nil), s.Ops...)
	sort.SliceStable(all, func(i, j int) bool { return all[i].Name < all[j].Name })
	for _, op := range all {
		ov := opView{Name: op.Name, Async: op.Async}
		if op.Async {
			ov.Trigger = string(op.Trigger.Kind)
			ov.At = op.Trigger.At
		}
		ops = append(ops, ov)
	}
	// The served VIEW is part of the source: a new entity read route or a flipped WebDir changes
	// the emitted server, so it must change the content address. Entity names are canonically sorted
	// so input order never leaks into the hash.
	ents := append([]string(nil), s.Entities...)
	sort.Strings(ents)
	body := map[string]any{"project": s.Project, "ops": ops, "entities": ents, "web_dir": s.WebDir}
	return records.Canonicalize(mustJSON(body))
}

// ServerSourceHash is the content address of a server spec (the SourceHash every artifact
// carries). Any byte change (a new op, an op turned async) yields a new hash.
func ServerSourceHash(s ServerSpec) (string, error) {
	body, err := serverSourceBody(s)
	if err != nil {
		return "", err
	}
	return records.Hash(body), nil
}

// EmitServer renders the bootable Hono/TS server for the project: imports, the app +
// middleware (request-id + json), GET /healthz (the health check), and one POST handler
// per SYNC operation that delegates to the injected operation-interpreter callback (the
// Go sidecar, ADR 0040 Déc.7 — the handler re-implements no business rule). The async ops
// are wired into the worker (EmitWorker), not the HTTP router. FN02-pure: deps arrive as a
// parameter to `createApp`, never as a module-scope mutable binding.
func EmitServer(s ServerSpec) (Artifact, *blockreason.BlockReason) {
	if err := validateServer(s); err != nil {
		br := block(err)
		return Artifact{}, &br
	}
	sourceHash, err := ServerSourceHash(s)
	if err != nil {
		br := block(err)
		return Artifact{}, &br
	}

	var b strings.Builder
	b.WriteString(header("//", sourceHash))
	b.WriteString("// S87 emitted app server (Hono/functional TS, ADR 0040). main+router+middleware+health+\n")
	b.WriteString("// one handler per SYNC operation; async ops are wired in worker.ts. When the spec pins a\n")
	b.WriteString("// WebDir it ALSO serves the React view (the static dist/) on GET / + an SPA fallback.\n\n")
	b.WriteString("import { Hono } from \"hono\";\n")
	b.WriteString("import type { Context } from \"hono\";\n")
	// cors ships INSIDE the hono package (no new dep) — emitted UNCONDITIONALLY because the app is
	// MULTI-PLATFORM (ADR 0040): the web child shares the API origin, but the mobile (Expo) and desktop
	// (Electron) children run on SEPARATE origins, so the API must answer their cross-origin fetch/POST.
	// Auth is the x-aidos-user HEADER (never an ambient cookie), so the default allow-all origin policy
	// carries no credential-leak risk (CORS is not the auth boundary; the header is). Tightening the
	// allowed origins per deployment is a documented OpenQuestion, not a rule emitted here.
	b.WriteString("import { cors } from \"hono/cors\";\n")
	// serveStatic ships with @hono/node-server (no new dep) — imported ONLY when the server serves the
	// view (WebDir set), so a pure API server stays import-clean (the no-fork guarantee).
	if s.WebDir != "" {
		b.WriteString("import { serveStatic } from \"@hono/node-server/serve-static\";\n")
	}
	b.WriteString("\n")

	// The operation interpreter callback port (ADR 0040 Déc.7): the handler hands the
	// command to the Go sidecar interpreter; it re-implements no rule. A PORT, not a global.
	// It carries the caller AUTH ($.auth) alongside the input ($.input) so an authorize verb
	// and an auth-bearing mutate (createOrder's userId: $.auth.user.id, total: sum(...)) resolve
	// against the real caller — never an empty $.auth. auth is optional (defaults to {}).
	b.WriteString("export type OperationInterpreter = (operation: string, input: unknown, auth?: unknown) => Promise<unknown>;\n")
	// The entity LIST port (the read side, S87 read verb): a PURE function entity name → its rows.
	// The served view's list fetch (GET /entities/<e>) delegates to it; like OperationInterpreter it
	// is a PORT the boot wires onto the Go sidecar (GET ${INTERPRETER_URL}/list?entity=<e>), never a
	// global, never a re-implemented query. Optional so the pure API server still boots in a test
	// without a list source — a missing lister yields an honest empty array (never a 404).
	b.WriteString("export type EntityLister = (entity: string) => Promise<unknown[]>;\n")
	// The AUTH deriver port: a PURE function request-context → caller identity ($.auth). server.ts owns
	// no authentication SCHEME — it only calls the injected deriver and sets the result on the context
	// (FIRST, before the routes, so every handler's c.get("auth") resolves). The BOOT (index.ts) injects
	// the concrete deriver (the X-Aidos-User header reader); a missing deriver defaults to {} (no scheme
	// invented here). Optional so the pure server stays bootable in tests without an auth source.
	b.WriteString("export type AuthDeriver = (c: Context) => unknown;\n")
	b.WriteString("export type Deps = { interpret: OperationInterpreter; list?: EntityLister; auth?: AuthDeriver };\n\n")

	// createApp is a PURE FACTORY: deps in → a configured Hono app out. No module-scope
	// mutable binding (FN02). Every handler closes over the injected `deps`.
	b.WriteString("export function createApp(deps: Deps): Hono {\n")
	b.WriteString("\tconst app = new Hono();\n")
	// CORS — registered FIRST so the preflight OPTIONS of a cross-origin child (mobile/desktop) is
	// answered before any route runs. Default policy (allow-all origin) — see the import note. A pure
	// deterministic projection, no business rule, no module-scope state (FN02).
	b.WriteString("\tapp.use(\"*\", cors());\n")
	// FIRST middleware (runs BEFORE every route — Hono dispatches in registration order): the request-id/
	// app header AND the caller-identity binding. It calls the injected auth deriver and sets the result on
	// the context (c.set("auth", …)) so each route reads it via c.get("auth"). Installed here, not in the
	// boot, because a middleware registered AFTER the routes would not wrap them (Hono registration order).
	b.WriteString("\tapp.use(\"*\", async (c, next) => {\n")
	b.WriteString("\t\tc.header(\"x-app\", " + jsStr(s.Project) + ");\n")
	b.WriteString("\t\tc.set(\"auth\", deps.auth ? deps.auth(c) : {});\n")
	b.WriteString("\t\tawait next();\n")
	b.WriteString("\t});\n")
	// The health check — GET /healthz → 200 { status: \"ok\" }.
	b.WriteString("\tapp.get(\"/healthz\", (c) => c.json({ status: \"ok\" }, 200));\n")
	// One handler per sync operation (canonical name order). A create-op → POST /<op>.
	for _, op := range syncOps(s) {
		route := routeOf(op.Name)
		fmt.Fprintf(&b, "\tapp.post(%s, async (c) => {\n", jsStr(route))
		b.WriteString("\t\tconst input = await c.req.json().catch(() => ({}));\n")
		// The caller AUTH ($.auth): the conventional Hono context value an upstream auth
		// middleware sets (c.get(\"auth\")), defaulting to {} when none is set. It is forwarded
		// to the sidecar so $.auth resolves (createOrder's userId/total). The route invents no
		// authentication scheme — it only forwards the caller the platform already authenticated.
		b.WriteString("\t\tconst auth = c.get(\"auth\") ?? {};\n")
		fmt.Fprintf(&b, "\t\tconst result = await deps.interpret(%s, input, auth);\n", jsStr(op.Name))
		b.WriteString("\t\treturn c.json(result, 201);\n")
		b.WriteString("\t});\n")
	}
	// One READ route per entity the served view lists (GET /entities/<entity>, canonical order). The
	// list views fetch their rows here. The route DELEGATES to the injected EntityLister port (the Go
	// sidecar's GET /list?entity=<e> verb, wired in index.ts) — it re-implements no query (the wall §2,
	// determinism-first §6/§8). When no lister is wired (the pure API server in a test) it falls back to
	// an honest EMPTY array, never a 404: the list view renders its header + the "—" empty state.
	for _, name := range sortedNames(s.Entities) {
		entity := strings.ToLower(name)
		route := "/entities/" + entity
		fmt.Fprintf(&b, "\tapp.get(%s, async (c) => {\n", jsStr(route))
		fmt.Fprintf(&b, "\t\tconst rows = deps.list ? await deps.list(%s) : [];\n", jsStr(entity))
		b.WriteString("\t\treturn c.json(rows, 200);\n")
		b.WriteString("\t}); // read route → sidecar list verb (GET /list?entity)\n")
	}
	// The VIEW the app SERVES (WebDir set): the built React dist/ as static files + an SPA catch-all
	// to index.html. Mounted LAST so the API routes above (healthz, POST /<op>, GET /entities/<e>) win;
	// any other path falls through to the static assets, and an unknown path serves index.html (the SPA
	// shell). Same origin as the API → the view's fetch(/entities/…) + POST /<op> reach the API, no CORS.
	if s.WebDir != "" {
		root := s.WebDir
		fmt.Fprintf(&b, "\tapp.use(\"/*\", serveStatic({ root: %s }));\n", jsStr(root))
		fmt.Fprintf(&b, "\tapp.get(\"*\", serveStatic({ path: %s }));\n", jsStr(strings.TrimRight(root, "/")+"/index.html"))
	}
	b.WriteString("\treturn app;\n")
	b.WriteString("}\n")

	out := []byte(strings.TrimRight(b.String(), "\n") + "\n")
	return artifact("gen/"+s.Project+"/server/server.ts", TargetHonoServer, out, sourceHash), nil
}

// EmitWorker renders the emitted app's ASYNC WORKER entrypoint (S73/S74): for each async
// operation (canonical name order) a `dispatch<Op>` that drains the outbox and dispatches
// each typed effect, plus (for a cron trigger) the scheduled echeance as a constant. The
// dispatcher + outbox arrive as PARAMETERS (FN02 — no module-scope mutable binding). A spec
// with no async op emits a worker with no dispatchers (a valid, byte-stable empty entry).
func EmitWorker(s ServerSpec) (Artifact, *blockreason.BlockReason) {
	if err := validateServer(s); err != nil {
		br := block(err)
		return Artifact{}, &br
	}
	sourceHash, err := ServerSourceHash(s)
	if err != nil {
		br := block(err)
		return Artifact{}, &br
	}

	var b strings.Builder
	b.WriteString(header("//", sourceHash))
	b.WriteString("// S87 emitted app worker (Hono/TS, ADR 0040): drains the outbox, dispatches typed effects.\n\n")
	b.WriteString("export type OutboxRow = { effect_id: string; operation: string; kind: string; target: string; payload: unknown; dispatched: boolean };\n")
	b.WriteString("export type Outbox = {\n")
	b.WriteString("\tpending(operation: string): Promise<OutboxRow[]>;\n")
	b.WriteString("\tmarkDispatched(effectId: string): Promise<void>;\n")
	b.WriteString("};\n")
	b.WriteString("export type Dispatcher = {\n")
	for _, tk := range operation.TriggerKinds() {
		fmt.Fprintf(&b, "\t%s(target: string, payload: unknown): Promise<void>;\n", string(tk))
	}
	b.WriteString("};\n\n")

	for _, op := range asyncOps(s) {
		opConst := strings.ToUpper(op.Name[:1]) + op.Name[1:]
		if op.Trigger.Kind == operation.TriggerCron {
			fmt.Fprintf(&b, "export const %s_SCHEDULED_AT = %s;\n", strings.ToUpper(op.Name), jsStr(op.Trigger.At))
		}
		fmt.Fprintf(&b, "export async function dispatch%s(outbox: Outbox, dispatcher: Dispatcher): Promise<number> {\n", opConst)
		fmt.Fprintf(&b, "\tconst rows = await outbox.pending(%s);\n", jsStr(op.Name))
		b.WriteString("\tlet dispatched = 0;\n")
		b.WriteString("\tfor (const row of rows) {\n")
		b.WriteString("\t\tif (row.dispatched) continue;\n")
		b.WriteString("\t\tswitch (row.kind) {\n")
		for _, tk := range operation.TriggerKinds() {
			fmt.Fprintf(&b, "\t\t\tcase %s: await dispatcher.%s(row.target, row.payload); break;\n", jsStr(string(tk)), string(tk))
		}
		b.WriteString("\t\t\tdefault: continue;\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tawait outbox.markDispatched(row.effect_id);\n")
		b.WriteString("\t\tdispatched++;\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn dispatched;\n")
		b.WriteString("}\n\n")
	}

	out := []byte(strings.TrimRight(b.String(), "\n") + "\n")
	return artifact("gen/"+s.Project+"/server/worker.ts", TargetHonoWorker, out, sourceHash), nil
}

// routeOf maps an operation name to its POST route deterministically: /<lowercased name>.
// It coins no route the source does not pin (honesty).
func routeOf(name string) string {
	return "/" + strings.ToLower(name)
}

// sortedNames returns a canonical-name-ordered COPY of a name slice (never mutating the caller's),
// so input order never leaks into the emitted read routes.
func sortedNames(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
