package entities

import (
	"fmt"
	"go/format"
	"path"
	"strings"

	"github.com/steph-frtech/aidos/back/kernel/records"
	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// typeBinding maps one closed scalar type to its three projections. The set is CLOSED
// — a field whose type is not here is a BlockReason, never a guessed mapping
// (honesty). The Go column is the sqlc-shaped type (pgtype.* mirrors the existing
// sqlc output so the go-sqlc projection is what sqlc would emit from the DDL — the two
// cannot drift); the DDL column is the Postgres type fed to Atlas.
type typeBinding struct {
	ddl string // Postgres column type (the sqlc schema input)
	gos string // Go field type (what sqlc emits from that column)
	ts  string // TypeScript field type
}

// typeMap is the single source of the scalar → {DDL, Go, TS} mapping. It is the ONLY
// place a scalar token becomes three concrete types; ScalarTypes()/IsKnownType read
// it so the closed set and its mapping never drift apart.
var typeMap = map[ScalarType]typeBinding{
	TypeString:      {ddl: "TEXT", gos: "string", ts: "string"},
	TypeInt:         {ddl: "BIGINT", gos: "int64", ts: "number"},
	TypeDecimal:     {ddl: "NUMERIC", gos: "pgtype.Numeric", ts: "string"},
	TypeBool:        {ddl: "BOOLEAN", gos: "bool", ts: "boolean"},
	TypeTimestamptz: {ddl: "TIMESTAMPTZ", gos: "pgtype.Timestamptz", ts: "string"},
}

// ProtectedMarker is the exact text every emitted file header carries. Hand-edited
// gen/ files are forbidden (CLAUDE.md §4/§9); this marker makes the prohibition
// visible and the drift computable (an artifact whose source: hash no longer matches
// its entity's head is stale — it feeds S22's red wave, never hunted).
const ProtectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// Artifact is one emitted projection of an entity. It is content-addressed twice: by
// its SOURCE (SourceHash = the entity AST it was emitted from, reusing S02) and by
// its OUTPUT (OutputHash = the digest of the rendered bytes, the byte-identical
// re-emit proof). Path is RELATIVE (no absolute path — determinism).
type Artifact struct {
	Path       string `json:"path"`
	Target     string `json:"target"`
	Bytes      []byte `json:"bytes"`
	SourceHash string `json:"source_hash"`
	OutputHash string `json:"output_hash"`
	Protected  bool   `json:"protected"`
}

// The three projection target tokens. The set is closed (one source → exactly these
// three projections at S35); api/mobile are later teeth, never invented here.
const (
	TargetGo  = "go-sqlc"
	TargetTS  = "ts-types"
	TargetDDL = "pg-ddl"
)

// blockUnknownType renders the canonical S13 BlockReason for an entity that cannot be
// projected — an unknown attribute type (UNKNOWN_ATTRIBUTE_TYPE) or a malformed/empty
// AST. It reuses the blockreason shape (never a new code beyond a human red) and
// always carries a non-empty how_to_fix (no prison, KRD §44.5). The cause names the
// missing/unknown pin so the panel and `aidos explain` are actionable.
func blockUnknownType(cause error) blockreason.BlockReason {
	return blockreason.BlockReason{
		Code:     blockreason.CodeOutOfScope,
		Severity: blockreason.SeverityBlocking,
		Explanation: "Émission refusée (UNKNOWN_ATTRIBUTE_TYPE) : l'AST d'entité est malformé, ou un " +
			"attribut porte un type hors du jeu scalaire fermé (" + cause.Error() + "). Un emitter REND " +
			"exactement les attributs épinglés par la source, avec leur type mappé ; il n'invente jamais " +
			"un champ, une colonne ni un type, et ne retombe JAMAIS silencieusement sur any/text (honnêteté).",
		HowToFix: []string{
			"use_a_known_type : chaque attribut porte un type du jeu fermé (string | int | decimal | bool | timestamptz) ; un type inconnu n'est jamais deviné.",
			"pin_the_entity_ast : complétez l'AST d'entité (nom + attributs typés, au plus un identifier) — l'emitter ne lit que ce que la source épingle.",
			"rerun aidos project : relancez l'émission une fois la source d'entité complète et bien typée.",
		},
	}
}

// goName turns an entity/attribute name into an exported Go identifier (Order, Id).
// Deterministic: first rune upper, rest verbatim (the AST pins lowercase tokens in
// the Order example; no inflection is invented — `placed_at` → `Placed_at`, kept
// faithful to the source rather than guessing a CamelCase the source did not pin).
func goName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// header renders the protected file header for a target's comment syntax: the SAME
// marker on every target plus the source content-hash.
func header(commentPrefix, sourceHash string) string {
	return fmt.Sprintf("%s %s. source: %s\n", commentPrefix, ProtectedMarker, sourceHash)
}

// EmitGo renders the Go struct projection (the sqlc-shaped N3 type): one exported
// struct, one field per attribute IN SOURCE ORDER, with the mapped Go type, pgtype.*
// imported only when used. go/format makes it gofmt-clean by construction and is a
// pure function of its input, so byte-stability holds. Required/¬required does NOT
// change the Go field type (a Go struct field is always present; nullability is a
// pgtype/database concern, not a struct-shape concern) — but the field SET and ORDER
// are faithful to the source. Returns a BlockReason for a malformed/unknown-type AST.
func EmitGo(e Entity) (Artifact, *blockreason.BlockReason) {
	if err := Validate(e); err != nil {
		br := blockUnknownType(err)
		return Artifact{}, &br
	}
	sourceHash, err := ID(e)
	if err != nil {
		br := blockUnknownType(err)
		return Artifact{}, &br
	}
	needsPgtype := false
	for _, a := range e.Attributes {
		if strings.HasPrefix(typeMap[a.Type].gos, "pgtype.") {
			needsPgtype = true
		}
	}
	var b strings.Builder
	b.WriteString(header("//", sourceHash))
	fmt.Fprintf(&b, "package %sgen\n\n", strings.ToLower(e.Name))
	if needsPgtype {
		b.WriteString("import (\n\t\"github.com/jackc/pgx/v5/pgtype\"\n)\n\n")
	}
	fmt.Fprintf(&b, "type %s struct {\n", goName(e.Name))
	for _, a := range e.Attributes {
		fmt.Fprintf(&b, "\t%s %s\n", goName(a.Name), typeMap[a.Type].gos)
	}
	b.WriteString("}\n")
	out := []byte(b.String())
	if formatted, ferr := format.Source(out); ferr == nil {
		out = formatted
	}
	return artifact(e, TargetGo, out, sourceHash), nil
}

// EmitTS renders the TypeScript type projection (the shared type/sdk projection): one
// exported type alias, one field per attribute IN SOURCE ORDER, with the mapped TS
// type. A ¬required attribute is OPTIONAL (`discount?`) — required ⇔ non-optional. It
// is rendered from the SAME AST as Go/DDL so the three agree on every field — one
// source, never double-typed. Returns a BlockReason for a malformed/unknown-type AST.
func EmitTS(e Entity) (Artifact, *blockreason.BlockReason) {
	if err := Validate(e); err != nil {
		br := blockUnknownType(err)
		return Artifact{}, &br
	}
	sourceHash, err := ID(e)
	if err != nil {
		br := blockUnknownType(err)
		return Artifact{}, &br
	}
	var b strings.Builder
	b.WriteString(header("//", sourceHash))
	fmt.Fprintf(&b, "export type %s = {\n", goName(e.Name))
	for _, a := range e.Attributes {
		opt := ""
		if !a.Required {
			opt = "?"
		}
		fmt.Fprintf(&b, "\t%s%s: %s;\n", a.Name, opt, typeMap[a.Type].ts)
	}
	b.WriteString("};\n")
	return artifact(e, TargetTS, []byte(b.String()), sourceHash), nil
}

// EmitDDL renders the Postgres DDL projection (the expand-contract db projection): a
// CREATE TABLE with one column per attribute IN SOURCE ORDER. required → NOT NULL;
// ¬required → NULLABLE (the column omits NOT NULL). The single identifier attribute
// becomes the PRIMARY KEY. Identifiers are quoted so a reserved word (e.g. "order")
// is valid DDL and a safe sqlc schema input — so the go-sqlc projection cannot drift
// from it. Returns a BlockReason for a malformed/unknown-type AST.
func EmitDDL(e Entity) (Artifact, *blockreason.BlockReason) {
	if err := Validate(e); err != nil {
		br := blockUnknownType(err)
		return Artifact{}, &br
	}
	sourceHash, err := ID(e)
	if err != nil {
		br := blockUnknownType(err)
		return Artifact{}, &br
	}
	id, hasID := Identifier(e)
	var b strings.Builder
	b.WriteString(header("--", sourceHash))
	fmt.Fprintf(&b, "CREATE TABLE %q (\n", strings.ToLower(e.Name))
	for i, a := range e.Attributes {
		col := typeMap[a.Type].ddl
		nullness := ""
		if a.Required {
			nullness = " NOT NULL"
		}
		pk := ""
		if hasID && a.Name == id.Name {
			pk = " PRIMARY KEY"
		}
		comma := ","
		if i == len(e.Attributes)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "    %q %s%s%s%s\n", a.Name, col, pk, nullness, comma)
	}
	b.WriteString(");\n")
	return artifact(e, TargetDDL, []byte(b.String()), sourceHash), nil
}

// artifact builds the Artifact wrapper around rendered bytes, computing the relative
// path and the output content hash. SourceHash is the entity's content address.
func artifact(e Entity, target string, out []byte, sourceHash string) Artifact {
	return Artifact{
		Path:       artifactPath(e, target),
		Target:     target,
		Bytes:      out,
		SourceHash: sourceHash,
		OutputHash: records.Hash(out),
		Protected:  true,
	}
}

// artifactPath returns the RELATIVE projection path for a target (no absolute paths —
// determinism). The kernel entity projections land under a DEDICATED location distinct
// from S34's runtime gen (back/gen/<name>/) so the two emitter sets never clobber each
// other: Go/DDL under back/gen/<name>-entity/, TS under front/web/gen/<name>-entity/.
func artifactPath(e Entity, target string) string {
	name := strings.ToLower(e.Name) + "-entity"
	switch target {
	case TargetGo:
		return path.Join("back/gen", name, strings.ToLower(e.Name)+".go")
	case TargetDDL:
		return path.Join("back/gen", name, "schema.sql")
	case TargetTS:
		return path.Join("front/web/gen", name, strings.ToLower(e.Name)+".ts")
	default:
		return ""
	}
}

// Emit dispatches to the per-target emitter, so callers can fan an entity across the
// closed target set deterministically.
func Emit(e Entity, target string) (Artifact, *blockreason.BlockReason) {
	switch target {
	case TargetGo:
		return EmitGo(e)
	case TargetTS:
		return EmitTS(e)
	case TargetDDL:
		return EmitDDL(e)
	default:
		br := blockUnknownType(fmt.Errorf("entities: unknown target %q", target))
		return Artifact{}, &br
	}
}

// Targets returns the closed projection target set in canonical order (Go, TS, DDL).
func Targets() []string { return []string{TargetGo, TargetTS, TargetDDL} }

// AttributeSet returns the entity's attribute names in source order — the field/column
// set each projection must agree on (no add/drop/rename). Used by the "all three agree"
// fixture and the no-drift property.
func AttributeSet(e Entity) []string {
	out := make([]string, len(e.Attributes))
	for i, a := range e.Attributes {
		out[i] = a.Name
	}
	return out
}
