// CODE GENERATED BY AIDOS — DO NOT EDIT. source: 8ebfb46ff10c0dc68ee53be000e9965466e7effa666703f870fce027fbae5cf6
// Web projection (S38): the control-spec "checkout-button" bound to action "checkout-submit".
// One source → N projections, never double-typed (KRD LIVRE V). The button is a
// PROJECTION of the control-spec (S11): visible/enabled are EvalState(control, given)
// embedded as the control's Expr ASTs; the click DECLARES the bound operation
// (Plan(action, click).invoke) via data-aidos-invoke — it does NOT execute it.
"use client";

import { type ExprNode, evalState } from "@/lib/aidos-expr";

// visible_when / enabled_when — the control's Expr DSL ASTs (back/kernel/expr), embedded verbatim.
const VISIBLE_WHEN: ExprNode = {"args":[{"kind":"ref","path":"$.cart.items.length"},{"kind":"lit","value":0}],"fn":"\u003e","kind":"call"};
const ENABLED_WHEN: ExprNode = {"args":[{"kind":"ref","path":"$.form.valid"},{"args":[{"kind":"ref","path":"$.submitting"}],"fn":"!","kind":"call"}],"fn":"\u0026\u0026","kind":"call"};
const INVOKE = "createOrder";
const LABEL = "i18n(cart.checkout)";

export interface CheckoutButtonProps {
	/** The $-rooted situation state — the fixture `given` (S11). */
	given: Record<string, unknown>;
	/** Called with the bound operation ref when the enabled button is clicked. */
	onInvoke?: (invoke: string) => void;
}

/** CheckoutButton — the emitted web projection of control "checkout-button". */
export function CheckoutButton({ given, onInvoke }: CheckoutButtonProps) {
	const { visible, enabled } = evalState(VISIBLE_WHEN, ENABLED_WHEN, given);
	if (!visible) return null;
	return (
		<button
			data-testid="aidos-control-checkout-button"
			type="button"
			disabled={!enabled}
			data-aidos-visible={visible ? "true" : "false"}
			data-aidos-enabled={enabled ? "true" : "false"}
			data-aidos-invoke={INVOKE}
			onClick={() => {
				if (enabled) onInvoke?.(INVOKE);
			}}
			className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
		>
			{LABEL}
		</button>
	);
}
