import { expect, test } from "@playwright/test";

/**
 * S36 Playwright e2e — the API-projection Workbench panel (/api-projection).
 * mirror record: reflects=runtime.generators.{EmitAPI,EmitContract,VerifyContract} (the
 *               deterministic, LLM-free API emitter + in-process Pact provider verification;
 *               a kernel OPERATION exposed over HTTP, request/response reusing the ENTITY
 *               shape, never re-typed), test_kind=e2e, cert_language=gherkin, liveness=alive,
 *               authority=above
 *
 * Scenario: the createOrder route passes its contract test — the done criterion, visible
 *   Given the Workbench is running
 *   When I navigate to /api-projection
 *   Then the createOrder card shows method POST and route /orders (from the operation, not invented)
 *   And the emitted Go handler panel is present and non-empty, carrying the protected header
 *        and delegating to operation.Interpret
 *   And the Pact contract panel is present
 *   And clicking VERIFY CONTRACT makes the contract-test badge read PASS (the done criterion)
 *   And clicking RE-EMIT reports byte-identical (same output_hash — determinism visible)
 */

test.describe("S36 — API projection (operation + entity → Go REST/JSON handler + Pact)", () => {
	test.beforeEach(async ({ page }) => {
		await page.goto("/api-projection");
		await expect(
			page.getByRole("heading", { name: /API projection/i }),
		).toBeVisible({ timeout: 5000 });
	});

	test("the createOrder card shows method POST and route /orders", async ({
		page,
	}) => {
		const methodRoute = page.locator("[data-method-route]");
		await expect(methodRoute).toBeVisible();
		await expect(methodRoute).toContainText("POST");
		await expect(methodRoute).toContainText("/orders");
	});

	test("the emitted Go handler panel is present, non-empty, with the protected header", async ({
		page,
	}) => {
		const handler = page.locator("[data-handler-bytes]");
		await expect(handler).toBeVisible();
		await expect(handler).toContainText(
			"CODE GENERATED BY AIDOS — DO NOT EDIT",
		);
		// the handler delegates to the S10 operation interpreter (thin transport adapter).
		await expect(handler).toContainText("operation.Interpret");
		await expect(handler).toContainText("OrderRequest");
	});

	test("the Pact contract panel is present", async ({ page }) => {
		const contract = page.locator('[data-contract="createOrder"]');
		await expect(contract).toBeVisible();
		await expect(
			contract.getByRole("button", { name: /VERIFY CONTRACT|VÉRIFIER/i }),
		).toBeVisible();
	});

	test("VERIFY CONTRACT makes the contract-test badge read PASS (the done criterion)", async ({
		page,
	}) => {
		const contract = page.locator('[data-contract="createOrder"]');
		await contract
			.getByRole("button", { name: /VERIFY CONTRACT|VÉRIFIER/i })
			.click();
		const badge = page.locator("[data-verify-badge]");
		await expect(badge).toHaveAttribute("data-pass", "true");
		await expect(badge).toContainText(/PASS/i);
	});

	test("RE-EMIT reports byte-identical (same output_hash — determinism visible)", async ({
		page,
	}) => {
		await page.getByRole("button", { name: /RE-EMIT|RÉ-ÉMETTRE/i }).click();
		await expect(
			page
				.locator("[data-reemit-result]")
				.getByText(/byte-identical|byte-identique/i),
		).toBeVisible();
	});
});
