import { expect, test } from "@playwright/test";

/**
 * S37 Playwright e2e — the DB-projection Workbench panel (/db-projection).
 * mirror record: reflects=gen.db.{EmitMigration,RequireMigration,DataTruthScope} (the
 *               deterministic, LLM-free expand-contract emitter + the §44.3 guard; the db
 *               migration is a PROJECTION of the entity, below the line), test_kind=e2e,
 *               cert_language=gherkin, liveness=alive, authority=above
 *
 * Scenario: the done criterion — dry-run valid + historical-impact-requires-migration — visible
 *   Given the Workbench is running
 *   When I navigate to /db-projection
 *   Then the emitted-migration panel shows the Atlas text with the protected header + a source: hash
 *   And clicking DRY-RUN makes the dry-run badge read DRY-RUN VALID
 *   And clicking RE-EMIT reports byte-identical (determinism visible)
 *   And a historical-impact change with no scope renders REQUIRES MIGRATION (HISTORICAL_IMPACT_REQUIRES_MIGRATION)
 *   And a declared DataTruthScope renders ALLOWED
 *   And a new-records-only change renders "no migration needed"
 */

test.describe("S37 — DB projection (entity → expand-contract migration + DataTruthScope)", () => {
	test.beforeEach(async ({ page }) => {
		await page.goto("/db-projection");
		await expect(
			page.getByRole("heading", { name: /DB projection/i }),
		).toBeVisible({ timeout: 5000 });
	});

	test("the emitted-migration panel shows the Atlas text with the protected header + a source hash", async ({
		page,
	}) => {
		const migration = page.locator("[data-migration-bytes]");
		await expect(migration).toBeVisible();
		await expect(migration).toContainText(
			"CODE GENERATED BY AIDOS — DO NOT EDIT",
		);
		await expect(migration).toContainText("source:");
		// the additive default scenario is an EXPAND step (ADD COLUMN), no DROP.
		await expect(migration).toContainText("ADD COLUMN");
	});

	test("DRY-RUN makes the dry-run badge read DRY-RUN VALID (the done criterion)", async ({
		page,
	}) => {
		await page.getByRole("button", { name: /^DRY-RUN$/i }).click();
		const badge = page.locator("[data-dryrun-badge]");
		await expect(badge).toHaveAttribute("data-valid", "true");
		await expect(badge).toContainText(/DRY-RUN VALID|DRY-RUN VALIDE/i);
	});

	test("RE-EMIT reports byte-identical (determinism visible)", async ({
		page,
	}) => {
		await page.getByRole("button", { name: /RE-EMIT|RÉ-ÉMETTRE/i }).click();
		await expect(
			page
				.locator("[data-reemit-result]")
				.getByText(/byte-identical|byte-identique/i),
		).toBeVisible();
	});

	test("a historical-impact change with no scope renders REQUIRES MIGRATION", async ({
		page,
	}) => {
		await page.locator('[data-change="historical"]').click();
		const verdict = page.locator("[data-verdict]");
		await expect(verdict).toHaveAttribute("data-kind", "requires");
		await expect(verdict).toContainText(
			/REQUIRES MIGRATION|EXIGE UNE MIGRATION/i,
		);
		await expect(page.locator("[data-block-code]")).toContainText(
			"HISTORICAL_IMPACT_REQUIRES_MIGRATION",
		);
	});

	test("a declared DataTruthScope renders ALLOWED", async ({ page }) => {
		await page.locator('[data-change="declared"]').click();
		const verdict = page.locator("[data-verdict]");
		await expect(verdict).toHaveAttribute("data-kind", "allowed");
		await expect(verdict).toContainText(/ALLOWED|AUTORISÉ/i);
	});

	test('a new-records-only change renders "no migration needed"', async ({
		page,
	}) => {
		await page.locator('[data-change="newOnly"]').click();
		const verdict = page.locator("[data-verdict]");
		await expect(verdict).toHaveAttribute("data-kind", "none");
		await expect(verdict).toContainText(
			/no migration needed|aucune migration/i,
		);
	});
});
