import { expect, test } from "@playwright/test";

/**
 * S34 Playwright e2e — the Emitters Workbench panel (/emitters).
 * mirror record: reflects=runtime.generators.{Emit,Project} (the deterministic, LLM-free emitters,
 *               one per kind × target ; one source → N projections, byte-identical, hash + protected),
 *               test_kind=e2e, cert_language=gherkin, liveness=alive, authority=above
 *
 * Scenario: an entity shows three projections; re-emit is byte-identical; a moved head goes STALE
 *   Given the Workbench is running
 *   When I navigate to /emitters
 *   Then the Order entity shows THREE projection cards (go-sqlc, pg-ddl, ts-types), each carrying a
 *        source_hash and the protected header "CODE GENERATED BY AIDOS — DO NOT EDIT"
 *   And clicking RE-EMIT reports the SAME output_hash (byte-identical — the done criterion visible)
 *   And after I MOVE THE HEAD (remove discount) the prior artifact cards flip to STALE while staying
 *        listed (append-only ledger)
 */

test.describe("S34 — the emitters (one source → three byte-identical, protected projections)", () => {
	test.beforeEach(async ({ page }) => {
		await page.goto("/emitters");
		await expect(page.getByTestId("emitters-panel")).toBeVisible({
			timeout: 5000,
		});
	});

	test("the Order entity shows three projection cards, each with a source_hash + protected header", async ({
		page,
	}) => {
		const cards = page.getByTestId("projection-cards");
		await expect(cards).toBeVisible();

		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await expect(page.getByTestId(`card-${target}`)).toBeVisible();
			await expect(page.getByTestId(`source-hash-${target}`)).toBeVisible();
			await expect(page.getByTestId(`header-${target}`)).toContainText(
				"CODE GENERATED BY AIDOS — DO NOT EDIT",
			);
		}
	});

	test("RE-EMIT reports the same output_hash (byte-identical — the done criterion)", async ({
		page,
	}) => {
		const outputHash = (
			await page.getByTestId("output-hash-go-sqlc").textContent()
		)?.trim();
		expect(outputHash).toBeTruthy();

		await page.getByTestId("reemit-go-sqlc").click();
		await expect(page.getByTestId("byte-identical-go-sqlc")).toBeVisible();

		// The output_hash on the card is unchanged after re-emit (deterministic).
		const after = (
			await page.getByTestId("output-hash-go-sqlc").textContent()
		)?.trim();
		expect(after).toBe(outputHash);
	});

	test("the cards start deterministic; moving the entity head flips them to STALE (append-only)", async ({
		page,
	}) => {
		// Before the head moves, every Order projection is deterministic (source_hash == head).
		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await expect(page.getByTestId(`badge-${target}`)).toHaveAttribute(
				"data-stale",
				"false",
			);
		}

		await page.getByTestId("move-head").click();

		// The prior artifact cards stay listed but flip to STALE (the head moved ahead).
		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await expect(page.getByTestId(`card-${target}`)).toBeVisible();
			await expect(page.getByTestId(`badge-${target}`)).toHaveAttribute(
				"data-stale",
				"true",
			);
		}

		// RESET brings them back to deterministic (the demo is reversible).
		await page.getByTestId("reset-head").click();
		await expect(page.getByTestId("badge-go-sqlc")).toHaveAttribute(
			"data-stale",
			"false",
		);
	});

	// FN03 — EMITTED_FUNCTION_PURE made action-capable: PROVE PURITY re-emits N rounds and the
	// verdict (data-pure="true") shows the emitted code is pure / byte-identical-reproducible.
	test("PROVE PURITY executes and reports the emitted code is pure (FN03)", async ({
		page,
	}) => {
		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await page.getByTestId(`prove-purity-${target}`).click();
			await expect(
				page.getByTestId(`purity-verdict-${target}`),
			).toHaveAttribute("data-pure", "true");
		}
	});

	// FN04 — the three EMITTED arch-fitness rules made action-capable: CHECK ARCH-FITNESS runs the
	// deterministic twin (no global mutable / no init / acyclic call graph) over the emitted Go bytes
	// and reports the verdict (data-archfitness="true" — compliant).
	test("CHECK ARCH-FITNESS executes and reports the emitted Go is compliant (FN04)", async ({
		page,
	}) => {
		await page.getByTestId("arch-fitness-go-sqlc").click();
		await expect(
			page.getByTestId("arch-fitness-verdict-go-sqlc"),
		).toHaveAttribute("data-archfitness", "true");
	});

	// FN05 — the call-graph index made action-capable: INDEX CALL GRAPH runs the deterministic twin
	// (callGraphIndex) over the emitted Go bytes (the Understand-Anything view) and renders the index
	// (content-addressed by hash) + the affected sub-graph the ContextRouter (S33) consumes. The
	// control executes and surfaces a stable, content-addressed verdict.
	test("INDEX CALL GRAPH executes and renders a content-addressed index (FN05)", async ({
		page,
	}) => {
		await page.getByTestId("call-graph-go-sqlc").click();
		const index = page.getByTestId("call-graph-index-go-sqlc");
		await expect(index).toBeVisible();
		// the index carries the deterministic node count (the emitted struct has 0 call nodes — the
		// honest, fail-closed verdict for a function-free projection; same code → same graph).
		await expect(index).toHaveAttribute("data-callgraph-nodes", /^\d+$/);
	});

	// FN06 — the functional graph VISUALISATION of the emitted app made action-capable: VISUALISE runs
	// the deterministic layout (layoutCallGraph) over the emitted functional Go and DRAWS the graph as
	// an SVG (nodes = functions, edges = calls). HIGHLIGHT then marks the affected sub-graph (the
	// ContextRouter S33 selection). The control executes and renders a content-addressed, themed graph.
	test("VISUALISE renders the emitted functional graph as an SVG (FN06)", async ({
		page,
	}) => {
		await page.getByTestId("visualise-graph").click();
		const svg = page.getByTestId("functional-graph-svg");
		await expect(svg).toBeVisible();
		// the emitted checkout-functional sample has three pure functions (priceLine, applyDiscount,
		// total) and three call edges — a real, non-empty graph (not the function-free struct).
		await expect(svg).toHaveAttribute("data-graph-nodes", "3");
		await expect(svg).toHaveAttribute("data-graph-edges", "3");
		await expect(svg).toHaveAttribute("data-graph-hash", /^[0-9a-f]{64}$/);
		// the function nodes are drawn (the Understand-Anything view, one node per function-layer)
		await expect(page.getByTestId("graph-node-total")).toBeVisible();
		await expect(page.getByTestId("graph-node-priceLine")).toBeVisible();
		await expect(page.getByTestId("graph-node-applyDiscount")).toBeVisible();
	});

	// FN06 — HIGHLIGHT executes the ContextRouter selection on the drawn graph: a change to the first
	// function ripples to every transitive caller; those nodes are flagged data-affected="true".
	test("HIGHLIGHT marks the affected sub-graph on the drawn graph (FN06)", async ({
		page,
	}) => {
		await page.getByTestId("visualise-graph-affected").click();
		const svg = page.getByTestId("functional-graph-svg");
		await expect(svg).toBeVisible();
		// a change to applyDiscount (the first node, sorted) affects itself + total (its caller)
		const affected = page.getByTestId("functional-graph-affected");
		await expect(affected).toBeVisible();
		await expect(page.getByTestId("graph-node-applyDiscount")).toHaveAttribute(
			"data-affected",
			"true",
		);
		await expect(page.getByTestId("graph-node-total")).toHaveAttribute(
			"data-affected",
			"true",
		);
		// priceLine is NOT a dependent of applyDiscount → not affected (honest, fail-closed selection)
		await expect(page.getByTestId("graph-node-priceLine")).toHaveAttribute(
			"data-affected",
			"false",
		);
	});
});
