import { expect, test } from "@playwright/test";

/**
 * S34 Playwright e2e — the Emitters Workbench panel (/emitters).
 * mirror record: reflects=runtime.generators.{Emit,Project} (the deterministic, LLM-free emitters,
 *               one per kind × target ; one source → N projections, byte-identical, hash + protected),
 *               test_kind=e2e, cert_language=gherkin, liveness=alive, authority=above
 *
 * Scenario: an entity shows three projections; re-emit is byte-identical; a moved head goes STALE
 *   Given the Workbench is running
 *   When I navigate to /emitters
 *   Then the Order entity shows THREE projection cards (go-sqlc, pg-ddl, ts-types), each carrying a
 *        source_hash and the protected header "CODE GENERATED BY AIDOS — DO NOT EDIT"
 *   And clicking RE-EMIT reports the SAME output_hash (byte-identical — the done criterion visible)
 *   And after I MOVE THE HEAD (remove discount) the prior artifact cards flip to STALE while staying
 *        listed (append-only ledger)
 */

test.describe("S34 — the emitters (one source → three byte-identical, protected projections)", () => {
	test.beforeEach(async ({ page }) => {
		await page.goto("/emitters");
		await expect(page.getByTestId("emitters-panel")).toBeVisible({ timeout: 5000 });
	});

	test("the Order entity shows three projection cards, each with a source_hash + protected header", async ({
		page,
	}) => {
		const cards = page.getByTestId("projection-cards");
		await expect(cards).toBeVisible();

		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await expect(page.getByTestId(`card-${target}`)).toBeVisible();
			await expect(page.getByTestId(`source-hash-${target}`)).toBeVisible();
			await expect(page.getByTestId(`header-${target}`)).toContainText("CODE GENERATED BY AIDOS — DO NOT EDIT");
		}
	});

	test("RE-EMIT reports the same output_hash (byte-identical — the done criterion)", async ({ page }) => {
		const outputHash = (await page.getByTestId("output-hash-go-sqlc").textContent())?.trim();
		expect(outputHash).toBeTruthy();

		await page.getByTestId("reemit-go-sqlc").click();
		await expect(page.getByTestId("byte-identical-go-sqlc")).toBeVisible();

		// The output_hash on the card is unchanged after re-emit (deterministic).
		const after = (await page.getByTestId("output-hash-go-sqlc").textContent())?.trim();
		expect(after).toBe(outputHash);
	});

	test("the cards start deterministic; moving the entity head flips them to STALE (append-only)", async ({
		page,
	}) => {
		// Before the head moves, every Order projection is deterministic (source_hash == head).
		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await expect(page.getByTestId(`badge-${target}`)).toHaveAttribute("data-stale", "false");
		}

		await page.getByTestId("move-head").click();

		// The prior artifact cards stay listed but flip to STALE (the head moved ahead).
		for (const target of ["go-sqlc", "pg-ddl", "ts-types"]) {
			await expect(page.getByTestId(`card-${target}`)).toBeVisible();
			await expect(page.getByTestId(`badge-${target}`)).toHaveAttribute("data-stale", "true");
		}

		// RESET brings them back to deterministic (the demo is reversible).
		await page.getByTestId("reset-head").click();
		await expect(page.getByTestId("badge-go-sqlc")).toHaveAttribute("data-stale", "false");
	});
});
