import { expect, test } from "@playwright/test";

/**
 * DP04 Playwright e2e — the « Émetteur .env.example + scripts » extension of /stack-emit.
 * mirror record: reflects=DP04-env-emitter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the /stack-emit route renders the SEEDED DP04 emission (the .env.example + the
 * start.sh / start_with_rebuild.sh scripts emitted from the SAME manifest as the DP03
 * compose) — the engraved /data/dockers merge order (global → bp-default → bp-secrets →
 * deploy-time) visible on screen, the secret keys carrying REFERENCES only
 * (<<from-secret-store>>, NEVER a value — the S91 contract), the deterministic
 * gitleaks-like scan verdict green, the DP03↔DP04 coherence verdict green — and that the
 * one control re-emits byte-identically (same .env.example output_hash) and keeps the
 * scan green when the manifest gains a connector scope (a NEW secret reference, still no
 * value).
 *
 * THE WALL (CLAUDE.md §2): the screen measures — it writes no truth and no gen/ file.
 * NO sensitive value appears anywhere in this spec (the done-criterion: e2e sans
 * valeurs sensibles).
 */

// The Go-authoritative output_hashes of envemit.Emit(Example()) (pinned by the vitest
// twin mirror lib/env-emit.test.ts).
const GO_ENV_OUTPUT_HASH =
	"0f8a51478417ab8b182947cd10f18471a0c384dd34e3cda40d5e02c3a9a874f9";
const GO_START_OUTPUT_HASH =
	"10525a91a69b915788cc517001216d1b50a893235b0ab269b8d6b35ac1c6b06e";
const GO_REBUILD_OUTPUT_HASH =
	"8a1b598c034efb01d08274b03d236325bfef2d879d87d83ef4b7214952d6f2db";

// React hydration races a plain fill(); retry until the controlled value sticks.
async function setManifestJson(
	textarea: import("@playwright/test").Locator,
	value: string,
): Promise<void> {
	await expect(async () => {
		await textarea.fill(value);
		expect(await textarea.inputValue()).toBe(value);
	}).toPass({ timeout: 10_000 });
}

test.describe("DP04 — the .env.example + scripts emitter (merge order engraved, zero secret values)", () => {
	test("the route renders the seeded .env.example: merge order, secret REFERENCES only, pinned hashes, green scan + coherence", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// the engraved /data/dockers merge order, visible as the emission template.
		await expect(page.getByTestId("merge-order")).toHaveText(
			"global → bp-default → bp-secrets → deploy-time",
		);

		const env = page.getByTestId("env-example");
		await expect(env).toContainText("CODE GENERATED BY AIDOS — DO NOT EDIT");
		// secret keys carry the S91 REFERENCE — never a value.
		await expect(env).toContainText(
			"GITHUB_PERSONAL_ACCESS_TOKEN=<<from-secret-store>>",
		);
		await expect(env).toContainText(
			"APP_SECRET_POSTGRES_READ_ONLY=<<from-secret-store>>",
		);
		// the deploy-time override: APP_NAME valued by deploy.sh, last write wins.
		await expect(env).toContainText("APP_NAME=alphashop");
		// every key the compose references exists (a sample of the closed set).
		for (const key of [
			"APP_SUBDOMAIN=<<set-at-deploy-time>>",
			"DOMAIN=<<set-at-deploy-time>>",
			"CERT_RESOLVER_NAME=<<set-at-deploy-time>>",
			"TRAEFIK_NETWORK_NAME=<<set-at-deploy-time>>",
			"APP_DATA_PATH=<<set-at-deploy-time>>",
			"INTERPRETER_IMAGE=<<set-at-deploy-time>>",
			"APP_PORT=3000",
		]) {
			await expect(env).toContainText(key);
		}

		// the deterministic verdicts — scan green, DP03↔DP04 coherence green.
		await expect(page.getByTestId("scan-verdict")).toHaveAttribute(
			"data-clean",
			"true",
		);
		await expect(page.getByTestId("coherence-verdict")).toHaveAttribute(
			"data-coherent",
			"true",
		);

		// the Go-authoritative double content address (output side).
		await expect(page.getByTestId("env-output-hash")).toHaveText(
			GO_ENV_OUTPUT_HASH,
		);
		await expect(page.getByTestId("start-output-hash")).toHaveText(
			GO_START_OUTPUT_HASH,
		);
		await expect(page.getByTestId("rebuild-output-hash")).toHaveText(
			GO_REBUILD_OUTPUT_HASH,
		);
	});

	test("the scripts are the deploy.sh templates: start.sh down → up; start_with_rebuild.sh down → build --no-cache → up", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		const start = page.getByTestId("start-sh");
		await expect(start).toContainText("#!/usr/bin/env bash");
		await expect(start).toContainText("docker compose down");
		await expect(start).toContainText("docker compose up -d");
		await expect(start).not.toContainText("--no-cache");

		const rebuild = page.getByTestId("rebuild-sh");
		await expect(rebuild).toContainText("docker compose build --no-cache");
		await expect(rebuild).toContainText("docker compose up -d");

		// the additive DP04 targets are registered in the closed matrix.
		await expect(page.getByTestId("targets")).toContainText(
			"stack_manifest × (env-example · start-scripts) — DP04",
		);
	});

	test("« émettre » re-emits the unchanged manifest to the SAME .env.example output_hash (byte-identical), scan green", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		await page.getByTestId("emit").click();

		const result = page.getByTestId("emit-result");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		await expect(page.getByTestId("emitted-env-output-hash")).toHaveText(
			GO_ENV_OUTPUT_HASH,
		);
		await expect(page.getByTestId("env-hash-compare")).toContainText(
			/même manifest → même output_hash|same manifest → same .env.example output_hash/,
		);
		await expect(page.getByTestId("emitted-scan-verdict")).toHaveAttribute(
			"data-clean",
			"true",
		);
		await expect(page.getByTestId("emitted-coherence-verdict")).toHaveAttribute(
			"data-coherent",
			"true",
		);
	});

	test("a NEW connector scope re-emits a NEW secret REFERENCE — still no value, scan still green, new output_hash", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		const textarea = page.getByTestId("manifest-json");
		const json = JSON.parse((await textarea.inputValue()) as string);
		json.connector_scopes = [
			...(json.connector_scopes ?? []),
			"forgejo:read-write",
		];
		await setManifestJson(textarea, JSON.stringify(json, null, 2));
		await page.getByTestId("emit").click();

		const result = page.getByTestId("emit-result");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		// the new scope appears as a REFERENCE in the bp-secrets layer.
		await expect(page.getByTestId("emitted-env")).toContainText(
			"APP_SECRET_FORGEJO_READ_WRITE=<<from-secret-store>>",
		);
		// the emission follows the source: a different manifest → a NEW hash.
		await expect(page.getByTestId("emitted-env-output-hash")).not.toHaveText(
			GO_ENV_OUTPUT_HASH,
		);
		// and STILL zero secret values (the deterministic scan stays green).
		await expect(page.getByTestId("emitted-scan-verdict")).toHaveAttribute(
			"data-clean",
			"true",
		);
	});
});
