import { expect, test } from "@playwright/test";

/**
 * DP05 Playwright e2e — « EmitStack(phase) : le bundle complet » on /stack-emit.
 * mirror record: reflects=DP05-stack-emitter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the /stack-emit route renders the COMPLETE bundle emitted from the
 * content-addressed S23 phase pinning the Example manifest — the phase_version,
 * the bundle_hash (« même phase → mêmes octets »), the traefik dynamic config
 * (file provider, env-var REFERENCES only — never a hardcoded host/value), the
 * Go interpreter sidecar (ADR 0040 Décision 7, role=interpreter profile core),
 * the closed hand-edit refusal code EMITTED_FILE_HAND_EDITED — and that the
 * one control « ré-émettre » re-emits the bundle byte-identically: re-emit
 * TWICE, the bundle_hash is EQUAL each time (the cornerstone done-criterion).
 *
 * THE WALL (CLAUDE.md §2): the screen measures — it writes no truth and no
 * gen/ file; the phase (source) is authoritative, the emission regenerable.
 */

// The Go-authoritative addresses of EmitStack(PhaseFor(Example), Example)
// (pinned by the vitest twin mirror lib/phase-emit.test.ts).
const GO_PHASE_VERSION =
	"a26d29c79ce01cbd6001a665e480685d2d22ca54419864f0314fe6474a9ba76c";
const GO_BUNDLE_HASH =
	"19670343b3cc053593df0f457b466a4ec94871381b69135ac26f6d2eb891af3a";
const GO_TRAEFIK_OUTPUT_HASH =
	"8d08ebf598fea0520cb7fbc2ecd621455397609fc711cf2f9ca8dcf7a4cd9dad";

// React hydration races a plain fill(); retry until the controlled value sticks.
async function setManifestJson(
	textarea: import("@playwright/test").Locator,
	value: string,
): Promise<void> {
	await expect(async () => {
		await textarea.fill(value);
		expect(await textarea.inputValue()).toBe(value);
	}).toPass({ timeout: 10_000 });
}

test.describe("DP05 — the complete stack bundle emitted from the phase (même phase → mêmes octets)", () => {
	test("the route renders the seeded bundle: phase_version + bundle_hash pinned to Go, traefik dynamic config with references only", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// the triple address — phase (S23), bundle (the 5 artifacts).
		await expect(page.getByTestId("phase-version")).toHaveText(
			GO_PHASE_VERSION,
		);
		await expect(page.getByTestId("bundle-hash")).toHaveText(GO_BUNDLE_HASH);
		await expect(page.getByTestId("traefik-output-hash")).toHaveText(
			GO_TRAEFIK_OUTPUT_HASH,
		);

		// the traefik dynamic config — header-protected, references NEVER values.
		const traefik = page.getByTestId("traefik-dynamic");
		await expect(traefik).toContainText(
			"CODE GENERATED BY AIDOS — DO NOT EDIT",
		);
		await expect(traefik).toContainText(
			"rule: Host(`${APP_SUBDOMAIN}.${DOMAIN}`)",
		);
		await expect(traefik).toContainText("certResolver: ${CERT_RESOLVER_NAME}");
		// docker_internal: the container reference on the shared network.
		await expect(traefik).toContainText("url: http://${APP_NAME}:3000");

		// the closed hand-edit refusal code is surfaced (the gen/ protection).
		await expect(page.getByTestId("bundle-card")).toContainText(
			"EMITTED_FILE_HAND_EDITED",
		);

		// the DP05 additive target is registered in the closed matrix.
		await expect(page.getByTestId("targets")).toContainText(
			"stack_manifest × traefik-dynamic + EmitStack(phase) — DP05",
		);
	});

	test("the Go interpreter sidecar (ADR 0040 D7) is visible: role=interpreter, profile core, in the compose and the badge", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		const badge = page.getByTestId("sidecar-badge");
		await expect(badge).toHaveAttribute("data-present", "true");
		await expect(badge).toContainText("interpreter · role=interpreter");
		await expect(badge).toContainText("profile core");

		// the sidecar rides the emitted compose, docker_internal.
		const compose = page.getByTestId("compose-yaml");
		await expect(compose).toContainText("interpreter:");
		await expect(compose).toContainText(
			"container_name: ${APP_NAME}-interpreter",
		);
	});

	test("« ré-émettre » TWICE: the bundle_hash is EQUAL each time (même phase content-adressée → mêmes octets)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// first re-emission — same bundle_hash as the seeded one.
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"emitted",
		);
		await expect(page.getByTestId("emitted-bundle-hash")).toHaveText(
			GO_BUNDLE_HASH,
		);
		await expect(page.getByTestId("bundle-hash-compare")).toHaveAttribute(
			"data-same",
			"true",
		);
		await expect(page.getByTestId("emitted-phase-version")).toHaveText(
			GO_PHASE_VERSION,
		);

		// second re-emission — STILL the same bundle_hash (hash égaux, deux fois).
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("emitted-bundle-hash")).toHaveText(
			GO_BUNDLE_HASH,
		);
		await expect(page.getByTestId("bundle-hash-compare")).toHaveAttribute(
			"data-same",
			"true",
		);
	});

	test("a modified manifest yields a NEW phase + NEW bundle_hash — and the scan + coherence stay green (the emission follows the source)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		const textarea = page.getByTestId("manifest-json");
		const manifest = JSON.parse(await textarea.inputValue());
		manifest.connector_scopes = [
			...(manifest.connector_scopes ?? []),
			"forgejo:read-write",
		];
		await setManifestJson(textarea, JSON.stringify(manifest, null, 2));
		await page.getByTestId("emit").click();

		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"emitted",
		);
		// a different source → a different phase → a different bundle.
		await expect(page.getByTestId("emitted-bundle-hash")).not.toHaveText(
			GO_BUNDLE_HASH,
		);
		await expect(page.getByTestId("bundle-hash-compare")).toHaveAttribute(
			"data-same",
			"false",
		);
		// the new scope adds a REFERENCE — never a value: the scan stays green.
		await expect(page.getByTestId("emitted-env")).toContainText(
			"APP_SECRET_FORGEJO_READ_WRITE=<<from-secret-store>>",
		);
		await expect(page.getByTestId("emitted-scan-verdict")).toHaveAttribute(
			"data-clean",
			"true",
		);
		await expect(page.getByTestId("emitted-coherence-verdict")).toHaveAttribute(
			"data-coherent",
			"true",
		);
	});
});
