import { expect, test } from "@playwright/test";

/**
 * DP03 Playwright e2e — the « Émetteur StackManifest → docker-compose » Workbench panel.
 * mirror record: reflects=DP03-compose-emitter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the /stack-emit route renders the SEEDED emission (the DP03 done-criterion: the
 * emitted compose + its output_hash, themed + bilingual) — the /data/dockers conventions
 * visible on screen (protected header, Traefik HTTPS router + redirect labels, the
 * ${APP_DATA_PATH} bind, external traefik_default, no published ports) — and that the one
 * control (« émettre le compose », ui-completeness CLAUDE.md §7) executes from the screen:
 * re-emitting the unchanged manifest yields the SAME output_hash (byte-identical
 * reproducibility), and the closed-set refusals DUPLICATE_INTERNAL_PORT /
 * UNKNOWN_SERVICE_ROLE / STACK_HAS_NO_SERVER are proven from the screen.
 *
 * THE WALL (CLAUDE.md §2): the screen measures — it writes no truth and no gen/ file;
 * the emitter is SELECT-only on kernel, the projection lands below the line.
 */

// The Go-authoritative double content address of Emit(Example()) (pinned by the vitest
// twin mirror lib/stack-emit.test.ts).
const GO_SOURCE_HASH =
	"8011728e4f9c01130c151d5c49b89b28afa1e3dc5e741fcc12c04c38062acdd2";
const GO_OUTPUT_HASH =
	"efea2247cc8634350680d6e0eb419af6637dade0a76369b8af3f38be6fea24c1";

// React hydration races a plain fill() (the SSR textarea text + the typed value can
// merge); retry until the controlled value sticks — deterministic, no fixed sleep.
async function setManifestJson(
	textarea: import("@playwright/test").Locator,
	value: string,
): Promise<void> {
	await expect(async () => {
		await textarea.fill(value);
		expect(await textarea.inputValue()).toBe(value);
	}).toPass({ timeout: 10_000 });
}

test.describe("DP03 — the docker-compose emitter (additive target)", () => {
	test("the route renders the seeded compose, its double content address and the /data/dockers conventions", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		await expect(
			page.getByRole("heading", {
				level: 1,
				name: /Émetteur StackManifest → docker-compose|StackManifest → docker-compose emitter/,
			}),
		).toBeVisible();

		// the double content address — source (S02 reused) + output (byte-identical proof).
		await expect(page.getByTestId("source-hash")).toHaveText(GO_SOURCE_HASH);
		await expect(page.getByTestId("output-hash")).toHaveText(GO_OUTPUT_HASH);

		// the below-the-line projection path.
		await expect(page.getByTestId("compose-path")).toHaveText(
			"back/gen/alphashop/docker-compose.yml",
		);

		// the /data/dockers conventions, visible in the emitted bytes.
		const yaml = page.getByTestId("compose-yaml");
		await expect(yaml).toContainText("CODE GENERATED BY AIDOS — DO NOT EDIT");
		// biome-ignore lint/suspicious/noTemplateCurlyInString: the compose carries the LITERAL env-var reference (never a hardcoded value) — the assertion must stay a plain string.
		await expect(yaml).toContainText("container_name: ${APP_NAME}");
		await expect(yaml).toContainText(
			// biome-ignore lint/suspicious/noTemplateCurlyInString: literal Traefik label from the emitted compose.
			"traefik.http.routers.${APP_NAME}.entrypoints=websecure",
		);
		await expect(yaml).toContainText(
			// biome-ignore lint/suspicious/noTemplateCurlyInString: literal Traefik redirect middleware label.
			"traefik.http.middlewares.${APP_NAME}-https-redirect.redirectscheme.scheme=https",
		);
		// biome-ignore lint/suspicious/noTemplateCurlyInString: literal named-bind device env-var reference.
		await expect(yaml).toContainText("device: ${APP_DATA_PATH}");
		await expect(yaml).toContainText("external: true");
		await expect(yaml).toContainText("restart: unless-stopped");

		// the additive target is registered in the closed matrix.
		await expect(page.getByTestId("targets")).toContainText(
			"stack_manifest × docker-compose — DP03",
		);
	});

	test("« émettre le compose » executes: the unchanged manifest re-emits to the SAME output_hash (byte-identical)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		await page.getByTestId("emit").click();

		const result = page.getByTestId("emit-result");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		await expect(page.getByTestId("emitted-output-hash")).toHaveText(
			GO_OUTPUT_HASH,
		);
		await expect(page.getByTestId("hash-compare")).toContainText(
			/même manifest → même output_hash|same manifest → same output_hash/,
		);
		// the re-emitted compose is on screen too.
		await expect(page.getByTestId("emitted-yaml")).toContainText(
			"CODE GENERATED BY AIDOS — DO NOT EDIT",
		);
	});

	test("a duplicate internal port is refused from the screen (DUPLICATE_INTERNAL_PORT)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		const textarea = page.getByTestId("manifest-json");
		const json = JSON.parse((await textarea.inputValue()) as string);
		json.services[1].internal_port = json.services[0].internal_port;
		await setManifestJson(textarea, JSON.stringify(json, null, 2));
		await page.getByTestId("emit").click();

		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"refused",
		);
		await expect(page.getByTestId("refusal-code")).toHaveText(
			"DUPLICATE_INTERNAL_PORT",
		);
	});

	test("an unknown role and a server-less stack are refused from the screen", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		const textarea = page.getByTestId("manifest-json");

		// UNKNOWN_SERVICE_ROLE — a role outside the closed set is never guessed a compose.
		const json = JSON.parse((await textarea.inputValue()) as string);
		json.services[1].role = "blockchain";
		await setManifestJson(textarea, JSON.stringify(json, null, 2));
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("refusal-code")).toHaveText(
			"UNKNOWN_SERVICE_ROLE",
		);

		// STACK_HAS_NO_SERVER — no role=server service left.
		const json2 = JSON.parse(JSON.stringify(json));
		json2.services[1].role = "datastore";
		for (const s of json2.services) {
			if (s.role === "server") s.role = "cache";
		}
		await setManifestJson(textarea, JSON.stringify(json2, null, 2));
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("refusal-code")).toHaveText(
			"STACK_HAS_NO_SERVER",
		);
	});
});

/**
 * DP04 Playwright e2e — the « .env.example + scripts » section on /stack-emit.
 * mirror record: reflects=DP04-env-emitter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the DP04 done-criterion FROM THE SCREEN: the /stack-emit route is extended with
 * the .env.example + start.sh + start_with_rebuild.sh tab; the emitted .env.example carries
 * EVERY expected key (APP_NAME, APP_SUBDOMAIN, DOMAIN, CERT_RESOLVER_NAME, the volume device
 * var, TRAEFIK_NETWORK_NAME, the per-service ports) and ZERO secret values — every secret key
 * is the <<from-secret-store>> reference (the deterministic scan is GREEN on screen), the
 * engraved /data/dockers merge order is visible, the DP03↔DP04 coherence verdict holds, the
 * scripts are the down→up / down→build --no-cache→up templates, and the « ré-émettre » control
 * (ui-completeness, CLAUDE.md §7) re-emits the unchanged manifest to the SAME .env.example
 * output_hash (byte-identical) with the scan still clean.
 *
 * THE WALL (§2): the screen measures — it writes no truth and no gen/ file; the secrets never
 * enter the source (S91), they stay encrypted + project-scoped and are injected at boot (DP32).
 */

// The Go-authoritative .env.example output hash of Emit(Example()) — byte-parity-pinned by the
// vitest twin (lib/env-emit.test.ts: GO_ENV_OUTPUT_HASH).
const GO_ENV_OUTPUT_HASH =
	"0f8a51478417ab8b182947cd10f18471a0c384dd34e3cda40d5e02c3a9a874f9";

test.describe("DP04 — the .env.example + scripts emitter (no secret values)", () => {
	test("the route renders the seeded .env.example with every key, zero secret value, the engraved merge order and the coherence verdict", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// the engraved /data/dockers merge order is on screen.
		await expect(page.getByTestId("merge-order")).toContainText(
			"global → bp-default → bp-secrets → deploy-time",
		);

		const env = page.getByTestId("env-example");
		await expect(env).toContainText("CODE GENERATED BY AIDOS — DO NOT EDIT");
		// every expected key the app awaits exists.
		for (const key of [
			"APP_NAME=alphashop",
			"APP_SUBDOMAIN=",
			"DOMAIN=",
			"CERT_RESOLVER_NAME=",
			"APP_DATA_PATH=",
			"TRAEFIK_NETWORK_NAME=",
			"APP_PORT=3000",
			"POSTGRES_PORT=5432",
		]) {
			await expect(env).toContainText(key);
		}
		// ZERO secret values — every secret key is the S91 reference, never a value.
		await expect(env).toContainText(
			"GITHUB_PERSONAL_ACCESS_TOKEN=<<from-secret-store>>",
		);
		await expect(env).toContainText(
			"APP_SECRET_POSTGRES_READ_ONLY=<<from-secret-store>>",
		);

		// the deterministic scan verdict is GREEN (code, never an LLM) and the
		// DP03↔DP04 coherence verdict holds (every ${VAR} ref has a key).
		await expect(page.getByTestId("scan-verdict")).toHaveAttribute(
			"data-clean",
			"true",
		);
		await expect(page.getByTestId("coherence-verdict")).toHaveAttribute(
			"data-coherent",
			"true",
		);

		// the .env.example double content address (Go-authoritative, twin-pinned).
		await expect(page.getByTestId("env-output-hash")).toHaveText(
			GO_ENV_OUTPUT_HASH,
		);

		// the scripts are the deploy.sh templates: down → up / down → build --no-cache → up.
		const startSh = page.getByTestId("start-sh");
		await expect(startSh).toContainText("docker compose down");
		await expect(startSh).toContainText("docker compose up -d");
		await expect(startSh).not.toContainText("--no-cache");
		const rebuildSh = page.getByTestId("rebuild-sh");
		await expect(rebuildSh).toContainText("docker compose build --no-cache");
		await expect(rebuildSh).toContainText("docker compose down");
		await expect(rebuildSh).toContainText("docker compose up -d");
	});

	test("« ré-émettre » executes: the unchanged manifest re-emits the SAME .env.example output_hash with the scan still clean", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		await page.getByTestId("emit").click();

		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"emitted",
		);
		await expect(page.getByTestId("emitted-env-output-hash")).toHaveText(
			GO_ENV_OUTPUT_HASH,
		);
		await expect(page.getByTestId("env-hash-compare")).toContainText(
			/même manifest → même output_hash \.env\.example|same manifest → same \.env\.example output_hash/,
		);
		// the re-emitted .env.example scan stays clean — zero secret value leaked.
		await expect(page.getByTestId("emitted-scan-verdict")).toHaveAttribute(
			"data-clean",
			"true",
		);
	});
});

/**
 * DP11 Playwright e2e — the « Profils déterministes » selector on /stack-emit.
 * mirror record: reflects=DP11-profile-filter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the DP11 done-criterion from the screen: a profile selector over the
 * CLOSED SPEC-stack-2026 set re-emits the compose NARROWED by the selection —
 * services appear/disappear (core => fewer; full => more), byte-identical per
 * selection, core included in full; the cross non-prod × prod surfaces the DP06
 * BlockReason. The selection is DECLARED (a closed dropdown — an unknown profile
 * is unselectable), never inferred. THE WALL (§2): the screen measures, it writes
 * nothing.
 */
/**
 * DP05 Playwright e2e — the « bundle complet émis depuis la phase » section on /stack-emit.
 * mirror record: reflects=DP05-stack-emitter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the DP05 done-criterion FROM THE SCREEN (« route /stack-emit montre bundle complet
 * par phase + bouton ré-émettre exécutable ; Playwright e2e ré-émettre deux fois, hash égaux ») :
 * the /stack-emit route renders the COMPLETE bundle of the seeded Example phase — the
 * phase_version (the S23 content address pinning the manifest), the bundle_hash (Go-authoritative,
 * twin-pinned), the Go interpreter SIDECAR (ADR 0040 D7: role=interpreter · profile core, the
 * sidecar is PRESENT), the traefik.dynamic.yml file-provider config (HTTPS router + redirect +
 * docker_internal service URL, env-var REFERENCES only — never a hardcoded host), and the
 * EMITTED_FILE_HAND_EDITED gate label. The « émettre » control (ui-completeness, CLAUDE.md §7)
 * re-emits the unchanged manifest TWICE — the bundle_hash is byte-identical to the seeded one
 * («ré-émettre deux fois, hash égaux»: the cornerstone reproducibility, ONE comparison).
 *
 * THE WALL (§2): the phase (source) is authoritative; the emitted bundle is regenerable, never the
 * reverse. The screen measures — it writes no truth and no gen/ file; the re-emission is below-the-line.
 */

// The Go-authoritative phase_version + bundle_hash of EmitStack(PhaseFor(Example())) — byte-parity-
// pinned by the vitest twin (lib/phase-emit.test.ts: GO_PHASE_VERSION / GO_BUNDLE_HASH).
const GO_PHASE_VERSION =
	"a26d29c79ce01cbd6001a665e480685d2d22ca54419864f0314fe6474a9ba76c";
const GO_BUNDLE_HASH =
	"19670343b3cc053593df0f457b466a4ec94871381b69135ac26f6d2eb891af3a";

test.describe("DP05 — the complete stack bundle from a phase (cornerstone reproducibility)", () => {
	test("the route renders the seeded bundle: phase_version, bundle_hash, the interpreter sidecar and the traefik dynamic config", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// the triple content address — the phase (S23) and the bundle's own output hash.
		await expect(page.getByTestId("phase-version")).toHaveText(
			GO_PHASE_VERSION,
		);
		await expect(page.getByTestId("bundle-hash")).toHaveText(GO_BUNDLE_HASH);

		// the Go interpreter sidecar (ADR 0040 D7) is PRESENT — role=interpreter, profile core.
		const sidecar = page.getByTestId("sidecar-badge");
		await expect(sidecar).toHaveAttribute("data-present", "true");
		await expect(sidecar).toContainText("interpreter");
		await expect(sidecar).toContainText("role=interpreter");
		await expect(sidecar).toContainText("profile core");

		// the traefik dynamic config — file provider, env-var REFERENCES only (no hardcoded host).
		const traefik = page.getByTestId("traefik-dynamic");
		await expect(traefik).toContainText(
			"CODE GENERATED BY AIDOS — DO NOT EDIT",
		);
		await expect(traefik).toContainText("http:");
		await expect(traefik).toContainText("routers:");
		// biome-ignore lint/suspicious/noTemplateCurlyInString: literal ${VAR} env reference in the emitted traefik config — never a hardcoded value.
		await expect(traefik).toContainText("Host(`${APP_SUBDOMAIN}.${DOMAIN}`)");
		// biome-ignore lint/suspicious/noTemplateCurlyInString: literal ${VAR} cert-resolver reference resolved at deploy time — never a hardcoded value.
		await expect(traefik).toContainText("certResolver: ${CERT_RESOLVER_NAME}");
		// biome-ignore lint/suspicious/noTemplateCurlyInString: literal docker_internal service URL (container name is the ${APP_NAME} reference).
		await expect(traefik).toContainText("url: http://${APP_NAME}:");
		await expect(traefik).toContainText("redirectScheme:");

		// the hand-edit gate code is surfaced on screen.
		await expect(page.getByTestId("bundle-card")).toContainText(
			"EMITTED_FILE_HAND_EDITED",
		);

		// the additive DP05 target is registered in the closed matrix.
		await expect(page.getByTestId("targets")).toContainText(
			"stack_manifest × traefik-dynamic + EmitStack(phase) — DP05",
		);
	});

	test("« ré-émettre » executes TWICE: the unchanged phase re-emits the SAME bundle_hash (ré-émettre deux fois, hash égaux)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// FIRST re-emission of the unchanged manifest.
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"emitted",
		);
		await expect(page.getByTestId("emitted-bundle-hash")).toHaveText(
			GO_BUNDLE_HASH,
		);
		await expect(page.getByTestId("bundle-hash-compare")).toHaveAttribute(
			"data-same",
			"true",
		);
		await expect(page.getByTestId("bundle-hash-compare")).toContainText(
			/même phase → même bundle_hash|same phase → same bundle_hash/,
		);
		await expect(page.getByTestId("emitted-phase-version")).toHaveText(
			GO_PHASE_VERSION,
		);
		const firstBundle =
			(await page.getByTestId("emitted-bundle-hash").textContent()) ?? "";

		// SECOND re-emission — byte-identical: the two bundle hashes are EQUAL.
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"emitted",
		);
		const secondBundle =
			(await page.getByTestId("emitted-bundle-hash").textContent()) ?? "";
		expect(secondBundle).toBe(firstBundle);
		expect(secondBundle).toBe(GO_BUNDLE_HASH);
		// the re-emitted traefik config is on screen too (env-var references only).
		await expect(page.getByTestId("emitted-traefik")).toContainText(
			// biome-ignore lint/suspicious/noTemplateCurlyInString: literal ${VAR} cert-resolver reference — never a hardcoded value.
			"certResolver: ${CERT_RESOLVER_NAME}",
		);
	});

	test("a manifest edit yields a NEW phase + NEW bundle_hash (the emission follows the source, never the reverse)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		const textarea = page.getByTestId("manifest-json");
		const json = JSON.parse((await textarea.inputValue()) as string);
		json.app = `${json.app}beta`;
		await setManifestJson(textarea, JSON.stringify(json, null, 2));
		await page.getByTestId("emit").click();

		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"emitted",
		);
		// a different manifest → a different phase → a different bundle_hash.
		await expect(page.getByTestId("emitted-bundle-hash")).not.toHaveText(
			GO_BUNDLE_HASH,
		);
		await expect(page.getByTestId("bundle-hash-compare")).toHaveAttribute(
			"data-same",
			"false",
		);
		await expect(page.getByTestId("emitted-phase-version")).not.toHaveText(
			GO_PHASE_VERSION,
		);
	});
});

test.describe("DP11 — the deterministic profile selector (include/exclude)", () => {
	test("switching profile makes services appear/disappear (core ⊊ full, core in full)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		const selector = page.getByTestId("stack-emit-profile");
		await expect(selector).toBeVisible();
		// the dropdown is the CLOSED set — exactly the 9 profiles, no more.
		await expect(selector.locator("option")).toHaveCount(9);

		const result = page.getByTestId("profile-result");
		const yaml = page.getByTestId("profile-yaml");
		const kept = page.getByTestId("profile-kept");

		// `full` — the deterministic UNION: every service of the profiled manifest.
		await selector.selectOption("full");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		// the « N/total kept » verdict re-emits per selection — wait on the kept
		// list (server-action result), never on the optimistic state attribute, so
		// the read reflects the SELECTION, not a stale render (no fixed sleep).
		await expect(kept).toContainText("svc-git");
		await expect(kept).toContainText("svc-docs");
		// the core server + the opt-in services are all present under full.
		await expect(yaml).toContainText("app:");
		await expect(yaml).toContainText("svc-git:");
		await expect(yaml).toContainText("svc-docs:");
		const fullYaml = (await yaml.textContent()) ?? "";

		// `git` — narrows: core stays, the other opt-ins drop. FEWER than full.
		await selector.selectOption("git");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		// wait for the git emission to LAND (the docs opt-in disappears) before
		// reading — the retrying matcher is the synchronisation point.
		await expect(kept).not.toContainText("svc-docs");
		await expect(kept).toContainText("svc-git");
		await expect(yaml).not.toContainText("svc-docs:");
		// core is still in (the server survives every selection).
		await expect(yaml).toContainText("app:");
		await expect(yaml).toContainText("svc-git:");
		const gitYaml = (await yaml.textContent()) ?? "";

		// the text DIFFERS between selections, and git is strictly shorter (fewer
		// services emitted) — the include/exclude is visible on screen.
		expect(gitYaml).not.toBe(fullYaml);
		expect(gitYaml.length).toBeLessThan(fullYaml.length);
		// the core server is present in BOTH (core ⊆ every selection ⊆ full).
		expect(fullYaml).toContain("app:");
		expect(gitYaml).toContain("app:");
	});

	test("the cross non-prod × prod surfaces the DP06 BlockReason (DOLTGRES_NOT_ALLOWED_IN_PROD)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// select prod, then the non-prod profile → the DP06 gate refuses (reused).
		await page.getByTestId("stack-emit-env").selectOption("prod");
		await page.getByTestId("stack-emit-profile").selectOption("non-prod");

		const result = page.getByTestId("profile-result");
		await expect(result).toHaveAttribute("data-outcome", "blocked");
		await expect(page.getByTestId("profile-block-code")).toHaveText(
			"DOLTGRES_NOT_ALLOWED_IN_PROD",
		);

		// off the cross — the same non-prod profile against dev passes (emitted).
		await page.getByTestId("stack-emit-env").selectOption("dev");
		await page.getByTestId("stack-emit-profile").selectOption("non-prod");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
	});
});
