import { expect, test } from "@playwright/test";

/**
 * DP03 Playwright e2e — the « Émetteur StackManifest → docker-compose » Workbench panel.
 * mirror record: reflects=DP03-compose-emitter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the /stack-emit route renders the SEEDED emission (the DP03 done-criterion: the
 * emitted compose + its output_hash, themed + bilingual) — the /data/dockers conventions
 * visible on screen (protected header, Traefik HTTPS router + redirect labels, the
 * ${APP_DATA_PATH} bind, external traefik_default, no published ports) — and that the one
 * control (« émettre le compose », ui-completeness CLAUDE.md §7) executes from the screen:
 * re-emitting the unchanged manifest yields the SAME output_hash (byte-identical
 * reproducibility), and the closed-set refusals DUPLICATE_INTERNAL_PORT /
 * UNKNOWN_SERVICE_ROLE / STACK_HAS_NO_SERVER are proven from the screen.
 *
 * THE WALL (CLAUDE.md §2): the screen measures — it writes no truth and no gen/ file;
 * the emitter is SELECT-only on kernel, the projection lands below the line.
 */

// The Go-authoritative double content address of Emit(Example()) (pinned by the vitest
// twin mirror lib/stack-emit.test.ts).
const GO_SOURCE_HASH =
	"8011728e4f9c01130c151d5c49b89b28afa1e3dc5e741fcc12c04c38062acdd2";
const GO_OUTPUT_HASH =
	"efea2247cc8634350680d6e0eb419af6637dade0a76369b8af3f38be6fea24c1";

// React hydration races a plain fill() (the SSR textarea text + the typed value can
// merge); retry until the controlled value sticks — deterministic, no fixed sleep.
async function setManifestJson(
	textarea: import("@playwright/test").Locator,
	value: string,
): Promise<void> {
	await expect(async () => {
		await textarea.fill(value);
		expect(await textarea.inputValue()).toBe(value);
	}).toPass({ timeout: 10_000 });
}

test.describe("DP03 — the docker-compose emitter (additive target)", () => {
	test("the route renders the seeded compose, its double content address and the /data/dockers conventions", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		await expect(
			page.getByRole("heading", {
				level: 1,
				name: /Émetteur StackManifest → docker-compose|StackManifest → docker-compose emitter/,
			}),
		).toBeVisible();

		// the double content address — source (S02 reused) + output (byte-identical proof).
		await expect(page.getByTestId("source-hash")).toHaveText(GO_SOURCE_HASH);
		await expect(page.getByTestId("output-hash")).toHaveText(GO_OUTPUT_HASH);

		// the below-the-line projection path.
		await expect(page.getByTestId("compose-path")).toHaveText(
			"back/gen/alphashop/docker-compose.yml",
		);

		// the /data/dockers conventions, visible in the emitted bytes.
		const yaml = page.getByTestId("compose-yaml");
		await expect(yaml).toContainText("CODE GENERATED BY AIDOS — DO NOT EDIT");
		// biome-ignore lint/suspicious/noTemplateCurlyInString: the compose carries the LITERAL env-var reference (never a hardcoded value) — the assertion must stay a plain string.
		await expect(yaml).toContainText("container_name: ${APP_NAME}");
		await expect(yaml).toContainText(
			// biome-ignore lint/suspicious/noTemplateCurlyInString: literal Traefik label from the emitted compose.
			"traefik.http.routers.${APP_NAME}.entrypoints=websecure",
		);
		await expect(yaml).toContainText(
			// biome-ignore lint/suspicious/noTemplateCurlyInString: literal Traefik redirect middleware label.
			"traefik.http.middlewares.${APP_NAME}-https-redirect.redirectscheme.scheme=https",
		);
		// biome-ignore lint/suspicious/noTemplateCurlyInString: literal named-bind device env-var reference.
		await expect(yaml).toContainText("device: ${APP_DATA_PATH}");
		await expect(yaml).toContainText("external: true");
		await expect(yaml).toContainText("restart: unless-stopped");

		// the additive target is registered in the closed matrix.
		await expect(page.getByTestId("targets")).toContainText(
			"stack_manifest × docker-compose — DP03",
		);
	});

	test("« émettre le compose » executes: the unchanged manifest re-emits to the SAME output_hash (byte-identical)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		await page.getByTestId("emit").click();

		const result = page.getByTestId("emit-result");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		await expect(page.getByTestId("emitted-output-hash")).toHaveText(
			GO_OUTPUT_HASH,
		);
		await expect(page.getByTestId("hash-compare")).toContainText(
			/même manifest → même output_hash|same manifest → same output_hash/,
		);
		// the re-emitted compose is on screen too.
		await expect(page.getByTestId("emitted-yaml")).toContainText(
			"CODE GENERATED BY AIDOS — DO NOT EDIT",
		);
	});

	test("a duplicate internal port is refused from the screen (DUPLICATE_INTERNAL_PORT)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		const textarea = page.getByTestId("manifest-json");
		const json = JSON.parse((await textarea.inputValue()) as string);
		json.services[1].internal_port = json.services[0].internal_port;
		await setManifestJson(textarea, JSON.stringify(json, null, 2));
		await page.getByTestId("emit").click();

		await expect(page.getByTestId("emit-result")).toHaveAttribute(
			"data-outcome",
			"refused",
		);
		await expect(page.getByTestId("refusal-code")).toHaveText(
			"DUPLICATE_INTERNAL_PORT",
		);
	});

	test("an unknown role and a server-less stack are refused from the screen", async ({
		page,
	}) => {
		await page.goto("/stack-emit");
		const textarea = page.getByTestId("manifest-json");

		// UNKNOWN_SERVICE_ROLE — a role outside the closed set is never guessed a compose.
		const json = JSON.parse((await textarea.inputValue()) as string);
		json.services[1].role = "blockchain";
		await setManifestJson(textarea, JSON.stringify(json, null, 2));
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("refusal-code")).toHaveText(
			"UNKNOWN_SERVICE_ROLE",
		);

		// STACK_HAS_NO_SERVER — no role=server service left.
		const json2 = JSON.parse(JSON.stringify(json));
		json2.services[1].role = "datastore";
		for (const s of json2.services) {
			if (s.role === "server") s.role = "cache";
		}
		await setManifestJson(textarea, JSON.stringify(json2, null, 2));
		await page.getByTestId("emit").click();
		await expect(page.getByTestId("refusal-code")).toHaveText(
			"STACK_HAS_NO_SERVER",
		);
	});
});

/**
 * DP11 Playwright e2e — the « Profils déterministes » selector on /stack-emit.
 * mirror record: reflects=DP11-profile-filter, test_kind=e2e, cert_language=playwright, liveness=live
 *
 * Proves the DP11 done-criterion from the screen: a profile selector over the
 * CLOSED SPEC-stack-2026 set re-emits the compose NARROWED by the selection —
 * services appear/disappear (core => fewer; full => more), byte-identical per
 * selection, core included in full; the cross non-prod × prod surfaces the DP06
 * BlockReason. The selection is DECLARED (a closed dropdown — an unknown profile
 * is unselectable), never inferred. THE WALL (§2): the screen measures, it writes
 * nothing.
 */
test.describe("DP11 — the deterministic profile selector (include/exclude)", () => {
	test("switching profile makes services appear/disappear (core ⊊ full, core in full)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		const selector = page.getByTestId("stack-emit-profile");
		await expect(selector).toBeVisible();
		// the dropdown is the CLOSED set — exactly the 9 profiles, no more.
		await expect(selector.locator("option")).toHaveCount(9);

		const result = page.getByTestId("profile-result");
		const yaml = page.getByTestId("profile-yaml");
		const kept = page.getByTestId("profile-kept");

		// `full` — the deterministic UNION: every service of the profiled manifest.
		await selector.selectOption("full");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		// the « N/total kept » verdict re-emits per selection — wait on the kept
		// list (server-action result), never on the optimistic state attribute, so
		// the read reflects the SELECTION, not a stale render (no fixed sleep).
		await expect(kept).toContainText("svc-git");
		await expect(kept).toContainText("svc-docs");
		// the core server + the opt-in services are all present under full.
		await expect(yaml).toContainText("app:");
		await expect(yaml).toContainText("svc-git:");
		await expect(yaml).toContainText("svc-docs:");
		const fullYaml = (await yaml.textContent()) ?? "";

		// `git` — narrows: core stays, the other opt-ins drop. FEWER than full.
		await selector.selectOption("git");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
		// wait for the git emission to LAND (the docs opt-in disappears) before
		// reading — the retrying matcher is the synchronisation point.
		await expect(kept).not.toContainText("svc-docs");
		await expect(kept).toContainText("svc-git");
		await expect(yaml).not.toContainText("svc-docs:");
		// core is still in (the server survives every selection).
		await expect(yaml).toContainText("app:");
		await expect(yaml).toContainText("svc-git:");
		const gitYaml = (await yaml.textContent()) ?? "";

		// the text DIFFERS between selections, and git is strictly shorter (fewer
		// services emitted) — the include/exclude is visible on screen.
		expect(gitYaml).not.toBe(fullYaml);
		expect(gitYaml.length).toBeLessThan(fullYaml.length);
		// the core server is present in BOTH (core ⊆ every selection ⊆ full).
		expect(fullYaml).toContain("app:");
		expect(gitYaml).toContain("app:");
	});

	test("the cross non-prod × prod surfaces the DP06 BlockReason (DOLTGRES_NOT_ALLOWED_IN_PROD)", async ({
		page,
	}) => {
		await page.goto("/stack-emit");

		// select prod, then the non-prod profile → the DP06 gate refuses (reused).
		await page.getByTestId("stack-emit-env").selectOption("prod");
		await page.getByTestId("stack-emit-profile").selectOption("non-prod");

		const result = page.getByTestId("profile-result");
		await expect(result).toHaveAttribute("data-outcome", "blocked");
		await expect(page.getByTestId("profile-block-code")).toHaveText(
			"DOLTGRES_NOT_ALLOWED_IN_PROD",
		);

		// off the cross — the same non-prod profile against dev passes (emitted).
		await page.getByTestId("stack-emit-env").selectOption("dev");
		await page.getByTestId("stack-emit-profile").selectOption("non-prod");
		await expect(result).toHaveAttribute("data-outcome", "emitted");
	});
});
