"use client";

import { useMemo, useState } from "react";
import {
	type Change,
	emitMigration,
	GO_CREATE_SOURCE_HASH,
	GO_NARROW_SOURCE_HASH,
	requireMigration,
} from "@/lib/db-projection";
import {
	DECLARED_SCOPE,
	HISTORICAL_CHANGE,
	NEW_ONLY_CHANGE,
	ORDER_NARROWED,
	ORDER_NEW,
	ORDER_PRIOR,
} from "@/lib/db-projection-data";

/**
 * DbProjectionPanel — the action-capable /db-projection panel (S37). The human RUNS the
 * db projection FROM THE SCREEN: on the left the entity's EMITTED expand-contract Atlas
 * migration (read-only, protected header + source_hash, marked "derived projection") with
 * a DRY-RUN VALID badge, two actions — RE-EMIT (the byte-identical determinism check) and
 * DRY-RUN (the migration applies on the ephemeral engine, proven green in the Go
 * Testcontainers leg). On the right, a change-descriptor selector evaluates the §44.3
 * DataTruthScope guard: REQUIRES MIGRATION (historical impact, no scope), ALLOWED
 * (migration declared), or "no migration needed" (new-records-only). Everything is
 * COMPUTED by the deterministic twin lib/db-projection.ts (byte-identical to
 * back/gen/db) — no LLM, no I/O. READ-ONLY against truth (the wall): the entity is a
 * SOURCE above the line; back/gen/db is never hand-edited; a DataTruthScope is written via
 * propose → ChangeSet → approval, never from a screen. Themed (ADR 0010), bilingual (ADR 0011).
 */

interface Labels {
	migrationTitle: string;
	derivedBadge: string;
	protectedBadge: string;
	expandBadge: string;
	contractBadge: string;
	sourceHashLabel: string;
	pathLabel: string;
	reemitCta: string;
	dryrunCta: string;
	byteIdenticalOk: string;
	dryRunValid: string;
	scopeTitle: string;
	additiveLabel: string;
	narrowingLabel: string;
	historicalLabel: string;
	declaredLabel: string;
	newOnlyLabel: string;
	appliesToLabel: string;
	strategyLabel: string;
	preserveLabel: string;
	requiresBadge: string;
	allowedBadge: string;
	noMigrationBadge: string;
	verdictTitle: string;
}

type Scenario = "additive" | "narrowing";
type ChangeChoice = "historical" | "declared" | "newOnly";

function short(h: string): string {
	return h.slice(0, 16);
}

const CHANGE_OF: Record<ChangeChoice, Change> = {
	historical: HISTORICAL_CHANGE,
	declared: { ...HISTORICAL_CHANGE, scope: DECLARED_SCOPE },
	newOnly: NEW_ONLY_CHANGE,
};

export function DbProjectionPanel({ labels }: { labels: Labels }) {
	const [scenario, setScenario] = useState<Scenario>("additive");
	const [reemitOk, setReemitOk] = useState<boolean | null>(null);
	const [dryRun, setDryRun] = useState<boolean | null>(null);
	const [choice, setChoice] = useState<ChangeChoice>("historical");

	const artifact = useMemo(() => {
		if (scenario === "additive") {
			return emitMigration(ORDER_NEW, ORDER_PRIOR, GO_CREATE_SOURCE_HASH);
		}
		return emitMigration(ORDER_NARROWED, ORDER_PRIOR, GO_NARROW_SOURCE_HASH);
	}, [scenario]);

	function reEmit() {
		const fresh =
			scenario === "additive"
				? emitMigration(ORDER_NEW, ORDER_PRIOR, GO_CREATE_SOURCE_HASH)
				: emitMigration(ORDER_NARROWED, ORDER_PRIOR, GO_NARROW_SOURCE_HASH);
		setReemitOk(fresh.bytes === artifact.bytes);
	}

	function doDryRun() {
		// The dry-run is the real Go Testcontainers leg; on screen we assert the emitted
		// migration carries the protected header + a valid forward-only shape (the same
		// shape the engine accepted). Deterministic, no I/O.
		const valid =
			artifact.bytes.includes("CODE GENERATED BY AIDOS") &&
			!/^\s*ALTER TABLE.+DROP COLUMN(?!.+IF EXISTS)/m.test(artifact.bytes) &&
			(artifact.shape !== "expand_contract" ||
				(artifact.bytes.includes("EXPAND") &&
					artifact.bytes.includes("BACKFILL") &&
					artifact.bytes.includes("CONTRACT")));
		setDryRun(valid);
	}

	const change = CHANGE_OF[choice];
	const verdict = useMemo(() => requireMigration(change), [change]);
	const verdictKind: "requires" | "allowed" | "none" = !verdict.required
		? "none"
		: verdict.block
			? "requires"
			: "allowed";

	return (
		<div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,22rem)]">
			{/* ── The emitted expand-contract migration (left) ───────────── */}
			<article
				data-migration="order"
				className="rounded-lg border border-border bg-card p-4"
			>
				<div className="flex flex-wrap items-center justify-between gap-2">
					<div className="flex items-center gap-2">
						<h2 className="text-lg font-semibold text-foreground">
							{labels.migrationTitle}
						</h2>
						<span className="rounded bg-accent px-1.5 py-0.5 text-xs text-accent-foreground">
							{labels.derivedBadge}
						</span>
						<span className="rounded bg-emerald-500/15 px-1.5 py-0.5 text-xs font-medium text-emerald-600">
							{labels.protectedBadge}
						</span>
						<span
							data-shape
							className="rounded bg-blue-600 px-1.5 py-0.5 text-xs font-medium text-white"
						>
							{artifact.shape === "expand_contract"
								? labels.contractBadge
								: labels.expandBadge}
						</span>
					</div>
				</div>

				{/* Scenario toggle: additive (expand) vs narrowing (expand→backfill→contract). */}
				<fieldset
					className="mt-3 flex gap-2 border-0 p-0"
					aria-label={labels.migrationTitle}
				>
					<button
						type="button"
						data-scenario="additive"
						aria-pressed={scenario === "additive"}
						onClick={() => {
							setScenario("additive");
							setReemitOk(null);
							setDryRun(null);
						}}
						className={`rounded-md border px-2.5 py-1 text-xs transition-colors ${
							scenario === "additive"
								? "border-blue-600 bg-blue-600 text-white"
								: "border-border text-foreground hover:bg-accent"
						}`}
					>
						{labels.additiveLabel}
					</button>
					<button
						type="button"
						data-scenario="narrowing"
						aria-pressed={scenario === "narrowing"}
						onClick={() => {
							setScenario("narrowing");
							setReemitOk(null);
							setDryRun(null);
						}}
						className={`rounded-md border px-2.5 py-1 text-xs transition-colors ${
							scenario === "narrowing"
								? "border-blue-600 bg-blue-600 text-white"
								: "border-border text-foreground hover:bg-accent"
						}`}
					>
						{labels.narrowingLabel}
					</button>
				</fieldset>

				<dl className="mt-3 grid grid-cols-1 gap-1 text-xs text-muted-foreground sm:grid-cols-2">
					<div>
						{labels.sourceHashLabel}:{" "}
						<code className="font-mono text-foreground">
							{short(artifact.sourceHash)}
						</code>
					</div>
					<div>
						{labels.pathLabel}:{" "}
						<code className="font-mono text-foreground">
							back/gen/db/order.sql
						</code>
					</div>
				</dl>

				<div className="mt-3 flex flex-wrap gap-2">
					<button
						type="button"
						onClick={reEmit}
						className="rounded-md border border-border px-2.5 py-1 text-xs text-foreground transition-colors hover:bg-accent"
					>
						{labels.reemitCta}
					</button>
					<button
						type="button"
						onClick={doDryRun}
						className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-blue-700"
					>
						{labels.dryrunCta}
					</button>
				</div>
				{reemitOk !== null ? (
					<p
						data-reemit-result
						className={`mt-2 text-xs font-medium ${reemitOk ? "text-emerald-600" : "text-red-600"}`}
					>
						{reemitOk ? labels.byteIdenticalOk : "—"}
					</p>
				) : null}
				{dryRun !== null ? (
					<p
						data-dryrun-badge
						data-valid={dryRun ? "true" : "false"}
						className={`mt-2 rounded-md px-3 py-2 text-sm font-medium ${
							dryRun
								? "bg-emerald-500/15 text-emerald-600"
								: "bg-red-500/15 text-red-600"
						}`}
					>
						{dryRun ? labels.dryRunValid : "—"}
					</p>
				) : null}

				<pre className="mt-3 max-h-96 overflow-auto rounded-md bg-background p-3 text-xs leading-relaxed text-foreground">
					<code data-migration-bytes>{artifact.bytes}</code>
				</pre>
			</article>

			{/* ── The DataTruthScope verdict (right) ─────────────────────── */}
			<section className="space-y-4">
				<h2 className="text-lg font-semibold text-foreground">
					{labels.scopeTitle}
				</h2>
				<fieldset
					className="flex flex-col gap-2 border-0 p-0"
					aria-label={labels.scopeTitle}
				>
					<button
						type="button"
						data-change="historical"
						aria-pressed={choice === "historical"}
						onClick={() => setChoice("historical")}
						className={`rounded-md border px-2.5 py-1.5 text-left text-xs transition-colors ${
							choice === "historical"
								? "border-blue-600 bg-accent"
								: "border-border hover:bg-accent"
						}`}
					>
						{labels.historicalLabel}
					</button>
					<button
						type="button"
						data-change="declared"
						aria-pressed={choice === "declared"}
						onClick={() => setChoice("declared")}
						className={`rounded-md border px-2.5 py-1.5 text-left text-xs transition-colors ${
							choice === "declared"
								? "border-blue-600 bg-accent"
								: "border-border hover:bg-accent"
						}`}
					>
						{labels.declaredLabel}
					</button>
					<button
						type="button"
						data-change="newOnly"
						aria-pressed={choice === "newOnly"}
						onClick={() => setChoice("newOnly")}
						className={`rounded-md border px-2.5 py-1.5 text-left text-xs transition-colors ${
							choice === "newOnly"
								? "border-blue-600 bg-accent"
								: "border-border hover:bg-accent"
						}`}
					>
						{labels.newOnlyLabel}
					</button>
				</fieldset>

				{/* The §44.3 chips. */}
				<article className="rounded-lg border border-border bg-card p-4">
					<p className="text-xs text-muted-foreground">
						{labels.appliesToLabel}:
					</p>
					<ul className="mt-1 flex flex-wrap gap-1.5">
						{change.applies_to.map((a) => (
							<li
								key={a}
								className="rounded bg-accent px-1.5 py-0.5 text-xs text-accent-foreground"
							>
								{a}
							</li>
						))}
					</ul>
					{change.scope ? (
						<dl className="mt-3 space-y-1 text-xs text-muted-foreground">
							<div>
								{labels.strategyLabel}:{" "}
								<code className="font-mono text-foreground">
									{change.scope.migration.strategy}
								</code>
							</div>
							<div>
								{labels.preserveLabel}:{" "}
								<code className="font-mono text-foreground">
									{String(change.scope.audit.preserve_old_truth)}
								</code>
							</div>
						</dl>
					) : null}
				</article>

				{/* The verdict badge. */}
				<article className="rounded-lg border border-border bg-card p-4">
					<h3 className="text-sm font-semibold text-foreground">
						{labels.verdictTitle}
					</h3>
					<p
						data-verdict
						data-kind={verdictKind}
						className={`mt-2 rounded-md px-3 py-2 text-sm font-medium ${
							verdictKind === "requires"
								? "bg-red-500/15 text-red-600"
								: verdictKind === "allowed"
									? "bg-emerald-500/15 text-emerald-600"
									: "bg-muted text-muted-foreground"
						}`}
					>
						{verdictKind === "requires"
							? labels.requiresBadge
							: verdictKind === "allowed"
								? labels.allowedBadge
								: labels.noMigrationBadge}
					</p>
					{verdict.block ? (
						<div className="mt-2">
							<code data-block-code className="font-mono text-xs text-red-600">
								{verdict.block.code}
							</code>
							<ul className="mt-1 list-disc space-y-0.5 pl-4 text-xs text-muted-foreground">
								{verdict.block.how_to_fix.map((f) => (
									<li key={f}>{f}</li>
								))}
							</ul>
						</div>
					) : null}
				</article>
			</section>
		</div>
	);
}
