// callgraphindex_property_test.go — FN05 reproducibility mirror (determinism-first, CLAUDE.md
// §6/§8). The call-graph index is a PURE, TOTAL function of the emitted source: no DB, no clock,
// no rng, no LLM — an AST walk, never an "LLM that reads the code". These rapid properties pin:
//
//   - reproducibility: same code ⇒ same index (the done criterion — "même code → même graphe");
//   - totality: never panics on arbitrary bytes (unparseable / unmarked ⇒ empty index, never a
//     crash);
//   - scope gate: an unmarked source (not an AIDOS projection) yields the empty index (ADR 0036 §3);
//   - canonical order: nodes and edges come back sorted, so the index hashes byte-identically;
//   - router-consumability: AffectedSubgraph is a pure closure over the index — same (index,
//     changed set) ⇒ same affected node set, the dependents/dependencies of the changed symbols,
//     so the ContextRouter can target the affected sub-graph (the second done criterion).
package agentloop

import (
	"reflect"
	"testing"

	"pgregory.net/rapid"
)

// genIndexSource draws the same family genEmittedSource uses (clean / global / init / recursive /
// unmarked / broken / garbage) so the index is exercised on the full surface the FN04 rule sees.
func genIndexSource(t *rapid.T) (string, []byte) {
	bodies := []string{
		"// CODE GENERATED BY AIDOS\npackage g\nfunc h() {}\n",
		"// CODE GENERATED BY AIDOS\npackage g\nfunc a() { b() }\nfunc b() { c() }\nfunc c() {}\n",
		"// CODE GENERATED BY AIDOS\npackage g\nfunc a() { b() }\nfunc b() { a() }\n",
		"// CODE GENERATED BY AIDOS\npackage g\nvar x = 1\nfunc h() { other() }\nfunc other() {}\n",
		"package db\nfunc Emit() { helper() }\nfunc helper() {}\n", // unmarked: out of scope
		"// CODE GENERATED BY AIDOS\npackage g\nfunc broken( {\n",
		string(rapid.SliceOfN(rapid.Byte(), 0, 40).Draw(t, "garbage")),
	}
	name := rapid.SampledFrom([]string{"a.go", "b.go", "c.go"}).Draw(t, "name")
	body := rapid.SampledFrom(bodies).Draw(t, "body")
	return name, []byte(body)
}

func TestCallGraphIndex_Reproducible(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genIndexSource(rt)
		a := CallGraphIndex(name, src)
		b := CallGraphIndex(name, src)
		if !reflect.DeepEqual(a, b) {
			rt.Fatalf("index not reproducible:\n a=%+v\n b=%+v", a, b)
		}
		// And the content hash is byte-identical (same code → same graph, addressable).
		if a.Hash != b.Hash {
			rt.Fatalf("index hash not reproducible: %q vs %q", a.Hash, b.Hash)
		}
	})
}

func TestCallGraphIndex_Total(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genIndexSource(rt)
		_ = CallGraphIndex(name, src) // must not panic on any bytes
	})
}

// Canonical order: nodes sorted, and each node's callees sorted — so two equal inputs hash equal
// and a panel/router reads a stable order (no map-iteration leak).
func TestCallGraphIndex_CanonicalOrder(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genIndexSource(rt)
		idx := CallGraphIndex(name, src)
		for i := 1; i < len(idx.Nodes); i++ {
			if idx.Nodes[i-1].Name > idx.Nodes[i].Name {
				rt.Fatalf("nodes not sorted: %q before %q", idx.Nodes[i-1].Name, idx.Nodes[i].Name)
			}
		}
		for _, n := range idx.Nodes {
			for i := 1; i < len(n.Calls); i++ {
				if n.Calls[i-1] > n.Calls[i] {
					rt.Fatalf("calls of %q not sorted", n.Name)
				}
			}
		}
	})
}

// Scope gate: an unmarked source (not an AIDOS-emitted projection) yields the empty index
// regardless of content — only emitted projections are indexed (ADR 0036 §3, like the FN04 rule).
func TestCallGraphIndex_UnmarkedOutOfScope(t *testing.T) {
	src := []byte("package db\nfunc Emit() { helper() }\nfunc helper() {}\n")
	idx := CallGraphIndex("logic.go", src)
	if len(idx.Nodes) != 0 {
		t.Fatalf("unmarked source is out of scope, got %d nodes", len(idx.Nodes))
	}
}

// Router-consumability (the second done criterion): the index is a fonction-graphe the
// ContextRouter can consume to target the AFFECTED sub-graph of a change. AffectedSubgraph must be
// a pure closure over the index: same (index, changed) ⇒ same affected set.
func TestAffectedSubgraph_Reproducible(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genIndexSource(rt)
		idx := CallGraphIndex(name, src)
		// draw a subset of the node names as the "changed" set
		var names []string
		for _, n := range idx.Nodes {
			names = append(names, n.Name)
		}
		changed := []string{}
		for _, nm := range names {
			if rapid.Bool().Draw(rt, "pick:"+nm) {
				changed = append(changed, nm)
			}
		}
		a := AffectedSubgraph(idx, changed)
		b := AffectedSubgraph(idx, changed)
		if !reflect.DeepEqual(a, b) {
			rt.Fatalf("affected subgraph not reproducible:\n a=%v\n b=%v", a, b)
		}
		// every changed node that exists in the index appears in its own affected set (reflexive)
		for _, c := range changed {
			if idx.has(c) && !contains(a, c) {
				rt.Fatalf("changed node %q missing from its own affected set %v", c, a)
			}
		}
		// the affected set is sorted (stable for the router)
		for i := 1; i < len(a); i++ {
			if a[i-1] > a[i] {
				rt.Fatalf("affected set not sorted: %v", a)
			}
		}
	})
}

func contains(xs []string, x string) bool {
	for _, v := range xs {
		if v == x {
			return true
		}
	}
	return false
}
