// callgraphindex.go — FN05: the deterministic CALL-GRAPH INDEX of an AIDOS-emitted file (the
// Understand-Anything view, Lum1104/Understand-Anything) supplied to the agent as CONTEXT, and the
// AffectedSubgraph selector the ContextRouter (S33) consumes to target only the sub-graph a change
// touches. It completes the router: where S33 routes by red-set / bounded-context over the kernel
// ContextGraph, FN05 lets it ALSO target by the structural call-graph of the emitted app — "chaque
// fonction = une couche + un nœud de graphe" — so the agent loads the affected sub-graph, never the
// whole emitted tree.
//
// WHY (ADR 0036, the functional mandate). FN04 already proves the emitted call-graph is ACYCLIC
// (EMITTED_CALL_GRAPH_ACYCLIC); FN05 turns that same intra-file graph into a first-class, content-
// addressed INDEX so the router has a precise map of "who calls whom" in the emitted projection.
// Because the graph is guaranteed acyclic upstream, the dependents-closure AffectedSubgraph
// computes always terminates.
//
// DETERMINISM-FIRST (CLAUDE.md §6/§8). The index is a PURE, TOTAL function of (filename, source):
// an AST walk over the parsed Go, never an "LLM that reads the code". Same code ⇒ same graph ⇒ same
// content hash (the done criterion). Nodes are sorted, each node's callees sorted — no map-iteration
// leak, byte-identical encoding. AffectedSubgraph is likewise a pure closure over the index: same
// (index, changed set) ⇒ same affected node set. The reproducibility mirror is
// callgraphindex_property_test.go; the worked examples, callgraphindex_fixture_test.go.
//
// SCOPE + FAIL-CLOSED (ADR 0036 §3). Only EMITTED projections (the "CODE GENERATED BY AIDOS" marker)
// are indexed — the engine's own logic and sqlc output are out of scope, exactly as the FN04 rule.
// Unparseable or unmarked source yields the EMPTY index (no nodes): the index never fabricates a
// graph it cannot derive (the honesty rule — never invent a node/target).
//
// THE WALL (CLAUDE.md §2). This package WRITES NO TRUTH. The index is below-the-line telemetry /
// context the router reads; it never edits the kernel.
package agentloop

import (
	"encoding/json"
	"go/ast"
	"go/parser"
	"go/token"
	"sort"

	"github.com/steph-frtech/aidos/back/kernel/records"
)

// CallNode is one node of the emitted call-graph index: a top-level function defined in the file
// and the names (sorted) of the same-file functions it calls. "Une couche + un nœud d'un graphe."
type CallNode struct {
	Name  string   `json:"name"`
	Calls []string `json:"calls"`
}

// CallGraph is the content-addressed call-graph index of ONE emitted file — the Understand-Anything
// view handed to the agent and consumed by the ContextRouter. Pure function of the source.
type CallGraph struct {
	// Package is the emitted file's package name ("" when out of scope / unparseable).
	Package string `json:"package"`
	// Nodes are the call nodes in canonical (sorted-by-name) order.
	Nodes []CallNode `json:"nodes"`
	// Hash is the content address over the canonical encoding (same code ⇒ same hash).
	Hash string `json:"hash"`
}

// has reports whether name is a node of the index. Pure.
func (g CallGraph) has(name string) bool {
	for _, n := range g.Nodes {
		if n.Name == name {
			return true
		}
	}
	return false
}

// CallGraphIndex builds the deterministic call-graph index of an emitted Go file. Out-of-scope
// (unmarked) or unparseable source yields the empty index. Same (filename, src) ⇒ same index.
func CallGraphIndex(filename string, src []byte) CallGraph {
	if !IsEmittedProjection(src) {
		return CallGraph{Nodes: []CallNode{}} // out of scope (ADR 0036 §3)
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.SkipObjectResolution)
	if err != nil {
		return CallGraph{Nodes: []CallNode{}} // fail-closed: no graph from unparseable Go
	}

	// node set: top-level funcs defined here (the closed node set of this emitted layer) — exactly
	// the set firstCallCycleNode uses, so the index and the FN04 acyclicity rule see the same graph.
	defined := map[string]bool{}
	for _, decl := range file.Decls {
		if fd, ok := decl.(*ast.FuncDecl); ok && fd.Name != nil {
			defined[fd.Name.Name] = true
		}
	}

	// caller → set of same-file callees.
	calls := map[string]map[string]bool{}
	for _, decl := range file.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Name == nil {
			continue
		}
		caller := fd.Name.Name
		if _, seen := calls[caller]; !seen {
			calls[caller] = map[string]bool{}
		}
		if fd.Body == nil {
			continue
		}
		ast.Inspect(fd.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			if id, ok := call.Fun.(*ast.Ident); ok && defined[id.Name] {
				calls[caller][id.Name] = true
			}
			return true
		})
	}

	names := make([]string, 0, len(defined))
	for n := range defined {
		names = append(names, n)
	}
	sort.Strings(names)

	nodes := make([]CallNode, 0, len(names))
	for _, n := range names {
		callees := make([]string, 0, len(calls[n]))
		for c := range calls[n] {
			callees = append(callees, c)
		}
		sort.Strings(callees)
		nodes = append(nodes, CallNode{Name: n, Calls: callees})
	}

	g := CallGraph{Package: file.Name.Name, Nodes: nodes}
	g.Hash = hashCallGraph(g)
	return g
}

// hashCallGraph content-addresses the index over its canonical encoding, REUSING the S01/S02
// records.Canonicalize + records.Hash scheme so the index lands under the same address scheme as
// every other content-addressed artifact (the ContextPack hash, the entity source_hash). The Hash
// field is zeroed before hashing (a value never hashes itself). Same graph ⇒ identical hash.
func hashCallGraph(g CallGraph) string {
	g.Hash = ""
	raw, err := json.Marshal(g)
	if err != nil {
		return ""
	}
	canon, err := records.Canonicalize(raw)
	if err != nil {
		return ""
	}
	return records.Hash(canon)
}

// AffectedSubgraph is what the ContextRouter (S33) consumes to target the SUB-GRAPH a change
// touches: given the index and the set of changed symbols, it returns the changed symbols PLUS
// every node that (transitively) DEPENDS ON them — i.e. everyone who calls a changed function,
// directly or through a chain. A change to a callee ripples UP to its callers, so those are exactly
// the layers the agent must reload. Sorted, deduped, pure; unknown changed symbols are ignored (the
// router never invents a node — honesty rule). Terminates because the emitted graph is acyclic (FN04).
func AffectedSubgraph(g CallGraph, changed []string) []string {
	// reverse edges: callee → callers (dependents).
	dependents := map[string][]string{}
	for _, n := range g.Nodes {
		for _, callee := range n.Calls {
			dependents[callee] = append(dependents[callee], n.Name)
		}
	}

	seen := map[string]bool{}
	var stack []string
	for _, c := range changed {
		if g.has(c) && !seen[c] {
			seen[c] = true
			stack = append(stack, c)
		}
	}
	for len(stack) > 0 {
		cur := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		for _, caller := range dependents[cur] {
			if !seen[caller] {
				seen[caller] = true
				stack = append(stack, caller)
			}
		}
	}

	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}
