// callgraphindex_fixture_test.go — FN05 fixture mirror: concrete (emitted source) → (call-graph
// index) and (index, changed) → (affected sub-graph) cases, the worked examples the property
// mirror generalises. The index is the Understand-Anything view AIDOS hands the agent as context;
// AffectedSubgraph is what the ContextRouter (S33) consumes to target the affected sub-graph.
package agentloop

import (
	"reflect"
	"testing"
)

const fnChainSrc = `// CODE GENERATED BY AIDOS — DO NOT EDIT. source: deadbeef
package g

func a() { b(); c() }
func b() { c() }
func c() {}
`

func TestCallGraphIndex_ChainShape(t *testing.T) {
	idx := CallGraphIndex("chain.go", []byte(fnChainSrc))
	want := []CallNode{
		{Name: "a", Calls: []string{"b", "c"}},
		{Name: "b", Calls: []string{"c"}},
		{Name: "c", Calls: []string{}},
	}
	if !reflect.DeepEqual(idx.Nodes, want) {
		t.Fatalf("graph shape:\n got  %+v\n want %+v", idx.Nodes, want)
	}
	if idx.Package != "g" {
		t.Fatalf("package: got %q want g", idx.Package)
	}
	if idx.Hash == "" {
		t.Fatalf("index must be content-addressed (non-empty hash)")
	}
}

// AffectedSubgraph(changed={c}) must surface c AND everyone who (transitively) calls c — a, b —
// because a change to c ripples up to its dependents: that is the sub-graph the router must load.
func TestAffectedSubgraph_DependentsRippleUp(t *testing.T) {
	idx := CallGraphIndex("chain.go", []byte(fnChainSrc))
	got := AffectedSubgraph(idx, []string{"c"})
	want := []string{"a", "b", "c"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("affected by change to c: got %v want %v", got, want)
	}
}

// AffectedSubgraph(changed={a}) — a is a leaf-of-the-dependents direction (nothing calls a), so the
// affected set is just {a}: a change to a ripples to nobody upstream.
func TestAffectedSubgraph_TopOnlyAffectsItself(t *testing.T) {
	idx := CallGraphIndex("chain.go", []byte(fnChainSrc))
	got := AffectedSubgraph(idx, []string{"a"})
	want := []string{"a"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("affected by change to a: got %v want %v", got, want)
	}
}

// A changed symbol that is not a node in the index contributes nothing (the router never invents a
// target — honesty rule). Empty changed ⇒ empty affected.
func TestAffectedSubgraph_UnknownAndEmpty(t *testing.T) {
	idx := CallGraphIndex("chain.go", []byte(fnChainSrc))
	if got := AffectedSubgraph(idx, []string{"zzz"}); len(got) != 0 {
		t.Fatalf("unknown symbol affects nothing, got %v", got)
	}
	if got := AffectedSubgraph(idx, nil); len(got) != 0 {
		t.Fatalf("empty change affects nothing, got %v", got)
	}
}

// Fail-closed / out of scope: unparseable emitted Go and unmarked sources both yield the empty
// index (no nodes) — the index never fabricates a graph it cannot derive.
func TestCallGraphIndex_EmptyOnUnparseableOrUnmarked(t *testing.T) {
	broken := CallGraphIndex("b.go", []byte("// CODE GENERATED BY AIDOS\npackage g\nfunc broken( {\n"))
	if len(broken.Nodes) != 0 {
		t.Fatalf("unparseable yields empty index, got %d nodes", len(broken.Nodes))
	}
	unmarked := CallGraphIndex("u.go", []byte("package db\nfunc Emit() {}\n"))
	if len(unmarked.Nodes) != 0 {
		t.Fatalf("unmarked yields empty index, got %d nodes", len(unmarked.Nodes))
	}
}
