// emittedfitness_property_test.go — FN04 reproducibility/totality mirror (determinism-first,
// CLAUDE.md §6/§8). CheckEmittedFunctional is a PURE, TOTAL function of (filename, source):
// no DB, no clock, no rng, no LLM. These rapid properties pin:
//   - reproducibility: identical (name, src) ⇒ identical violations (twice) — never an LLM
//     "is this functional?" judgement, an AST walk;
//   - totality: never panics on arbitrary bytes (fail-closed to EMITTED_UNPARSEABLE);
//   - the three rule codes are the ONLY codes a violation can carry.
package agentloop

import (
	"testing"

	"pgregory.net/rapid"
)

// genEmittedSource draws small Go-ish sources around the AIDOS marker — some clean, some
// carrying a global / init / recursion — plus arbitrary garbage to exercise fail-closed.
func genEmittedSource(t *rapid.T) (string, []byte) {
	bodies := []string{
		"// CODE GENERATED BY AIDOS\npackage g\nfunc h() {}\n",
		"// CODE GENERATED BY AIDOS\npackage g\nvar x = 1\nfunc h() {}\n",
		"// CODE GENERATED BY AIDOS\npackage g\nfunc init() {}\nfunc h() {}\n",
		"// CODE GENERATED BY AIDOS\npackage g\nfunc a() { b() }\nfunc b() { a() }\n",
		"// CODE GENERATED BY AIDOS\npackage g\nvar _ = h\nfunc h() {}\n",
		"package db\nfunc Emit() {}\n", // unmarked: not an emitted projection
		"// CODE GENERATED BY AIDOS\npackage g\nfunc broken( {\n",
		string(rapid.SliceOfN(rapid.Byte(), 0, 40).Draw(t, "garbage")),
	}
	name := rapid.SampledFrom([]string{"a.go", "b.go", "c.go"}).Draw(t, "name")
	body := rapid.SampledFrom(bodies).Draw(t, "body")
	return name, []byte(body)
}

func TestCheckEmittedFunctional_Reproducible(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genEmittedSource(rt)
		a := CheckEmittedFunctional(name, src)
		b := CheckEmittedFunctional(name, src)
		if len(a) != len(b) {
			rt.Fatalf("not reproducible: %d vs %d", len(a), len(b))
		}
		for i := range a {
			if a[i].Package != b[i].Package || a[i].Import != b[i].Import || a[i].BlockReason.Code != b[i].BlockReason.Code {
				rt.Fatalf("violation %d differs: %+v vs %+v", i, a[i], b[i])
			}
		}
	})
}

func TestCheckEmittedFunctional_Total(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genEmittedSource(rt)
		_ = CheckEmittedFunctional(name, src) // must not panic
	})
}

// Soundness of the code surface: every violation carries one of the four declared codes,
// blocking severity, and a non-empty how_to_fix (never a prison).
func TestCheckEmittedFunctional_OnlyDeclaredCodes(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		name, src := genEmittedSource(rt)
		for _, v := range CheckEmittedFunctional(name, src) {
			switch v.BlockReason.Code {
			case CodeEmittedNoGlobalMutable, CodeEmittedFunctionPure, CodeEmittedCallGraphAcyclic, CodeEmittedUnparseable:
			default:
				rt.Fatalf("unexpected violation code %q", v.BlockReason.Code)
			}
			if v.BlockReason.Severity != "blocking" {
				rt.Fatalf("violation must be blocking, got %q", v.BlockReason.Severity)
			}
			if len(v.BlockReason.HowToFix) == 0 {
				rt.Fatalf("violation must carry how_to_fix (never a prison)")
			}
		}
	})
}

// Unmarked sources are out of scope (the marker is the deterministic scope gate): a file
// without the AIDOS marker yields zero violations regardless of content.
func TestCheckEmittedFunctional_UnmarkedOutOfScope(t *testing.T) {
	src := []byte("package db\nvar global = 1\nfunc init() {}\nfunc a() { a() }\n")
	if got := CheckEmittedFunctional("logic.go", src); len(got) != 0 {
		t.Fatalf("unmarked emitter logic is out of scope, got %d violations: %+v", len(got), got)
	}
}
