// emittedfitness.go — FN04: the deterministic, fail-closed ARCH-FITNESS rules that make
// the EMITTED-functional mandate (ADR 0036) an ENFORCED build-time invariant over the
// AIDOS-emitted projection tree (back/gen/). Three rules, one pure function:
//
//   - EMITTED_NO_GLOBAL_MUTABLE  — an emitted Go file may declare NO package-level mutable
//     `var` (the spike's typeBindings() table is RETURNED by value, never a module-level
//     accumulator). const/type are immutable and allowed; a blank-identifier compile
//     assertion (`var _ X = …`) carries no mutable state and is exempt.
//   - EMITTED_FUNCTION_PURE      — an emitted Go file may declare NO `init()`: a hidden
//     startup effect breaks "each emitted symbol is a pure value/type, same input → same
//     output structurally". (Re-emission byte-identity — the dynamic facet — is pinned by
//     FN03's purity property mirror; this rule pins the static facet over gen/.)
//   - EMITTED_CALL_GRAPH_ACYCLIC — the intra-file function call graph is ACYCLIC: no self-
//     or mutual recursion. Each function is "une couche + un nœud d'un graphe acyclique"
//     (Understand-Anything); FN05's call-graph index relies on this guarantee.
//
// WHY RULES, NOT PROSE (ADR 0036 §4). The functional mandate, asserted only as prose,
// could quietly rot: a later emitter could leak a `var typeMap`, an init(), or a recursive
// helper into gen/ and every per-step "determinism-first ✓" would still pass. These rules
// turn the mandate into a build-time guard — the exact spirit of CheckLLMIsolation (BA14).
//
// DETERMINISM-FIRST + FAIL-CLOSED (CLAUDE.md §6/§8, ADR 0036 §4). Each check is a PURE Go
// function over a parsed AST — the deterministic family go-arch-lint/depguard belong to —
// never an "LLM that judges if this is functional". Same (filename, source) ⇒ same
// violations. Fail-closed: emitted Go that does not even parse cannot be certified
// functional, so it is itself a violation (EMITTED_UNPARSEABLE), never silently green.
//
// SCOPE (ADR 0036 §3): gen/ ONLY, and within gen/ only the EMITTED OUTPUTS — Go files
// carrying the "CODE GENERATED BY AIDOS" marker. The emitter LOGIC that happens to live
// under gen/ (e.g. gen/db's EmitMigration, unmarked) and sqlc-generated code are OUT of
// scope: the mandate binds the projections AIDOS emits, never the engine that emits them.
// IsEmittedProjection is that deterministic scope gate.
//
// THE WALL (CLAUDE.md §2). This package WRITES NO TRUTH. The mandate (the three invariants
// + the gen/ scope) is the above-the-line intent (ADR 0036) projected to a below-the-line
// deterministic check; the rules report, they never edit the kernel. Widening the scope or
// softening an invariant is a truth change (idée → miroir → /goal), never a silent edit.
package agentloop

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// The four FN04 arch-fitness violation codes (ADR 0036 §2 + the fail-closed case). Declared
// here with their rule (arch-fitness codes live with their rule, like
// CodeLLMSDKImportOutsideProvider).
const (
	// CodeEmittedNoGlobalMutable — an emitted Go file declares a package-level mutable var.
	CodeEmittedNoGlobalMutable blockreason.Code = "EMITTED_NO_GLOBAL_MUTABLE"
	// CodeEmittedFunctionPure — an emitted Go file declares an init() (hidden startup effect).
	CodeEmittedFunctionPure blockreason.Code = "EMITTED_FUNCTION_PURE"
	// CodeEmittedCallGraphAcyclic — the emitted intra-file call graph contains a cycle.
	CodeEmittedCallGraphAcyclic blockreason.Code = "EMITTED_CALL_GRAPH_ACYCLIC"
	// CodeEmittedUnparseable — emitted Go that does not parse (fail-closed).
	CodeEmittedUnparseable blockreason.Code = "EMITTED_UNPARSEABLE"
)

// aidosEmittedMarker is the deterministic scope gate: only Go files whose source carries
// this marker (the AIDOS emitters write it as the first line, S35/S36) are EMITTED
// projections the functional mandate binds. Unmarked logic and sqlc output are out of scope.
const aidosEmittedMarker = "CODE GENERATED BY AIDOS"

// IsEmittedProjection reports whether src is an AIDOS-emitted projection — the deterministic
// scope discriminator for the FN04 rules (ADR 0036 §3). Pure.
func IsEmittedProjection(src []byte) bool {
	return bytes.Contains(src, []byte(aidosEmittedMarker))
}

// emittedBlockReason builds the canonical actionable refusal for an emitted-functional
// breach — code, blocking severity, French explanation, non-empty how_to_fix (never a
// prison, KRD §44.5). Pure constructor.
func emittedBlockReason(code blockreason.Code, pkg, symbol string) *blockreason.BlockReason {
	switch code {
	case CodeEmittedNoGlobalMutable:
		return &blockreason.BlockReason{
			Code:     code,
			Severity: blockreason.SeverityBlocking,
			Explanation: "Refus arch-fitness — mandat fonctionnel du code émis (ADR 0036) : la projection émise " +
				pkg + " déclare une variable mutable au scope paquet (`var " + symbol + "`). Le code émis doit être " +
				"PUR — aucune globale mutable : les tables sont construites et retournées par valeur, threadées " +
				"explicitement (le `typeBindings()` du spike FN01).",
			HowToFix: []string{
				"return_by_value : transformez la globale en fonction qui CONSTRUIT et RETOURNE la valeur (slice/map) à chaque appel, threadée explicitement — jamais un accumulateur de module.",
				"const_or_type : si la valeur est immuable, déclarez-la `const` (ou un type) — autorisé par le mandat.",
				"reform_emitter : la fuite vient de l'émetteur (back/runtime/generators) — reformez le rendu pour ne plus émettre de `var` de module (FN03).",
			},
		}
	case CodeEmittedFunctionPure:
		return &blockreason.BlockReason{
			Code:     code,
			Severity: blockreason.SeverityBlocking,
			Explanation: "Refus arch-fitness — mandat fonctionnel du code émis (ADR 0036) : la projection émise " +
				pkg + " déclare `init()` — un effet de démarrage caché. Chaque symbole émis doit être une valeur/type PUR " +
				"(même entrée → même sortie, structurellement) ; un `init()` introduit un état au démarrage hors des entrées.",
			HowToFix: []string{
				"remove_init : retirez `init()` ; faites construire l'état par une fonction pure appelée explicitement par l'appelant (functional core).",
				"reform_emitter : si l'émetteur produit un `init()`, reformez-le pour émettre une fonction pure à la place (FN03).",
			},
		}
	case CodeEmittedCallGraphAcyclic:
		return &blockreason.BlockReason{
			Code:     code,
			Severity: blockreason.SeverityBlocking,
			Explanation: "Refus arch-fitness — mandat fonctionnel du code émis (ADR 0036) : le graphe d'appel intra-fichier de la projection " +
				pkg + " contient un CYCLE (récursion directe ou mutuelle impliquant " + symbol + "). Chaque fonction émise doit être une couche + " +
				"un nœud d'un graphe ACYCLIQUE (intention Understand-Anything) — l'index call-graph de FN05 en dépend.",
			HowToFix: []string{
				"break_cycle : remplacez la récursion par une composition explicite (fold/map sur une structure immuable) — pas de récursion mutuelle cachée.",
				"reform_emitter : si l'émetteur génère des appels cycliques, reformez la composition (renderGo/renderDDL/renderTS foldés, FN03/ADR 0036 §2).",
			},
		}
	default: // CodeEmittedUnparseable
		return &blockreason.BlockReason{
			Code:     CodeEmittedUnparseable,
			Severity: blockreason.SeverityBlocking,
			Explanation: "Refus arch-fitness (fail-closed) — la projection émise " + pkg + " ne PARSE pas comme Go (" + symbol + "). " +
				"Un code émis qui ne compile même pas ne peut être certifié fonctionnel ; le doute est rouge (determinism-first, fail-closed).",
			HowToFix: []string{
				"fix_emitter : l'émetteur a produit du Go invalide — corrigez le rendu pour émettre du Go bien formé (FN03).",
				"reproduce : rejouez l'émission ; la sortie est déterministe (S34), donc le défaut est reproductible et localisable.",
			},
		}
	}
}

// CheckEmittedFunctional is the PURE, TOTAL FN04 rule over ONE emitted Go file. It returns
// every violation of the three EMITTED invariants (+ the fail-closed parse case), in a
// deterministic order (no-global-mutable decls in source order, then init, then call-graph
// cycle). If the source is NOT an AIDOS-emitted projection it is OUT of scope → no
// violation. Same (filename, src) ⇒ same violations: an AST walk, never an LLM judgement.
func CheckEmittedFunctional(filename string, src []byte) []Violation {
	if !IsEmittedProjection(src) {
		return nil // out of scope (ADR 0036 §3): only emitted projections are bound
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.SkipObjectResolution)
	if err != nil {
		// Fail-closed: unparseable emitted Go is a violation, never silently green.
		return []Violation{{
			Package:     filename,
			Import:      err.Error(),
			BlockReason: emittedBlockReason(CodeEmittedUnparseable, filename, "parse error"),
		}}
	}
	pkg := file.Name.Name
	var out []Violation

	// Rule 1 + 2 — walk top-level decls: package-level mutable var, and init().
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			if d.Tok != token.VAR {
				continue // const / type / import are immutable / not state
			}
			for _, spec := range d.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, name := range vs.Names {
					if name.Name == "_" {
						continue // blank-identifier compile assertion — no mutable state
					}
					out = append(out, Violation{
						Package:     pkg,
						Import:      name.Name,
						BlockReason: emittedBlockReason(CodeEmittedNoGlobalMutable, pkg, name.Name),
					})
				}
			}
		case *ast.FuncDecl:
			if d.Recv == nil && d.Name != nil && d.Name.Name == "init" {
				out = append(out, Violation{
					Package:     pkg,
					Import:      "init",
					BlockReason: emittedBlockReason(CodeEmittedFunctionPure, pkg, "init"),
				})
			}
		}
	}

	// Rule 3 — call-graph acyclicity over intra-file functions.
	if node := firstCallCycleNode(file); node != "" {
		out = append(out, Violation{
			Package:     pkg,
			Import:      node,
			BlockReason: emittedBlockReason(CodeEmittedCallGraphAcyclic, pkg, node),
		})
	}
	return out
}

// firstCallCycleNode builds the intra-file function call graph (caller → callees, restricted
// to functions DEFINED in the same file — the closed node set of this emitted layer) and
// returns the name of the first node (in sorted order) that participates in a cycle, or ""
// if the graph is acyclic. Pure and deterministic (sorted iteration; DFS three-colour).
func firstCallCycleNode(file *ast.File) string {
	// node set: top-level funcs defined here (methods keyed by name too — a cycle among
	// same-named symbols still indicates recursion in the emitted layer).
	defined := map[string]bool{}
	for _, decl := range file.Decls {
		if fd, ok := decl.(*ast.FuncDecl); ok && fd.Name != nil {
			defined[fd.Name.Name] = true
		}
	}
	graph := map[string][]string{}
	for _, decl := range file.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Name == nil || fd.Body == nil {
			continue
		}
		caller := fd.Name.Name
		callees := map[string]bool{}
		ast.Inspect(fd.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			if id, ok := call.Fun.(*ast.Ident); ok && defined[id.Name] {
				callees[id.Name] = true
			}
			return true
		})
		names := make([]string, 0, len(callees))
		for c := range callees {
			names = append(names, c)
		}
		sort.Strings(names)
		graph[caller] = append(graph[caller], names...)
	}

	const (
		white = 0
		gray  = 1
		black = 2
	)
	color := map[string]int{}
	nodes := make([]string, 0, len(graph))
	for n := range defined {
		nodes = append(nodes, n)
	}
	sort.Strings(nodes)

	var cycleNode string
	var visit func(n string) bool // returns true if a cycle is found
	visit = func(n string) bool {
		color[n] = gray
		for _, m := range graph[n] {
			switch color[m] {
			case gray:
				cycleNode = m
				return true
			case white:
				if visit(m) {
					return true
				}
			}
		}
		color[n] = black
		return false
	}
	for _, n := range nodes {
		if color[n] == white {
			if visit(n) {
				return cycleNode
			}
		}
	}
	return ""
}

// ScanEmittedTree is the authoritative DETERMINISTIC scan of the emitted projection tree —
// the depguard-equivalent over gen/. It walks dir, reads every .go file (excluding _test.go
// and vendor/testdata/hidden), runs CheckEmittedFunctional on each, and returns every
// violation across the whole tree in a STABLE order (files sorted by path, then per-file
// violation order). Same tree ⇒ same violations; the only I/O is reading the .go files.
func ScanEmittedTree(dir string) ([]Violation, error) {
	root, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	walkErr := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if path != root && (name == "vendor" || name == "testdata" || strings.HasPrefix(name, ".")) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		files = append(files, path)
		return nil
	})
	if walkErr != nil {
		return nil, walkErr
	}
	sort.Strings(files)

	var out []Violation
	for _, path := range files {
		src, rerr := os.ReadFile(path)
		if rerr != nil {
			return nil, rerr
		}
		// Use the path relative to root in the reported Package so the report is portable.
		rel, _ := filepath.Rel(root, path)
		for _, v := range CheckEmittedFunctional(filepath.ToSlash(rel), src) {
			out = append(out, v)
		}
	}
	return out, nil
}

// EmittedInvariantCodes returns the three EMITTED invariant codes declared by ADR 0036 §2,
// in canonical order. It is the single source the arch-fitness.json parity test compares
// against, so the declared invariant list and the config never drift (ADR 0036 §5).
func EmittedInvariantCodes() []blockreason.Code {
	return []blockreason.Code{
		CodeEmittedNoGlobalMutable,
		CodeEmittedFunctionPure,
		CodeEmittedCallGraphAcyclic,
	}
}
