// emittedfitness_fixture_test.go — FN04: the RED-FIRST fault-injection arch mirror for the
// EMITTED-functional mandate (ADR 0036). Three deterministic, fail-closed arch-fitness
// rules over the AIDOS-emitted projection tree (back/gen/, files carrying the
// "CODE GENERATED BY AIDOS" marker — the emitted outputs, NOT the emitter logic):
//
//   - EMITTED_NO_GLOBAL_MUTABLE  — an emitted Go file declares a package-level mutable
//     `var` (a `var _ = …` blank compile assertion is exempt; const/type are immutable).
//   - EMITTED_FUNCTION_PURE      — an emitted Go file declares an `init()` (a hidden
//     startup effect) — purity by construction means no implicit run-time state.
//   - EMITTED_CALL_GRAPH_ACYCLIC — the intra-file function call graph contains a cycle
//     (mutual or self recursion) — each function must be a layer + a node in an ACYCLIC
//     graph (the Understand-Anything intention; FN05's index relies on it).
//
// THE FAULT INJECTION (the FN04 done criterion). The mirror proves each rule is a RULE,
// not prose: the clean emitted source passes (no violation); injecting a package-level
// mutable global, an init(), or a call cycle into emitted source flips the matching rule
// red with an actionable BlockReason naming the offending package + symbol. Fail-closed:
// emitted Go that does not parse is itself a violation (never silently green).
package agentloop

import (
	"strings"
	"testing"
)

// cleanEmitted is the live shape of an AIDOS-emitted projection (cf. back/gen/api/order.go):
// one handler func, struct types, NO package-level var, NO init(), NO call cycle. It MUST
// pass all three rules.
const cleanEmitted = `// CODE GENERATED BY AIDOS — DO NOT EDIT. source: deadbeef
package apigen

type OrderRequest struct{ Id int64 }

func OrderHandler() {
	var req OrderRequest // function-local var — allowed
	_ = req
	helper()
}

func helper() {}
`

func TestEmittedNoGlobalMutable_Clean_NoViolation(t *testing.T) {
	got := CheckEmittedFunctional("clean.go", []byte(cleanEmitted))
	for _, v := range got {
		if v.BlockReason.Code == CodeEmittedNoGlobalMutable {
			t.Fatalf("clean emitted source must have NO EMITTED_NO_GLOBAL_MUTABLE violation, got %+v", v)
		}
	}
}

// FAULT INJECTION 1 — a package-level mutable `var` is injected into emitted source. The
// EMITTED_NO_GLOBAL_MUTABLE rule MUST go red.
func TestEmittedNoGlobalMutable_InjectedGlobal_FlipsRed(t *testing.T) {
	src := cleanEmitted + "\nvar leaked = map[string]int{}\n"
	got := CheckEmittedFunctional("inject.go", []byte(src))
	var v *Violation
	for i := range got {
		if got[i].BlockReason.Code == CodeEmittedNoGlobalMutable {
			v = &got[i]
		}
	}
	if v == nil {
		t.Fatalf("a package-level mutable global must flip EMITTED_NO_GLOBAL_MUTABLE red, got %+v", got)
	}
	if v.Import != "leaked" {
		t.Fatalf("violation must name the offending var, got %q", v.Import)
	}
	if v.BlockReason.Severity != "blocking" || len(v.BlockReason.HowToFix) == 0 {
		t.Fatalf("violation must carry a blocking, actionable BlockReason, got %+v", v.BlockReason)
	}
}

// A blank-identifier compile assertion (`var _ X = …`, sqlc/idiomatic) is NOT mutable
// state and MUST NOT be flagged — fail-closed but not a false-positive machine.
func TestEmittedNoGlobalMutable_BlankAssertion_Allowed(t *testing.T) {
	src := cleanEmitted + "\nvar _ = OrderHandler\n"
	for _, v := range CheckEmittedFunctional("blank.go", []byte(src)) {
		if v.BlockReason.Code == CodeEmittedNoGlobalMutable {
			t.Fatalf("a blank-identifier var _ assertion must NOT be flagged, got %+v", v)
		}
	}
}

// FAULT INJECTION 2 — an init() is injected. The EMITTED_FUNCTION_PURE rule MUST go red.
func TestEmittedFunctionPure_InjectedInit_FlipsRed(t *testing.T) {
	src := cleanEmitted + "\nfunc init() { helper() }\n"
	got := CheckEmittedFunctional("inject-init.go", []byte(src))
	var found bool
	for _, v := range got {
		if v.BlockReason.Code == CodeEmittedFunctionPure {
			found = true
			if v.Import != "init" {
				t.Fatalf("violation must name init, got %q", v.Import)
			}
		}
	}
	if !found {
		t.Fatalf("an init() must flip EMITTED_FUNCTION_PURE red, got %+v", got)
	}
}

func TestEmittedFunctionPure_Clean_NoViolation(t *testing.T) {
	for _, v := range CheckEmittedFunctional("clean.go", []byte(cleanEmitted)) {
		if v.BlockReason.Code == CodeEmittedFunctionPure {
			t.Fatalf("clean emitted source must have NO EMITTED_FUNCTION_PURE violation, got %+v", v)
		}
	}
}

// FAULT INJECTION 3 — a self-recursive call is injected. The EMITTED_CALL_GRAPH_ACYCLIC
// rule MUST go red.
func TestEmittedCallGraphAcyclic_SelfRecursion_FlipsRed(t *testing.T) {
	src := `// CODE GENERATED BY AIDOS — DO NOT EDIT.
package g

func loop() { loop() }
`
	got := CheckEmittedFunctional("self.go", []byte(src))
	var found bool
	for _, v := range got {
		if v.BlockReason.Code == CodeEmittedCallGraphAcyclic {
			found = true
		}
	}
	if !found {
		t.Fatalf("self-recursion must flip EMITTED_CALL_GRAPH_ACYCLIC red, got %+v", got)
	}
}

// FAULT INJECTION 3b — a mutual-recursion cycle (a→b→a) is injected. The rule MUST go red.
func TestEmittedCallGraphAcyclic_MutualRecursion_FlipsRed(t *testing.T) {
	src := `// CODE GENERATED BY AIDOS — DO NOT EDIT.
package g

func a() { b() }
func b() { a() }
`
	got := CheckEmittedFunctional("mutual.go", []byte(src))
	var found bool
	for _, v := range got {
		if v.BlockReason.Code == CodeEmittedCallGraphAcyclic {
			found = true
		}
	}
	if !found {
		t.Fatalf("mutual recursion must flip EMITTED_CALL_GRAPH_ACYCLIC red, got %+v", got)
	}
}

func TestEmittedCallGraphAcyclic_Clean_NoViolation(t *testing.T) {
	src := `// CODE GENERATED BY AIDOS — DO NOT EDIT.
package g

func a() { b(); c() }
func b() { c() }
func c() {}
`
	for _, v := range CheckEmittedFunctional("dag.go", []byte(src)) {
		if v.BlockReason.Code == CodeEmittedCallGraphAcyclic {
			t.Fatalf("an acyclic call graph (a→b→c, a→c) must NOT be flagged, got %+v", v)
		}
	}
}

// FAIL-CLOSED — emitted Go that does not parse cannot be certified functional; it is a
// violation, never silently green (CLAUDE.md §8 determinism-first, fail-closed).
func TestCheckEmittedFunctional_Unparseable_FailsClosed(t *testing.T) {
	src := `// CODE GENERATED BY AIDOS — DO NOT EDIT.
package g
func broken( {
`
	got := CheckEmittedFunctional("broken.go", []byte(src))
	if len(got) == 0 {
		t.Fatalf("unparseable emitted Go must fail closed (a violation), got none")
	}
	if got[0].BlockReason.Code != CodeEmittedUnparseable {
		t.Fatalf("unparseable must carry EMITTED_UNPARSEABLE, got %+v", got[0].BlockReason)
	}
}

// IsEmittedProjection is the deterministic scope discriminator: only Go carrying the
// AIDOS-generated marker is an EMITTED projection (the mandate's surface, ADR 0036 §3).
// The emitter LOGIC under gen/ (no marker) and sqlc output are out of this rule's scope.
func TestIsEmittedProjection(t *testing.T) {
	if !IsEmittedProjection([]byte(cleanEmitted)) {
		t.Fatal("an AIDOS-marked file must be recognised as an emitted projection")
	}
	if IsEmittedProjection([]byte("package db\nfunc Emit() {}\n")) {
		t.Fatal("unmarked emitter logic must NOT be treated as an emitted projection")
	}
	if IsEmittedProjection([]byte("// Code generated by sqlc. DO NOT EDIT.\npackage x\n")) {
		t.Fatal("sqlc output must NOT be treated as an AIDOS emitted projection")
	}
}

// The REAL tree guard: scanning the live back/gen/ tree yields NO violation across the
// three rules — the emitted projections on disk hold the functional mandate (the wall
// holds, not just in fixtures). A future emitter that leaks a global/init/cycle into an
// AIDOS-marked file flips this red at build time.
func TestScanEmittedTree_LiveGen_Holds(t *testing.T) {
	got, err := ScanEmittedTree("../../gen")
	if err != nil {
		t.Fatalf("ScanEmittedTree failed: %v", err)
	}
	if len(got) != 0 {
		var b strings.Builder
		for _, v := range got {
			b.WriteString("\n  ")
			b.WriteString(string(v.BlockReason.Code))
			b.WriteString(" ")
			b.WriteString(v.Package)
			b.WriteString(":")
			b.WriteString(v.Import)
		}
		t.Fatalf("the LIVE back/gen tree must hold the EMITTED functional mandate, got %d violations:%s", len(got), b.String())
	}
}
