package functional

// funcemit.go — FN01's pure-FUNCTIONAL re-emission of the checkout slice.
//
// FALSIFIABILITY (the spike's question): can an emitter produce the S46 slice's three
// projections (Go struct / Postgres DDL / TS interface) in a PURE-FUNCTIONAL style —
//
//   - every renderer a PURE function (same input → same output, no side effect),
//   - ZERO package-level mutable state (no `var typeMap = …`; the binding table is a
//     value RETURNED by a pure function and threaded explicitly),
//   - composition EXPLICIT (an acyclic call graph: each stage names the stages it calls),
//
// — WITHOUT losing the S34 determinism (byte-identical to the imperative emitter)?
//
// Contrast with the live imperative emitter (back/runtime/generators/emit.go):
//   - it holds `var typeMap = map[string]typeBinding{…}` at PACKAGE scope (a global);
//   - it accumulates output by MUTATING a strings.Builder (`b.WriteString(...)`).
// Here neither exists: typeBindings() is a pure constructor; rendering is fold/concat
// over immutable slices. Nothing in this file is a method on shared mutable state.

import (
	"go/format"
	"sort"
	"strings"
)

// binding maps one canonical type token to its three projections. Plain value type.
type binding struct {
	ddl string // Postgres column type
	gos string // Go field type (what sqlc emits)
	ts  string // TypeScript field type
}

// typeBindings is a PURE constructor — it RETURNS the closed binding table by value.
// This is the functional substitute for the imperative emitter's `var typeMap`: no
// module-level mutable state, no shared aliasing. Calling it twice yields two equal,
// independent maps; the pipeline threads the result explicitly.
func typeBindings() map[string]binding {
	return map[string]binding{
		"text":        {ddl: "TEXT", gos: "string", ts: "string"},
		"numeric":     {ddl: "NUMERIC", gos: "pgtype.Numeric", ts: "string"},
		"int":         {ddl: "BIGINT", gos: "int64", ts: "number"},
		"bool":        {ddl: "BOOLEAN", gos: "bool", ts: "boolean"},
		"timestamptz": {ddl: "TIMESTAMPTZ", gos: "pgtype.Timestamptz", ts: "string"},
	}
}

// sortedFields returns a NEW slice of the entity's fields ordered by name. Pure: it
// copies into a fresh slice before sorting, so the input Entity is never mutated
// (the imperative emitter sorts a copy too — parity, but here it is the only stateful
// step and it is contained, returning a value).
func sortedFields(e Entity) []Field {
	out := append([]Field(nil), e.Fields...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// header is a pure function: (commentPrefix, hash) → the protected header line.
func header(commentPrefix string) string {
	return commentPrefix + " CODE GENERATED BY AIDOS — DO NOT EDIT. source: " + sourceHash + "\n"
}

// goName: first rune upper, rest verbatim (deterministic, pure).
func goName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// mapFields is the functional core: a PURE map over fields → rendered lines, with no
// accumulator mutation. It takes the per-field renderer as a parameter (higher-order
// function), the explicit-composition substitute for the imperative `for { b.Write }`.
func mapFields(fields []Field, render func(Field) string) []string {
	out := make([]string, len(fields))
	for i, f := range fields {
		out[i] = render(f) // render is pure; out[i] is a fresh value, no shared state
	}
	return out
}

// renderGo is a pure function of (entity, bindings). No Builder, no global: it folds
// the field lines with strings.Join, then runs the deterministic gofmt. Byte-output is
// engineered to equal the imperative emitter's renderGoSqlc for the Order slice.
func renderGo(e Entity, tb map[string]binding) string {
	fields := sortedFields(e)
	needsPgtype := false
	for _, f := range fields {
		if strings.HasPrefix(tb[f.Type].gos, "pgtype.") {
			needsPgtype = true
		}
	}
	lines := mapFields(fields, func(f Field) string {
		return "\t" + goName(f.Name) + " " + tb[f.Type].gos
	})
	imports := ""
	if needsPgtype {
		imports = "import (\n\t\"github.com/jackc/pgx/v5/pgtype\"\n)\n\n"
	}
	src := header("//") +
		"package " + strings.ToLower(e.Name) + "gen\n\n" +
		imports +
		"type " + goName(e.Name) + " struct {\n" +
		strings.Join(lines, "\n") + "\n" +
		"}\n"
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(formatted)
}

// renderDDL is a pure function: fold field lines with ",\n", wrap in CREATE TABLE.
func renderDDL(e Entity, tb map[string]binding) string {
	lines := mapFields(sortedFields(e), func(f Field) string {
		return "    " + quote(f.Name) + " " + tb[f.Type].ddl + " NOT NULL"
	})
	return header("--") +
		"CREATE TABLE " + quote(strings.ToLower(e.Name)) + " (\n" +
		strings.Join(lines, ",\n") + "\n" +
		");\n"
}

// renderTS is a pure function: fold field lines, wrap in an exported interface.
func renderTS(e Entity, tb map[string]binding) string {
	lines := mapFields(sortedFields(e), func(f Field) string {
		return "\t" + f.Name + ": " + tb[f.Type].ts + ";"
	})
	return header("//") +
		"export interface " + goName(e.Name) + " {\n" +
		strings.Join(lines, "\n") + "\n" +
		"}\n"
}

// quote wraps an identifier in double quotes (pure).
func quote(s string) string { return "\"" + s + "\"" }

// Projection is the immutable result of the functional pipeline: the three rendered
// artifacts for one entity, keyed by target. Returned by value.
type Projection struct {
	Go  string
	DDL string
	TS  string
}

// EmitFunctional is the spike's top-level PURE pipeline — explicit composition over
// the three renderers, threading the binding table (no global). Same Entity → same
// Projection, no side effect. This is the FN01 "emitter in functional pure style".
//
// The call graph is ACYCLIC and explicit:
//
//	EmitFunctional → typeBindings
//	              → renderGo  → sortedFields, mapFields, header, goName
//	              → renderDDL → sortedFields, mapFields, header, quote
//	              → renderTS  → sortedFields, mapFields, header, goName
func EmitFunctional(e Entity) Projection {
	tb := typeBindings()
	return Projection{
		Go:  renderGo(e, tb),
		DDL: renderDDL(e, tb),
		TS:  renderTS(e, tb),
	}
}
