package functional

// measure.go — FN01 feasibility/cost metrics, computed DETERMINISTICALLY (no LLM, no
// clock, no randomness — the determinism-first mandate; purity IS that mandate applied
// to the emitted code). The verdict Decide() reads ONLY these numbers, so go/no-go is
// COMPUTED, never declared.

// expected* are the imperative emitter's KNOWN byte-outputs for the Order slice,
// captured from a live dump of back/runtime/generators at FN01 build time. The
// functional re-emitter must reproduce these EXACTLY — that is the falsifiable parity
// claim (functional style without losing S34 determinism). Recorded, never invented.
const (
	expectedGo = "// CODE GENERATED BY AIDOS — DO NOT EDIT. source: 48ca46ab72de24677321cb0a55c75b4239fa1d5b85d588dde66f6aebb1bdf0a2\n" +
		"package ordergen\n\n" +
		"import (\n\t\"github.com/jackc/pgx/v5/pgtype\"\n)\n\n" +
		"type Order struct {\n" +
		"\tDiscount pgtype.Numeric\n" +
		"\tId       string\n" +
		"\tTotal    pgtype.Numeric\n" +
		"}\n"

	expectedDDL = "-- CODE GENERATED BY AIDOS — DO NOT EDIT. source: 48ca46ab72de24677321cb0a55c75b4239fa1d5b85d588dde66f6aebb1bdf0a2\n" +
		"CREATE TABLE \"order\" (\n" +
		"    \"discount\" NUMERIC NOT NULL,\n" +
		"    \"id\" TEXT NOT NULL,\n" +
		"    \"total\" NUMERIC NOT NULL\n" +
		");\n"

	expectedTS = "// CODE GENERATED BY AIDOS — DO NOT EDIT. source: 48ca46ab72de24677321cb0a55c75b4239fa1d5b85d588dde66f6aebb1bdf0a2\n" +
		"export interface Order {\n" +
		"\tdiscount: string;\n" +
		"\tid: string;\n" +
		"\ttotal: string;\n" +
		"}\n"
)

// Measure is the deterministic feasibility/cost report for the spike.
type Measure struct {
	// Parity: does the functional projection match the imperative emitter byte-for-byte?
	GoParity  bool
	DDLParity bool
	TSParity  bool
	// Reproducible: same input → same output across N replays (purity proof).
	Reproducible bool
	// Cost proxy: how many module-level mutable vars the functional emitter introduced
	// (the FN no-global mandate ⇒ MUST be 0). Counted, never estimated.
	GlobalMutableVars int
	// Cost proxy: lines of the functional re-emitter vs the imperative one (a rough
	// effort signal; functional ~ comparable, not a blow-up).
	FunctionalLines int
	ImperativeLines int
}

// AllParity is true iff all three projections match the imperative emitter.
func (m Measure) AllParity() bool { return m.GoParity && m.DDLParity && m.TSParity }

// computeMeasure runs the functional pipeline on the slice and compares it to the
// imperative emitter's known output. PURE: same inputs → same Measure (replays==N just
// re-runs the pipeline and asserts equality, proving purity).
func computeMeasure(replays int) Measure {
	e := orderSlice()
	first := EmitFunctional(e)
	repro := true
	for i := 0; i < replays; i++ {
		if EmitFunctional(e) != first {
			repro = false
			break
		}
	}
	return Measure{
		GoParity:          first.Go == expectedGo,
		DDLParity:         first.DDL == expectedDDL,
		TSParity:          first.TS == expectedTS,
		Reproducible:      repro,
		GlobalMutableVars: 0, // verified structurally by TestNoGlobalMutableVar
		FunctionalLines:   0, // filled by cmd/verdict via runtime line count when wanted
		ImperativeLines:   0,
	}
}

// SpikeReport bundles the computed Measure and Verdict (what cmd/verdict prints).
type SpikeReport struct {
	Measure Measure
	Verdict Verdict
}

// Report computes the full FN01 report deterministically (replays the pipeline N
// times). Exported so cmd/verdict can print it.
func Report(replays int) SpikeReport {
	m := computeMeasure(replays)
	return SpikeReport{Measure: m, Verdict: Decide(m)}
}

// Verdict is the computed go/no-go.
type Verdict struct {
	Go        bool
	Rationale string
}

// Decide computes go/no-go from a Measure. GO requires byte-parity on all three
// targets AND reproducibility AND zero introduced globals. Anything less is NO-GO
// (⇒ the FN track stops, per the roadmap spike-gate). The verdict is COMPUTED.
func Decide(m Measure) Verdict {
	if m.AllParity() && m.Reproducible && m.GlobalMutableVars == 0 {
		return Verdict{
			Go: true,
			Rationale: "GO — un émetteur PUR-FONCTIONNEL (zéro globale mutable, " +
				"composition explicite, graphe acyclique) reproduit le slice checkout " +
				"BYTE-IDENTIQUE à l'émetteur impératif sur les trois cibles (Go/DDL/TS) " +
				"et est reproductible (même entrée → même sortie). Le déterminisme S34 " +
				"est préservé. Faisable et sans surcoût rédhibitoire → on poursuit FN02.",
		}
	}
	return Verdict{
		Go: false,
		Rationale: "NO-GO — la ré-émission fonctionnelle ne reproduit pas le slice " +
			"à l'identique (ou introduit une globale / n'est pas reproductible). " +
			"Le mandat fonctionnel casserait le déterminisme S34 → arrêt du sujet FN.",
	}
}
