// emit.go — THROWAWAY (DP01 spike). The throwaway PURE emitter: StackManifest →
// docker-compose.yml honouring the /data/dockers conventions verbatim (container_name
// ${APP_NAME}-<svc>, env_file .env, no published ports, external traefik network, Traefik
// HTTPS router + HTTP→HTTPS redirect middleware for the server role, named bind volumes on
// env-var devices, restart unless-stopped, healthcheck). No clock, no RNG, no map iteration:
// services/volumes are rendered in a SORTED copy, lines folded with strings.Join, "\n" only.
// Determinism-first: the LLM never enters — this is the function the verdict measures.
package stackmanifest

import (
	"fmt"
	"sort"
	"strings"
)

// Emit renders the manifest as a docker-compose.yml — a pure function of its argument.
func Emit(m StackManifest) string {
	services := append([]Service(nil), m.Services...)
	sort.Slice(services, func(i, j int) bool { return services[i].Name < services[j].Name })
	volumes := append([]Volume(nil), m.Volumes...)
	sort.Slice(volumes, func(i, j int) bool { return volumes[i].Name < volumes[j].Name })

	var b []string
	b = append(b, "# generated by the DP01 throwaway emitter — source_hash: "+SourceHash(m))
	b = append(b, "services:")
	for _, s := range services {
		b = append(b, renderService(s)...)
	}
	b = append(b, "", "networks:")
	b = append(b, "  "+m.Network.Name+":")
	if m.Network.External {
		b = append(b, "    external: true")
	}
	b = append(b, "    name: ${TRAEFIK_NETWORK_NAME}")
	if len(volumes) > 0 {
		b = append(b, "", "volumes:")
		for _, v := range volumes {
			b = append(b,
				"  "+v.Name+":",
				"    name: ${APP_NAME}-"+v.Name,
				"    driver: local",
				"    driver_opts:",
				"      type: none",
				"      device: ${"+v.DeviceVar+"}",
				"      o: bind",
			)
		}
	}
	return strings.Join(b, "\n") + "\n"
}

// renderService renders one service block. Reverse-proxied services publish NO ports —
// they join the external traefik network and are exposed by labels only.
func renderService(s Service) []string {
	port := fmt.Sprintf("%d", s.InternalPort)
	out := []string{
		"  " + s.Name + ":",
		"    image: " + s.Image,
		"    container_name: ${APP_NAME}-" + s.Name,
		"    # role: " + s.Role,
		"    env_file:",
		"      - .env",
		"    profiles:",
		"      - " + s.Profile,
		"    networks:",
		"      - traefik_default",
		"    restart: unless-stopped",
		"    healthcheck:",
		`      test: ["CMD-SHELL", "exit 0"]`,
		"      interval: 30s",
		"      timeout: 3s",
		"      retries: 3",
	}
	if s.Role == "server" {
		out = append(out,
			"    labels:",
			`      - "traefik.enable=true"`,
			"      # HTTPS router",
			`      - "traefik.http.routers.${APP_NAME}.rule=Host(`+"`"+`${APP_SUBDOMAIN}.${DOMAIN}`+"`"+`)"`,
			`      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"`,
			`      - "traefik.http.routers.${APP_NAME}.tls=true"`,
			`      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${CERT_RESOLVER_NAME}"`,
			`      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=`+port+`"`,
			"      # HTTP -> HTTPS redirect",
			`      - "traefik.http.routers.${APP_NAME}-http.rule=Host(`+"`"+`${APP_SUBDOMAIN}.${DOMAIN}`+"`"+`)"`,
			`      - "traefik.http.routers.${APP_NAME}-http.entrypoints=web"`,
			`      - "traefik.http.routers.${APP_NAME}-http.middlewares=${APP_NAME}-https-redirect"`,
			`      - "traefik.http.middlewares.${APP_NAME}-https-redirect.redirectscheme.scheme=https"`,
		)
	} else {
		// internal-only service: still labelled with its internal port for the round-trip
		// (a comment, not a published port — internal URLs are env-var business, EPIC B).
		out = append(out, "    # internal_port: "+port)
	}
	return out
}
