package webcomponent_test

// Fixture mirror (N2) — emitting a control-spec produces a protected, source-hashed
// Next component.
//
//	mirrors schema · reflects: runtime.generators.webcomponent.Emit · test_kind: fixture
//	· cert_language: operation-dsl/go · authority: below · liveness: live
//
// Materialized source: tests/runtime/web_projection.fixture.md (the human-readable
// fixture, conceptually in the `mirrors` schema, persisted at S06 — bootstrap exception).
// state  (control): the S11 checkout-button control AST + its bound checkout-submit
//
//	action AST (read VERBATIM from S11 — the agent authors no new control/action truth).
//
// command: Emit(control, action, "ts-next")
// events:  [ Emitted ] → 1 artifact, target ts-next, path under web-preview/_generated/
//   - artifact.source_hash == Hash(Canonicalize(control.body ⊕ action.body))  (S02/S11 reused)
//   - artifact.bytes start with "CODE GENERATED BY AIDOS — DO NOT EDIT. source: <hash>"
//   - Emit(…) == Emit(…) byte-for-byte (the S34 determinism contract)
//   - a field the control AST does NOT pin is never invented (honesty)

import (
	"strings"
	"testing"

	"github.com/steph-frtech/aidos/back/kernel/action"
	"github.com/steph-frtech/aidos/back/kernel/control"
	"github.com/steph-frtech/aidos/back/kernel/records"
	"github.com/steph-frtech/aidos/back/runtime/generators/webcomponent"
)

func TestEmitProducesProtectedSourceHashedComponent(t *testing.T) {
	c := control.CheckoutButton()
	a := action.CheckoutSubmit()

	art, br := webcomponent.Emit(c, a, webcomponent.TargetTSNext)
	if br != nil {
		t.Fatalf("Emit: unexpected BlockReason %+v", br)
	}

	// One ts-next artifact for kind=control under web-preview/_generated/.
	if art.Target != webcomponent.TargetTSNext {
		t.Fatalf("target = %q, want ts-next", art.Target)
	}
	if art.Kind != webcomponent.KindControl {
		t.Fatalf("kind = %q, want control", art.Kind)
	}
	wantPath := "front/web/app/web-preview/_generated/checkout-button.tsx"
	if art.Path != wantPath {
		t.Fatalf("path = %q, want %q", art.Path, wantPath)
	}
	if !art.Protected {
		t.Fatalf("artifact must be protected")
	}

	// source_hash == Hash(Canonicalize(control.body ⊕ action.body)) — S02/S11 reused.
	wantHash, brh := webcomponent.SourceHash(c, a)
	if brh != nil {
		t.Fatalf("SourceHash: unexpected BlockReason %+v", brh)
	}
	if art.SourceHash != wantHash {
		t.Fatalf("source_hash = %q, want %q", art.SourceHash, wantHash)
	}

	// bytes start with the protected header carrying the source hash.
	header := "// " + webcomponent.ProtectedMarker + ". source: " + art.SourceHash
	if !strings.HasPrefix(string(art.Bytes), header) {
		t.Fatalf("bytes must start with the protected header %q; got %q", header, firstLine(art.Bytes))
	}

	// output_hash == Hash(bytes).
	if art.OutputHash != records.Hash(art.Bytes) {
		t.Fatalf("output_hash mismatch")
	}

	// The bound operation ref is taken VERBATIM from the action (never invented): the
	// component declares the action's invoke.
	if !strings.Contains(string(art.Bytes), "const INVOKE = "+quote(a.Invoke)+";") {
		t.Fatalf("emitted component must declare INVOKE = %q (Plan(action,click).invoke)", a.Invoke)
	}
	// The label is taken verbatim from the control (an i18n key, never translated here).
	if !strings.Contains(string(art.Bytes), "const LABEL = "+quote(c.Label)+";") {
		t.Fatalf("emitted component must declare LABEL = %q", c.Label)
	}
}

func TestEmitIsDeterministicByteForByte(t *testing.T) {
	c := control.CheckoutButton()
	a := action.CheckoutSubmit()

	a1, br1 := webcomponent.Emit(c, a, webcomponent.TargetTSNext)
	a2, br2 := webcomponent.Emit(c, a, webcomponent.TargetTSNext)
	if br1 != nil || br2 != nil {
		t.Fatalf("Emit: unexpected BlockReason %+v / %+v", br1, br2)
	}
	if string(a1.Bytes) != string(a2.Bytes) {
		t.Fatalf("Emit is not byte-identical across runs (determinism contract violated)")
	}
	if a1.OutputHash != a2.OutputHash {
		t.Fatalf("output_hash differs across runs: %q != %q", a1.OutputHash, a2.OutputHash)
	}
	// Normalized newlines: no CRLF leaks into the projection.
	if strings.Contains(string(a1.Bytes), "\r") {
		t.Fatalf("emitted bytes contain a carriage return (non-normalized newlines)")
	}
}

func TestEmitBlocksOnOrphanBind(t *testing.T) {
	c := control.CheckoutButton()
	a := action.CheckoutSubmit()
	a.Name = "some-other-action" // the control.triggers no longer resolves to this action

	_, br := webcomponent.Emit(c, a, webcomponent.TargetTSNext)
	if br == nil {
		t.Fatalf("Emit must BLOCK an orphan bind (control.triggers != action.Name), got no BlockReason")
	}
	if len(br.HowToFix) == 0 {
		t.Fatalf("BlockReason must carry a non-empty how_to_fix (no prison)")
	}
}

func TestEmitBlocksUnknownTarget(t *testing.T) {
	c := control.CheckoutButton()
	a := action.CheckoutSubmit()
	_, br := webcomponent.Emit(c, a, webcomponent.Target("mobile"))
	if br == nil {
		t.Fatalf("Emit must BLOCK an unknown target, got no BlockReason")
	}
}

func TestEmitBlocksMalformedControl(t *testing.T) {
	c := control.CheckoutButton()
	c.View = "" // a malformed/empty AST: no view pinned
	a := action.CheckoutSubmit()
	_, br := webcomponent.Emit(c, a, webcomponent.TargetTSNext)
	if br == nil {
		t.Fatalf("Emit must BLOCK a malformed control (no view), got no BlockReason")
	}
}

func firstLine(b []byte) string {
	s := string(b)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

func quote(s string) string { return "\"" + s + "\"" }
