// Package webcomponent is the AIDOS Runtime WEB PROJECTION emitter — the `ts-next`
// target for kind=control inside the S34 emitter set (NOT a fork of it). It READS a
// control-spec (S11, the button-as-a-kernel-source: {view, label, visible_when,
// enabled_when, triggers}) plus the action-spec it binds (S11: {on:click, invoke,
// on_success, on_error}) — both prior Kernel truth, SELECT-only (the wall, CLAUDE.md
// §2) — and EMITS a real Next.js (App Router) client component whose rendered
// visible/enabled are a FAITHFUL MIRROR of EvalState(control, given) (S11) and whose
// click DECLARES the action's invoke == Plan(action, click).invoke (S11).
//
// ONE SOURCE → N PROJECTIONS, NEVER DOUBLE-TYPED (CONTEXT-MAP, KRD LIVRE V). The button
// you click in a browser is a PROJECTION of the control-spec, never hand-authored UI
// behaviour. The component does NOT re-implement business rules: it embeds the
// control's two Expr ASTs (visible_when/enabled_when) as canonical JSON and evaluates
// them with the shared TS twin of the FROZEN expr catalogue (>, length, &&, !) — the
// same semantics as back/kernel/expr, never re-invented. The click sets a testable
// signal (data-aidos-invoke = the bound operation ref); it does NOT execute the
// operation (the operation runtime is a later tooth — the projection only DECLARES the
// bind).
//
// THE CONTRACT IS DETERMINISM (CLAUDE.md §6 determinism-first, S34): Emit(control,
// action) is a PURE function of Canonicalize(control.body ⊕ action.body) — no clock,
// no RNG, no map-iteration-order leak, no absolute paths; stable key ordering,
// normalized "\n" newlines. So Emit(c,a) is byte-for-byte equal on every run/machine.
// The emitted Artifact carries source_hash = Hash(Canonicalize(control.body ⊕
// action.body)) — REUSING S02 (records.Hash/Canonicalize) and S11 (control.Canonicalize
// / action.Canonicalize), NOT forked — and the SAME protected header as S34
// ("CODE GENERATED BY AIDOS — DO NOT EDIT. source: <hash>"), so staleness is COMPUTED
// (an artifact whose source_hash no longer matches its control's head feeds S22's red
// wave, never hunted) and a hand-edit of _generated/ cannot survive a re-emit.
//
// HONESTY (CLAUDE.md §8): a control whose `triggers` ref does not resolve to the bound
// action, or an action whose `on` does not match the control, is a BlockReason (the S13
// shape) — never a panic, never an invented bind. A field the AST does not pin is never
// invented. This package authors NO new truth (the control/action specs are prior
// truth, S11, read-only); it only emits the ts-next projection below the wall.
package webcomponent

import (
	"github.com/steph-frtech/aidos/back/kernel/action"
	"github.com/steph-frtech/aidos/back/kernel/control"
	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// Target is the projection target of this emitter — the closed S34 target set extended
// additively with one value. Declared here as a typed constant so it is enumerable and
// never invented.
type Target string

// TargetTSNext — a Next.js (App Router) client component, the web projection of a
// control-spec. Lands under front/web/app/web-preview/_generated/. This is the ONLY
// target this step adds (no targets beyond ts-next; the kind × target matrix grows
// additively).
const TargetTSNext Target = "ts-next"

// Kind is the source kind this emitter reads. The web projection emits from a CONTROL
// (the button-as-a-kernel-source, S11) bound to an ACTION. Declared closed; new kinds
// are later teeth, never invented here.
type Kind string

// KindControl — the control-spec AST (S11), the only source kind the web emitter
// projects from.
const KindControl Kind = "control"

// ProtectedMarker is the EXACT header text every emitted file carries — the SAME marker
// as the S34 emitter set (generators.ProtectedMarker), reused verbatim so the gen-
// protection sensor and the drift computation are uniform across targets.
const ProtectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// Artifact is one emitted web projection. It mirrors the S34 generators.Artifact shape
// (path, target, kind, bytes, source_hash, output_hash, protected) so the web target
// records into the SAME runtime.generated_artifacts ledger (S34) with no new table.
type Artifact struct {
	Path       string `json:"path"`        // front/web/app/web-preview/_generated/<control>.tsx
	Target     Target `json:"target"`      // always ts-next
	Kind       Kind   `json:"kind"`        // always control
	Bytes      []byte `json:"bytes"`       // the rendered .tsx (starts with the protected header)
	SourceHash string `json:"source_hash"` // Hash(Canonicalize(control.body ⊕ action.body)) — S02/S11 reused
	OutputHash string `json:"output_hash"` // Hash(bytes) — byte-identical re-emit proof
	Protected  bool   `json:"protected"`   // always true: gen/_generated/ is protected
}

// Emit is the pure web-projection emitter: it RENDERS the Next component for a control-
// spec bound to its action-spec. Emit(c,a) is a pure function of Canonicalize(c.body ⊕
// a.body) — no clock, no RNG, no map-order, no absolute paths — so it is byte-for-byte
// reproducible. It returns a BlockReason (S13 shape) for an unresolved trigger/bind or a
// malformed spec; never a panic, never an invented field.
//
// The control's `triggers` MUST resolve to the bound action's name, and the action's
// `on` event MUST be a click on this control — otherwise the bind is an orphan (a
// monster) and Emit blocks. This is the only place the two specs are checked to AGREE;
// it never invents the missing link.
func Emit(c control.Control, a action.Action, t Target) (Artifact, *blockreason.BlockReason) {
	if t != TargetTSNext {
		br := blockUnknownTarget(string(t))
		return Artifact{}, &br
	}
	if br := validateBind(c, a); br != nil {
		return Artifact{}, br
	}
	sourceHash, br := SourceHash(c, a)
	if br != nil {
		return Artifact{}, br
	}
	bytesOut, br := render(c, a, sourceHash)
	if br != nil {
		return Artifact{}, br
	}
	return Artifact{
		Path:       artifactPath(c),
		Target:     TargetTSNext,
		Kind:       KindControl,
		Bytes:      bytesOut,
		SourceHash: sourceHash,
		OutputHash: outputHash(bytesOut),
		Protected:  true,
	}, nil
}
