// Package appdata is the PURE, byte-stable per-project DATA emitter (the wall, §2/§6/§8).
//
// Intention (utilisatrice, 2026-06-14) : « aidospulumi up --project X déploie la VRAIE app de X avec
// les PROPRES entités de X — plus le seed Alpha Shop hardwiré ». Pulumi reste LE moteur (il monte les
// conteneurs) ; cet émetteur n'émet QUE les DONNÉES (schema.sql + entities.json) que Pulumi MONTE. La
// forme cible est prouvée en or par .deploy-pulumi/demoshop-dev/index.ts (montages
// /docker-entrypoint-initdb.d/01-schema.sql + /app/entities.json + env APP_NAME).
//
// DÉTERMINISME-FIRST. EmitProjectData(project, entities) est une FONCTION PURE, TOTALE, byte-stable de
// (project, Canonicalize(entities)) — mêmes entités → même schema/entities.json ; des entités
// différentes → des schémas différents. Aucune horloge, aucun RNG, ordre d'entité préservé tel que la
// source le pin (le projet OWNS son ordre de catalogue). Elle RÉUTILISE gen/db.EmitMigration (le même
// DDL Atlas que l'OS émet pour toute app) + generators — elle ne forke rien. Elle n'écrit AUCUNE
// vérité : une projection below-the-line. Importable par les deux gestes (aidosappemit + aidospulumi).
package appdata

import (
	"encoding/json"
	"fmt"

	gendb "github.com/steph-frtech/aidos/back/gen/db"
	"github.com/steph-frtech/aidos/back/runtime/generators"
)

// EntityOut is the per-entity metadata the generic admin server (aidos-app:latest) reads from
// entities.json to serve a CRUD UI per entity. It is a pure projection of the entity AST — name, the
// lowercase table name the gen/db emitter pins, and the pinned fields.
type EntityOut struct {
	Name   string             `json:"name"`
	Table  string             `json:"table"`
	Fields []generators.Field `json:"fields"`
}

// EmitProjectData is the PURE per-project data emitter: from a project name + its entity ASTs it
// renders (schema, entitiesJSON) — the EXACT two artifacts Pulumi mounts (01-schema.sql into the
// datastore initdb dir, entities.json into /app). It is byte-stable: same entities → identical bytes;
// different entities → different schemas. It reuses gen/db.EmitMigration (the canonical Atlas DDL
// emitter) per entity, never re-implementing the DDL. A malformed entity surfaces the emitter's
// BlockReason verbatim (the honesty rule), never a partial render.
//
// The project name is carried in the schema header so two projects' schemas differ even when they
// share an entity set — the schema is content-addressed to the PROJECT, not just the entities.
func EmitProjectData(project string, entities []generators.EntitySource) (schema []byte, entitiesJSON []byte, err error) {
	if project == "" {
		return nil, nil, fmt.Errorf("appdata: project is required (the per-project namespace)")
	}
	if len(entities) == 0 {
		return nil, nil, fmt.Errorf("appdata: no entities to emit for project %q", project)
	}

	header := fmt.Sprintf(
		"-- CODE GENERATED BY AIDOS — DO NOT EDIT. Emitted from project %q entities.\n\n", project)
	s := header
	meta := make([]EntityOut, 0, len(entities))

	for _, e := range entities {
		mig, br := gendb.EmitMigration(e, nil)
		if br != nil {
			return nil, nil, fmt.Errorf("emit %q blocked (%s): %s", e.Name, br.Code, br.Explanation)
		}
		s += string(mig.Bytes) + "\n\n"
		meta = append(meta, EntityOut{
			Name:   e.Name,
			Table:  TableName(e.Name),
			Fields: e.Fields,
		})
	}

	ej, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return nil, nil, fmt.Errorf("appdata: marshal entities.json: %w", err)
	}
	return []byte(s), ej, nil
}

// DecodeEntities decodes a JSON []EntitySource (the --entities file). It defaults a missing kind to
// KindEntity (a convenience for hand-authored project files), so a catalogue file may pin just
// {id, name, fields}; everything else is left untouched (validateSource in gen/db catches gaps).
func DecodeEntities(b []byte) ([]generators.EntitySource, error) {
	var ents []generators.EntitySource
	if err := json.Unmarshal(b, &ents); err != nil {
		return nil, err
	}
	for i := range ents {
		if ents[i].Kind == "" {
			ents[i].Kind = generators.KindEntity
		}
	}
	return ents, nil
}

// TableName mirrors the gen/db emitter's lowercase table name (ASCII A-Z → a-z).
func TableName(name string) string {
	out := make([]rune, 0, len(name))
	for _, r := range name {
		if r >= 'A' && r <= 'Z' {
			r = r + 32
		}
		out = append(out, r)
	}
	return string(out)
}
