// Package generators is the AIDOS Runtime emitter set — one deterministic emitter
// per `kind × target` that READS an entity AST (a prior Kernel truth, S02) and
// EMITS a projection: Go structs (via sqlc, the frozen Go-DB-access slot), Postgres
// DDL, or TypeScript types. One source → N projections, never double-typed
// (CONTEXT-MAP "Kernel → projections: constrains, never generates").
//
// THE CONTRACT IS DETERMINISM (CLAUDE.md §6 determinism-first, KRD LIVRE V):
//
//	Emit(source, target) is a PURE function of Canonicalize(source) —
//	no clock, no RNG, no map-iteration-order leak, no absolute paths;
//	stable key/field ordering, fixed import order, normalized "\n" newlines.
//
// So Emit(s,t) is byte-for-byte equal to Emit(s,t) on every run and every machine.
// The emitted Artifact carries its SOURCE CONTENT-HASH (reusing S02's
// records.Hash(records.Canonicalize(body)) — NOT forked) and a PROTECTED header
//
//	// CODE GENERATED BY AIDOS — DO NOT EDIT. source: <hash>
//
// so staleness is COMPUTED (an artifact whose source_hash no longer matches its
// entity's head feeds S22's red wave, never hunted) and a hand-edit of gen/ cannot
// survive a re-emit (CLAUDE.md §4/§9 — gen/ is never hand-edited).
//
// THE WALL (CLAUDE.md §2): an emitter only READS the entity AST (SELECT-only on
// `kernel`) and WRITES projections BELOW the line (gen/ for Go/DDL, front/web for
// TS). It writes no truth. A malformed/empty AST yields a BlockReason (the S13
// shape) — never a panic, never an invented field.
//
// OpenQuestion OQ-S34-entity-kind (provenance): S02 pins the seven KRDCore record
// kinds (idea/truth/mirror/layer/link/changeset/phase); there is no first-class
// `entity` record kind yet. The entity AST this step emits from is therefore
// modelled here as the JSON body the emitter CONSUMES (an EntitySource: a name +
// pinned fields), content-addressed via S02's Hash(Canonicalize(body)). When the
// entity DSL AST lands as a kernel kind, the EntitySource decoder binds to it; the
// emitter is unchanged. The emitter coins no new entity kind (the wall).
package generators

import (
	"errors"
	"fmt"
	"sort"

	"github.com/steph-frtech/aidos/back/kernel/records"
	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// Target is the projection target of an emitter. The set is CLOSED — declared here,
// never discovered — so the kind × target matrix is enumerable and no target is
// invented (the honesty rule). It grows ONLY additively (mobile/api are later teeth).
type Target string

const (
	// TargetGoSqlc — typed Go structs, emitted through sqlc (the frozen
	// Go-DB-access slot, CLAUDE.md §3, never substituted). Lands under back/gen/.
	TargetGoSqlc Target = "go-sqlc"
	// TargetPgDDL — Postgres DDL (CREATE TABLE), rendered from the same AST as the
	// Go target so the two can never drift. Lands under back/gen/.
	TargetPgDDL Target = "pg-ddl"
	// TargetTSTypes — TypeScript types, rendered from the same AST. Lands under
	// front/web/ (the Workbench / emitted-app TS, never double-typed against Go).
	TargetTSTypes Target = "ts-types"
)

// targetOrder is the canonical enumeration order. Declared, never derived from map
// iteration, so Targets() and Project's fan-out are stable.
var targetOrder = []Target{TargetGoSqlc, TargetPgDDL, TargetTSTypes}

// Targets returns every Target in the closed set, in canonical order.
func Targets() []Target {
	out := make([]Target, len(targetOrder))
	copy(out, targetOrder)
	return out
}

func isKnownTarget(t Target) bool {
	for _, kt := range targetOrder {
		if kt == t {
			return true
		}
	}
	return false
}

// Kind is the source kind an emitter reads. Currently only `entity` (the N3
// contract AST). Declared closed; new kinds are later teeth, never invented here.
type Kind string

// KindEntity — the entity AST (S02), the only source kind emitted from at S34.
const KindEntity Kind = "entity"

// Field is one pinned field of an entity AST. The emitter renders EXACTLY the
// pinned fields — it never invents a column/field the AST does not pin (honesty).
type Field struct {
	Name string `json:"name"`
	// Type is the canonical entity type token. The closed set is mapped per target
	// (text→string→TEXT, numeric→float64→NUMERIC, …); an unknown type is a
	// BlockReason, never a guessed mapping.
	Type string `json:"type"`
}

// EntitySource is the entity AST shape the emitter CONSUMES (OQ-S34-entity-kind).
// It is decoded from the kernel entity body; the emitter never authors it.
type EntitySource struct {
	ID     string  `json:"id"`
	Kind   Kind    `json:"kind"`
	Name   string  `json:"name"`
	Fields []Field `json:"fields"`
}

// Artifact is one emitted projection. It is content-addressed twice: by its SOURCE
// (source_hash = the entity AST it was emitted from) and by its OUTPUT (output_hash
// = the digest of the rendered bytes, proving byte-identical re-emission).
type Artifact struct {
	Path       string `json:"path"`        // where the projection lands (back/gen/… | front/web/…)
	Target     Target `json:"target"`      // which emitter produced it
	Kind       Kind   `json:"kind"`        // the source kind (currently entity)
	Bytes      []byte `json:"bytes"`       // the rendered text (starts with the protected header)
	SourceHash string `json:"source_hash"` // Hash(Canonicalize(entity.body)) — S02 reused
	OutputHash string `json:"output_hash"` // Hash(bytes) — byte-identical re-emit proof
	Protected  bool   `json:"protected"`   // always true: the header stamps gen/ as protected
}

// ProtectedMarker is the exact text every emitted file header carries. Hand-edited
// gen/ files are forbidden (CLAUDE.md §4/§9); this marker makes the prohibition
// visible and the drift computable.
const ProtectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// canonicalSourceHash returns the S02 content address of an entity source body.
// It REUSES records.Hash(records.Canonicalize(body)) — never forks it — so an
// artifact's source_hash equals the entity's kernel head hash and staleness is
// the simple inequality (the red-wave feed, S22).
func canonicalSourceHash(body []byte) (string, error) {
	canon, err := records.Canonicalize(body)
	if err != nil {
		return "", err
	}
	return records.Hash(canon), nil
}

// Validation errors. A malformed AST is a BlockReason at the boundary (Emit/
// Project); these sentinels are the internal causes.
var (
	ErrUnknownKind   = errors.New("generators: unknown source kind")
	ErrUnknownTarget = errors.New("generators: unknown target")
	ErrNoName        = errors.New("generators: entity AST pins no name")
	ErrNoFields      = errors.New("generators: entity AST pins no fields")
	ErrUnknownType   = errors.New("generators: entity field pins an unknown type")
)

// blockMalformed renders the canonical BlockReason for a malformed/empty AST. It
// reuses the S13 shape (blockreason.BlockReason) — never a new code beyond a human
// red — and always carries a non-empty how_to_fix (no prison). The cause is folded
// into the explanation so the panel and `aidos explain` name the missing pin.
func blockMalformed(cause error) blockreason.BlockReason {
	return blockreason.BlockReason{
		Code:     blockreason.CodeOutOfScope,
		Severity: blockreason.SeverityBlocking,
		Explanation: "Émission refusée : l'AST d'entité est malformé ou vide (" + cause.Error() +
			"). Un emitter REND exactement les champs épinglés par la source ; il n'invente jamais " +
			"un champ, une colonne ou un type (honnêteté). Une source sans nom ni champs n'est pas projetable.",
		HowToFix: []string{
			"pin_the_entity_ast : complétez l'AST d'entité dans le kernel (nom + champs typés) — l'emitter ne lit que ce que la source épingle.",
			"use_a_known_type : chaque champ porte un type du jeu fermé (text | numeric | int | bool | timestamptz) ; un type inconnu n'est jamais deviné.",
			"rerun aidos project : relancez l'émission une fois la source d'entité complète et bien typée.",
		},
	}
}

// validateSource checks the entity AST pins what every target needs: a name and at
// least one well-typed field. It invents nothing; an unpinned name/field/type is a
// cause, not a default.
func validateSource(s EntitySource) error {
	if s.Kind != KindEntity {
		return fmt.Errorf("%w: %q", ErrUnknownKind, s.Kind)
	}
	if s.Name == "" {
		return ErrNoName
	}
	if len(s.Fields) == 0 {
		return ErrNoFields
	}
	for _, f := range s.Fields {
		if f.Name == "" {
			return ErrNoFields
		}
		if !knownType(f.Type) {
			return fmt.Errorf("%w: %q", ErrUnknownType, f.Type)
		}
	}
	return nil
}

// sortedFields returns the entity's pinned fields in a STABLE order (by name).
// Determinism: the emitted output never depends on the order fields arrive in, so
// Project is order-independent and Emit is reproducible. It copies — never mutates
// the caller's slice.
func sortedFields(s EntitySource) []Field {
	out := make([]Field, len(s.Fields))
	copy(out, s.Fields)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}
