// Package frontemit is the AIDOS Runtime emitter for the EMITTED APP'S FRONT-END (S93):
// a deterministic, server-rendered Hono JSX/SSR front-end projected from the project's
// Kernel — the pages/navigation/forms over the user's entities (scalars + relations +
// blobs) and the control+action verticale rendered into REAL buttons, each button carrying
// its control-spec fixture as a SENSOR. It is the front counterpart of the S87 honoemit
// server (which emits the API) and the S90 apisurface (which emits the routes): where those
// emit the user app's BACKEND, frontemit emits the user app's UI, WIRED to the emitted API.
//
// OQ-0040-front — DECIDED (ROADMAP line 289). The emitted front is **Hono JSX/SSR** (the
// pages/forms render server-side as HTML via Hono's JSX runtime, the same Hono service that
// serves the API — one process, no separate SPA build), NOT a client SPA over `hc`. The
// type-sharing the roadmap prizes survives: the form posts to the emitted API route (S90),
// and the emitted model types (S74 relemit EmitTS) are the shared contract. Hono JSX/SSR is
// chosen over the `hc` client because (a) a server-rendered form is byte-stable and
// framework-agnostic (Playwright drives plain HTML), (b) it reuses the ALREADY-EMITTED Hono
// runtime (no second toolchain), (c) it needs no hydration/bundler step to be bootable. This
// is the forced decision the roadmap pinned "tranché ici"; recorded as ADR 0046-front.
//
// THE CONTRACT IS DETERMINISM (CLAUDE.md §6/§8, determinism-first):
//
//	EmitFront(spec) is a PURE, TOTAL function of its canonicalised input — no clock, no RNG,
//	no map-iteration-order leak, no absolute path; stable entity/control/field ordering,
//	fixed import order, "\n" newlines. So the same Kernel cut → byte-identical front bundle
//	on every run/machine (the S93 done-criterion: "même Kernel → bundle byte-identique").
//	The reproducibility mirror (frontemit_property_test.go, rapid) pins byte-stability AND
//	input-order invariance AND that every control's emitted button carries its fixture.
//
// THE WALL (CLAUDE.md §2). An emitter only READS Kernel sources (entities, relations, blob
// attributes, controls/actions) and WRITES projections BELOW the line (gen/<project>/web/…).
// It writes no truth. A malformed spec is a typed BlockReason (the S13 shape) — never a
// panic, never an invented form/field/route/button.
//
// THE CONTROL-SPEC FIXTURE AS A SENSOR (S11/S94, the done-criterion). Each emitted button
// embeds its control-spec fixture in a `data-aidos-control` JSON attribute: the control name,
// the bound operation (the action's `triggers`), and the expected {visible, enabled} from the
// control's fixture rows. A Playwright assertion reads that attribute to prove the rendered
// button obeys its control-spec — the button is the SENSOR of its own spec (no headless
// capability, ui-completeness CLAUDE.md §6 step 7).
package frontemit

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/steph-frtech/aidos/back/kernel/entities"
	"github.com/steph-frtech/aidos/back/kernel/entities/blob"
	"github.com/steph-frtech/aidos/back/kernel/entities/ref"
	"github.com/steph-frtech/aidos/back/kernel/records"
	"github.com/steph-frtech/aidos/back/runtime/blockreason"
)

// protectedMarker is the exact header text every emitted file carries — mirrors the S35/S87
// emitter marker so a hand-edit of gen/ is forbidden and the drift is computable.
const protectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// The emit targets frontemit renders. The set is CLOSED — one Kernel cut → exactly these
// front projections at S93 — so the matrix stays enumerable and no target is invented.
const (
	// TargetIndex — the emitted app's navigation index page (Hono JSX/SSR): a link to every
	// entity's list/form. Lands under gen/<project>/web/index.tsx.
	TargetIndex = "front-index"
	// TargetEntityForm — one create-form page per entity (Hono JSX/SSR), rendering an input
	// per scalar attribute, an <input type=file> per blob attribute, a <select> per relation,
	// posting to the emitted API. Lands under gen/<project>/web/<entity>.form.tsx.
	TargetEntityForm = "front-entity-form"
	// TargetControls — the control+action verticale rendered to REAL buttons, each embedding
	// its control-spec fixture as a sensor. Lands under gen/<project>/web/controls.tsx.
	TargetControls = "front-controls"
)

// targetOrder is the canonical enumeration order (declared, never from map iteration).
var targetOrder = []string{TargetIndex, TargetEntityForm, TargetControls}

// Targets returns every frontemit target in canonical order.
func Targets() []string {
	out := make([]string, len(targetOrder))
	copy(out, targetOrder)
	return out
}

// EntityModel is one entity the front-end renders a form/list over: its scalar Attributes
// (S35), its blob Attributes (S72) and its Relations (S71). The emitter never authors a
// field; it reads the Kernel cut. The three planes are disjoint (a scalar is never a blob).
type EntityModel struct {
	Entity entities.Entity
	Blobs  []blob.BlobAttribute
	Refs   []ref.Relation
}

// ControlModel is one control-spec rendered to a button, with the FIXTURE rows that pin its
// {visible, enabled} state. The button binds to the action's operation (the `triggers`/invoke
// link, S11). Conditions are carried as their canonical text (the projection embeds them as a
// sensor; the SOURCE remains the kernel control AST, read-only — the wall).
type ControlModel struct {
	// Name is the control identifier (e.g. "create-order-button").
	Name string
	// View is the screen the button lives on.
	View string
	// Label is the i18n key for the button text (ADR 0011 — bilingue).
	Label string
	// Operation is the operation the bound action invokes — the verticale's bottom (S11).
	Operation string
	// Fixtures are the control-spec fixture rows: each a given-name → expected {visible,enabled}
	// pair, so the emitted button can be asserted against its own spec.
	Fixtures []FixtureRow
}

// FixtureRow is one control-spec fixture row: a named situation and the expected button state.
type FixtureRow struct {
	Given   string
	Visible bool
	Enabled bool
}

// FrontSpec is the front emitter's input: the project namespace + the project's entities and
// controls. The emitter wires every entity (a form) and every control (a button); it never
// invents or omits an entity, a field or a control.
type FrontSpec struct {
	Project  string
	Entities []EntityModel
	Controls []ControlModel
}

// Validation sentinels. A malformed spec is a BlockReason at the boundary; these are the
// internal causes folded into the explanation (the S13 shape, never a new code).
var (
	ErrNoProject      = errors.New("frontemit: spec pins no project")
	ErrNoContent      = errors.New("frontemit: spec pins no entities and no controls")
	ErrEntityNoName   = errors.New("frontemit: entity pins no name")
	ErrControlNoName  = errors.New("frontemit: control pins no name")
	ErrControlNoOp    = errors.New("frontemit: control button binds no operation (orphan trigger)")
	ErrControlNoView  = errors.New("frontemit: control pins no view")
	ErrRelationNoName = errors.New("frontemit: relation pins no name")
)

// block renders the canonical S13 BlockReason for a malformed spec. It carries a non-empty
// how_to_fix (no prison) and folds the cause into the explanation so the panel and `aidos
// explain` name the missing pin.
func block(cause error) blockreason.BlockReason {
	return blockreason.BlockReason{
		Code:     blockreason.CodeOutOfScope,
		Severity: blockreason.SeverityBlocking,
		Explanation: "Émission du front refusée : la source (entités/contrôles du Kernel) est malformée ou vide (" +
			cause.Error() + "). Un emitter REND exactement ce que la source épingle ; il n'invente jamais un formulaire, " +
			"un champ, une route ni un bouton (honnêteté). Un bouton sans opération liée est un trigger orphelin, refusé.",
		HowToFix: []string{
			"pin_the_source : complétez la source dans le Kernel (entités nommées avec attributs / contrôles avec opération liée).",
			"bind_the_button : chaque contrôle lie une opération via son action (triggers) ; un bouton sans opération n'est jamais deviné.",
			"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
		},
	}
}

// validate checks the spec is projectable: a project namespace, ≥ 1 entity OR ≥ 1 control,
// every entity pins a name, every relation pins a name, every control pins a name + view +
// a bound operation (no orphan button). It invents nothing.
func validate(s FrontSpec) error {
	if s.Project == "" {
		return ErrNoProject
	}
	if len(s.Entities) == 0 && len(s.Controls) == 0 {
		return ErrNoContent
	}
	for _, e := range s.Entities {
		if e.Entity.Name == "" {
			return ErrEntityNoName
		}
		for _, r := range e.Refs {
			if r.Name == "" {
				return ErrRelationNoName
			}
		}
	}
	for _, c := range s.Controls {
		if c.Name == "" {
			return ErrControlNoName
		}
		if c.View == "" {
			return ErrControlNoView
		}
		if c.Operation == "" {
			return ErrControlNoOp
		}
	}
	return nil
}

// canonicalEntities returns the spec entities in canonical name order (so input order never
// leaks into the bytes). The scalar attributes / blobs / relations keep their declared
// source order WITHIN an entity (the entity AST owns that order).
func canonicalEntities(s FrontSpec) []EntityModel {
	out := append([]EntityModel(nil), s.Entities...)
	sort.SliceStable(out, func(i, j int) bool { return out[i].Entity.Name < out[j].Entity.Name })
	return out
}

// canonicalControls returns the spec controls in canonical name order.
func canonicalControls(s FrontSpec) []ControlModel {
	out := append([]ControlModel(nil), s.Controls...)
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// sourceBody re-serialises the spec into a canonical, key-sorted JSON body so the SourceHash
// is a content address: same spec (modulo input order) → same hash. It walks the CANONICAL
// entity/control order so input order never leaks (S02 Canonicalize reused, never forked).
func sourceBody(s FrontSpec) ([]byte, error) {
	type fieldView struct {
		Name     string `json:"name"`
		Type     string `json:"type"`
		Kind     string `json:"kind"`
		Required bool   `json:"required"`
		Target   string `json:"target,omitempty"`
		Card     string `json:"card,omitempty"`
	}
	type entityView struct {
		Name   string      `json:"name"`
		Fields []fieldView `json:"fields"`
	}
	type fixtureView struct {
		Given   string `json:"given"`
		Visible bool   `json:"visible"`
		Enabled bool   `json:"enabled"`
	}
	type controlView struct {
		Name     string        `json:"name"`
		View     string        `json:"view"`
		Label    string        `json:"label"`
		Op       string        `json:"op"`
		Fixtures []fixtureView `json:"fixtures"`
	}

	ents := make([]entityView, 0, len(s.Entities))
	for _, e := range canonicalEntities(s) {
		fields := make([]fieldView, 0)
		for _, a := range e.Entity.Attributes {
			fields = append(fields, fieldView{Name: a.Name, Type: string(a.Type), Kind: "scalar", Required: a.Required})
		}
		for _, bl := range e.Blobs {
			fields = append(fields, fieldView{Name: bl.Name, Kind: "blob", Required: bl.Required})
		}
		for _, r := range e.Refs {
			fields = append(fields, fieldView{Name: r.Name, Kind: "relation", Required: r.Required, Target: r.Target, Card: string(r.Cardinality)})
		}
		ents = append(ents, entityView{Name: e.Entity.Name, Fields: fields})
	}

	ctrls := make([]controlView, 0, len(s.Controls))
	for _, c := range canonicalControls(s) {
		fxs := make([]fixtureView, 0, len(c.Fixtures))
		for _, f := range c.Fixtures {
			fxs = append(fxs, fixtureView{Given: f.Given, Visible: f.Visible, Enabled: f.Enabled})
		}
		ctrls = append(ctrls, controlView{Name: c.Name, View: c.View, Label: c.Label, Op: c.Operation, Fixtures: fxs})
	}

	body := map[string]any{"project": s.Project, "entities": ents, "controls": ctrls}
	return records.Canonicalize(mustJSON(body))
}

// SourceHash is the content address of a front spec (the SourceHash every artifact carries).
// Any byte change (a new entity, a field, a control, a fixture) yields a new hash.
func SourceHash(s FrontSpec) (string, error) {
	body, err := sourceBody(s)
	if err != nil {
		return "", err
	}
	return records.Hash(body), nil
}

// EmitFront renders the WHOLE front bundle: the index page, one form page per entity, and the
// controls page. Returns the artifacts in canonical TARGET order then canonical entity order.
// A malformed spec is a single BlockReason (never a partial bundle).
func EmitFront(s FrontSpec) ([]Artifact, *blockreason.BlockReason) {
	if err := validate(s); err != nil {
		br := block(err)
		return nil, &br
	}
	sourceHash, err := SourceHash(s)
	if err != nil {
		br := block(err)
		return nil, &br
	}

	out := make([]Artifact, 0, len(s.Entities)+2)
	out = append(out, emitIndex(s, sourceHash))
	for _, e := range canonicalEntities(s) {
		out = append(out, emitEntityForm(s.Project, e, sourceHash))
	}
	out = append(out, emitControls(s, sourceHash))
	return out, nil
}

// EmitBundle renders the WHOLE front bundle as a SINGLE concatenated byte stream (the
// "bundle" the done-criterion addresses: "même Kernel → bundle byte-identique"). It joins
// every artifact's bytes in canonical order under a per-file banner, content-addressed by the
// digest of the joined bytes. This is the byte-identity proof surface.
func EmitBundle(s FrontSpec) (Artifact, *blockreason.BlockReason) {
	arts, br := EmitFront(s)
	if br != nil {
		return Artifact{}, br
	}
	sourceHash, _ := SourceHash(s)
	var b strings.Builder
	b.WriteString(header("//", sourceHash))
	b.WriteString("// S93 emitted app FRONT bundle (Hono JSX/SSR, ADR 0040 / OQ-0040-front DECIDED): index + per-entity forms + controls.\n")
	for _, a := range arts {
		fmt.Fprintf(&b, "\n// ===== %s =====\n", a.Path)
		b.Write(a.Bytes)
	}
	out := []byte(strings.TrimRight(b.String(), "\n") + "\n")
	return artifact("gen/"+s.Project+"/web/bundle.tsx", "front-bundle", out, sourceHash), nil
}

// mustJSON is defined in artifact.go.
