// Package relemit is the RELATION-AWARE, MULTI-ENTITY emitter (S74). Where the S35
// entity emitters (back/kernel/entities) project ONE entity to its three projections,
// relemit projects a WHOLE schema cut — a set of entities + their relations (S71 ref)
// + their async operations (S73 operation.Async) — into the emitted app's targets:
//
//   - EmitDDL  → Postgres DDL (ADR 0040: TargetPgDDL unchanged) with FOREIGN KEY columns
//     for 1-1/1-N relations, a JOIN TABLE for every N-N relation, and an OUTBOX
//     table when any operation is async. Every FK REFERENCES a real declared
//     table (the resolve gate, never a guess).
//   - EmitTS   → the emitted app's TypeScript model (ADR 0040: Hono/functional TS, the
//     primary target — sqlc/Go leaves the emitted tree, roadmap S74): one type
//     alias per entity, a TYPED ASSOCIATION field per relation, and a NAVIGATION
//     SDK (loadX helpers) so a caller walks the graph type-safely.
//   - EmitWorker → for each ASYNC operation node (S73), a TS WORKER that drains the outbox
//     and dispatches the operation's effects, plus (for a cron trigger) the
//     scheduled echeance. The worker is TS (roadmap S74 supersedes S73's Go).
//
// DETERMINISM-FIRST (CLAUDE.md §6/§8). Every Emit* is a PURE, TOTAL function of its input:
// no clock, no RNG, no I/O, no LLM. The same Schema → byte-identical output (the S74
// done-criterion). Entities and relations are rendered IN A CANONICAL ORDER (entities by
// name, relations by source order within an entity) so map iteration never leaks. The
// reproducibility mirror (relemit_property_test.go) pins byte-stability.
//
// THE WALL. The output is a PROJECTION (emitted code, regenerable); emitting writes no
// truth. It reuses the closed scalar→{DDL,TS} mapping of S35 (never forked) and the closed
// cardinality/semantic sets of S71 (never widened). A malformed schema (an unknown
// relation target, a missing identifier the FK needs) is a typed BlockReason, never a
// partial render — the same honesty as every emitter (no silent fallback).
package relemit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/steph-frtech/aidos/back/kernel/entities"
	"github.com/steph-frtech/aidos/back/kernel/entities/ref"
	"github.com/steph-frtech/aidos/back/kernel/operation"
	"github.com/steph-frtech/aidos/back/kernel/records"
)

// protectedMarker mirrors the entities emitter header marker (S35) — a generated file is
// never hand-edited. The same marker on every emitted target.
const protectedMarker = "CODE GENERATED BY AIDOS — DO NOT EDIT"

// The emit targets relemit renders. The set is CLOSED (one schema → exactly these
// projections at S74). They mirror the S35 token style.
const (
	// TargetDDL — the emitted app's Postgres schema (ADR 0040: dialect unchanged).
	TargetDDL = "rel-pg-ddl"
	// TargetTS — the emitted app's TypeScript model + navigation SDK (ADR 0040: primary).
	TargetTS = "rel-ts-model"
	// TargetWorker — the emitted app's async worker (S73 outbox drainer, TS at S74).
	TargetWorker = "rel-ts-worker"
)

// EntityRelations pairs an entity AST with the relations DECLARED ON it — the source-order
// list of typed references the entity owns. The relations point AT other entities in the
// same Schema (the resolve gate enforces membership).
type EntityRelations struct {
	Entity    entities.Entity
	Relations []ref.Relation
}

// AsyncOp pairs an async operation's NAME with its Async block (S73). relemit renders one
// worker + the outbox table off this. A schema with no AsyncOps emits no worker and no
// outbox table (the extension is purely additive).
type AsyncOp struct {
	Name  string
	Async operation.Async
}

// Schema is the MULTI-ENTITY cut relemit projects: an ordered set of entities-with-relations
// (a project's entity library, S70) plus the async operations (S73). project namespaces the
// paths (project-scoped, mirroring S72/S78). Schema is the single input of every Emit*.
type Schema struct {
	Project  string
	Entities []EntityRelations
	AsyncOps []AsyncOp
}

// Artifact wraps rendered bytes with their provenance, content-addressed by SOURCE (the
// schema hash) and by OUTPUT (the digest of the bytes — the byte-identical re-emit proof).
// Path is RELATIVE (no absolute path — determinism). It mirrors entities.Artifact so S78
// (project-scoped regeneration) treats relemit artifacts uniformly.
type Artifact struct {
	Path       string `json:"path"`
	Target     string `json:"target"`
	Bytes      []byte `json:"bytes"`
	SourceHash string `json:"source_hash"`
	OutputHash string `json:"output_hash"`
	Protected  bool   `json:"protected"`
}

// scalarDDL / scalarTS are the closed scalar→target mappings, REUSED from S35 via the
// public entities emitters (we re-derive through entities.Emit on a one-attr probe would
// be wasteful; instead we mirror the closed binding here against the public ScalarType
// set, and a property test pins they never drift from the S35 set).
var scalarDDL = map[entities.ScalarType]string{
	entities.TypeString:      "TEXT",
	entities.TypeInt:         "BIGINT",
	entities.TypeDecimal:     "NUMERIC",
	entities.TypeBool:        "BOOLEAN",
	entities.TypeTimestamptz: "TIMESTAMPTZ",
}

var scalarTS = map[entities.ScalarType]string{
	entities.TypeString:      "string",
	entities.TypeInt:         "number",
	entities.TypeDecimal:     "string",
	entities.TypeBool:        "boolean",
	entities.TypeTimestamptz: "string",
}

// ── Validation (typed, never silent) ────────────────────────────────────────────────

// Validate checks the WHOLE schema is projectable: a project namespace is pinned, every
// entity validates (S35 Validate), every relation resolves against the declared entity set
// (S71 Resolve — an UNKNOWN_RELATION_TARGET is refused, never guessed), every FK has a real
// target table with an identifier, and every async op's block is well-formed (S73
// ValidateAsync). It invents nothing. Returns nil for a projectable schema.
func Validate(s Schema) error {
	if s.Project == "" {
		return ErrNoProject
	}
	if len(s.Entities) == 0 {
		return ErrNoEntities
	}
	known := map[string]bool{}
	hasID := map[string]bool{}
	for _, er := range s.Entities {
		if err := entities.Validate(er.Entity); err != nil {
			return err
		}
		known[strings.ToLower(er.Entity.Name)] = true
		if _, ok := entities.Identifier(er.Entity); ok {
			hasID[strings.ToLower(er.Entity.Name)] = true
		}
	}
	for _, er := range s.Entities {
		for _, r := range er.Relations {
			// Resolve the target against the LOWERCASED declared set (table names are
			// lowercased in the DDL; the relation target must name a declared entity).
			if err := ref.Resolve(r, lowerKeys(known)); err != nil {
				return err
			}
			// An FK column (1-1 / 1-N) needs the target's PRIMARY KEY to reference. A
			// target with no identifier cannot be referenced — refused, never guessed.
			if r.Cardinality != ref.ManyToMany && !hasID[strings.ToLower(r.Target)] {
				return fmt.Errorf("%w: relation %q targets %q which has no identifier",
					ErrTargetNoIdentifier, r.Name, r.Target)
			}
			// An N-N join table references BOTH ends; both need a PRIMARY KEY.
			if r.Cardinality == ref.ManyToMany &&
				(!hasID[strings.ToLower(er.Entity.Name)] || !hasID[strings.ToLower(r.Target)]) {
				return fmt.Errorf("%w: N-N relation %q needs an identifier on both %q and %q",
					ErrTargetNoIdentifier, r.Name, er.Entity.Name, r.Target)
			}
		}
	}
	for _, ao := range s.AsyncOps {
		if ao.Name == "" {
			return ErrAsyncNoName
		}
		if err := operation.ValidateAsync(ao.Async); err != nil {
			return err
		}
	}
	return nil
}

// lowerKeys returns the lowercased membership set (ref.Resolve checks r.Target against it,
// and table/entity names are lowercased in the projections).
func lowerKeys(known map[string]bool) map[string]bool {
	out := make(map[string]bool, len(known))
	for k := range known {
		out[strings.ToLower(k)] = true
	}
	return out
}

// canonicalEntities returns the schema's entities sorted by entity name (the CANONICAL
// emission order, so map/source order never leaks into the bytes). Relations keep their
// source order within an entity (order is semantic, like attribute order in S35).
func canonicalEntities(s Schema) []EntityRelations {
	out := append([]EntityRelations(nil), s.Entities...)
	sort.SliceStable(out, func(i, j int) bool {
		return strings.ToLower(out[i].Entity.Name) < strings.ToLower(out[j].Entity.Name)
	})
	return out
}

// canonicalAsync returns the async ops sorted by name (canonical worker emission order).
func canonicalAsync(s Schema) []AsyncOp {
	out := append([]AsyncOp(nil), s.AsyncOps...)
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// SchemaBody re-serializes the schema into a canonical, key-sorted JSON body so the
// SourceHash is a content address: same schema (modulo input order) → same hash. It walks
// the CANONICAL order (entities by name, async by name) so input order never leaks.
func SchemaBody(s Schema) ([]byte, error) {
	type relView struct {
		Name        string `json:"name"`
		Target      string `json:"target"`
		Cardinality string `json:"cardinality"`
		Semantic    string `json:"semantic"`
		Required    bool   `json:"required"`
	}
	type entView struct {
		Entity    entities.Entity `json:"entity"`
		Relations []relView       `json:"relations"`
	}
	var ents []entView
	for _, er := range canonicalEntities(s) {
		rv := make([]relView, len(er.Relations))
		for i, r := range er.Relations {
			rv[i] = relView{r.Name, r.Target, string(r.Cardinality), string(r.Semantic), r.Required}
		}
		ents = append(ents, entView{er.Entity, rv})
	}
	var asyncs []map[string]any
	for _, ao := range canonicalAsync(s) {
		asyncs = append(asyncs, map[string]any{
			"name":  ao.Name,
			"async": ao.Async,
		})
	}
	body := map[string]any{
		"project":  s.Project,
		"entities": ents,
		"async":    asyncs,
	}
	raw, err := records.Canonicalize(mustJSON(body))
	if err != nil {
		return nil, err
	}
	return raw, nil
}

// SchemaHash is the content address of a schema (records.Hash of its canonical body) — the
// SourceHash every artifact carries. Any byte change (a new entity, a retargeted relation,
// an added async effect) yields a new hash, i.e. a new emitted version.
func SchemaHash(s Schema) (string, error) {
	body, err := SchemaBody(s)
	if err != nil {
		return "", err
	}
	return records.Hash(body), nil
}

// header renders the protected file header for a comment syntax + the schema source hash.
func header(commentPrefix, sourceHash string) string {
	return fmt.Sprintf("%s %s. source: %s\n", commentPrefix, protectedMarker, sourceHash)
}

// artifact wraps rendered bytes into an Artifact, content-addressing the output.
func artifact(path, target string, out []byte, sourceHash string) Artifact {
	return Artifact{
		Path:       path,
		Target:     target,
		Bytes:      out,
		SourceHash: sourceHash,
		OutputHash: records.Hash(out),
		Protected:  true,
	}
}
