/**
 * The API-projection twin — the Workbench /api-projection source (AIDOS step S36).
 *
 * The DECLARED projection of the Go package back/runtime/generators (api.go +
 * pactverify.go): the SAME deterministic API emitter — EmitAPI(operation, entity) → a
 * Go REST/JSON handler, EmitContract → the Pact-v3 contract, VerifyContract → the
 * provider-verification verdict. The API handler EXPOSES a kernel OPERATION (the N2
 * workflow, S10) over HTTP; its request/response reuse the ENTITY field shapes (the N3
 * source, S35) — never re-typed. /api-projection renders exactly what the Go emitter
 * computes — byte-identical (the source hash, the handler bytes, the contract).
 *
 * DETERMINISM-FIRST (CLAUDE.md §6/§8): pure functions over their input — no clock, no
 * rng, no I/O, no LLM — so the same (operation, entity) always yields byte-identical
 * output and the same content hash. The reproducibility mirror lib/api-projection.test.ts
 * (fast-check) pins determinism, the content-addressed source, the protected header, the
 * POST /orders route faithfulness, the no-add/drop/rename field set, and the PASS verdict.
 * The Go output is the AUTHORITATIVE truth; this twin reproduces it for the screen.
 *
 * READ-ONLY (the wall): /api-projection PROJECTS the emitted handler + the contract + the
 * verifier result; it never writes truth. The operation + entity are SOURCES above the
 * line (the agent reads them SELECT-only); back/gen/api is never hand-edited; truth-writes
 * (a contract row) go via propose → ChangeSet → approval, never a direct write from the
 * screen.
 */

import { createHash } from "node:crypto";

export const PROTECTED_MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

/** The closed entity scalar set (shared with S35). */
export type ScalarType = "string" | "int" | "decimal" | "bool" | "timestamptz";

export interface Attribute {
	name: string;
	type: ScalarType;
	required: boolean;
	identifier?: boolean;
}

export interface Entity {
	name: string;
	attributes: Attribute[];
}

/** A pinned operation step shape — the surface the source hash is taken over. */
export interface OpStep {
	kind: "validate" | "authorize" | "read" | "mutate" | "return";
	schema?: string;
	policy?: string;
	entity?: string;
	as?: string;
	op?: string;
	ref?: string;
	data_keys?: string[];
}

export interface Operation {
	name: string;
	input: string;
	emits: string[];
	steps: OpStep[];
}

export interface Artifact {
	path: string;
	target: "api";
	bytes: string;
	source_hash: string;
	output_hash: string;
	protected: true;
}

export interface PactContract {
	consumer: { name: string };
	provider: { name: string };
	interactions: {
		description: string;
		request: { method: string; path: string; body: Record<string, unknown> };
		response: { status: number; body: Record<string, unknown> };
	}[];
	metadata: { pactSpecification: { version: string } };
	source_hash: string;
}

export interface VerifyResult {
	pass: boolean;
	reason: string;
	interactions: string[];
}

const GO_TYPE: Record<ScalarType, string> = {
	string: "string",
	int: "int64",
	decimal: "pgtype.Numeric",
	bool: "bool",
	timestamptz: "pgtype.Timestamptz",
};

function sha256(s: string): string {
	return createHash("sha256").update(s).digest("hex");
}

function goName(s: string): string {
	return s ? s[0].toUpperCase() + s.slice(1) : s;
}

/** Minimal deterministic pluralizer — byte-identical to the Go pluralize. */
function pluralize(s: string): string {
	if (!s) return s;
	const vowel = (c: string) => "aeiou".includes(c);
	if (/[sxz]$/.test(s) || /(ch|sh)$/.test(s)) return `${s}es`;
	if (s.endsWith("y") && s.length > 1 && !vowel(s[s.length - 2]))
		return `${s.slice(0, -1)}ies`;
	return `${s}s`;
}

/** The HTTP method + route the operation pins (POST + the entity collection). */
export function methodRoute(entityName: string): {
	method: string;
	route: string;
} {
	return { method: "POST", route: `/${pluralize(entityName.toLowerCase())}` };
}

/** Canonical JSON: object keys sorted (recursively), arrays preserved (= Go Canonicalize). */
function canon(v: unknown): string {
	if (Array.isArray(v)) return `[${v.map(canon).join(",")}]`;
	if (v && typeof v === "object") {
		const keys = Object.keys(v as Record<string, unknown>).sort();
		return `{${keys
			.map(
				(k) =>
					`${JSON.stringify(k)}:${canon((v as Record<string, unknown>)[k])}`,
			)
			.join(",")}}`;
	}
	return JSON.stringify(v);
}

/** The canonical entity body (= Go entities.Body: omitempty false identifier). */
function entityBody(e: Entity): string {
	const attrs = e.attributes.map((a) => {
		const o: Record<string, unknown> = {
			name: a.name,
			type: a.type,
			required: a.required,
		};
		if (a.identifier) o.identifier = true;
		return o;
	});
	return canon({ attributes: attrs, name: e.name });
}

/**
 * The (operation ⊕ entity) source hash — byte-identical to Go's apiSourceHash. The
 * operation is rendered as its pinned step shapes; the combined body embeds the canonical
 * operation + entity bodies, then is canonicalized again (mirroring Go's json.RawMessage
 * embedding + final Canonicalize).
 */
export function sourceHash(op: Operation, e: Entity): string {
	const opShape = {
		name: op.name,
		input: op.input,
		emits: op.emits,
		steps: op.steps.map((s) => {
			const m: Record<string, unknown> = { kind: s.kind };
			if (s.kind === "validate") m.schema = s.schema;
			if (s.kind === "authorize") m.policy = s.policy;
			if (s.kind === "read") {
				m.entity = s.entity;
				m.as = s.as;
			}
			if (s.kind === "mutate") {
				m.entity = s.entity;
				m.op = s.op;
				m.as = s.as;
				m.data_keys = s.data_keys ?? [];
			}
			if (s.kind === "return") m.ref = s.ref;
			return m;
		}),
	};
	const opCanon = canon(opShape);
	const entCanon = entityBody(e);
	// Go embeds the two canonical bodies as RawMessage under {operation, entity} then
	// Canonicalizes; canon() sorts the two top keys (entity < operation) and re-emits the
	// already-canonical sub-bodies verbatim.
	const combined = `{${JSON.stringify("entity")}:${entCanon},${JSON.stringify("operation")}:${opCanon}}`;
	return sha256(combined);
}

function jsonTag(a: Attribute): string {
	return a.required ? a.name : `${a.name},omitempty`;
}

/**
 * EmitAPI — the Go REST/JSON handler bytes, byte-identical to the Go emitter (which runs
 * go/format.Source). gofmt aligns the struct field name/type/tag columns; mirror it.
 */
export function emitAPI(op: Operation, e: Entity): Artifact {
	const hash = sourceHash(op, e);
	const { method, route } = methodRoute(e.name);
	const typeName = goName(e.name);
	const needsPgtype = e.attributes.some((a) =>
		GO_TYPE[a.type].startsWith("pgtype."),
	);

	const names = e.attributes.map((a) => goName(a.name));
	const widestName = names.reduce((m, n) => Math.max(m, n.length), 0);
	const types = e.attributes.map((a) => GO_TYPE[a.type]);
	const widestType = types.reduce((m, t) => Math.max(m, t.length), 0);
	const structBody = (): string =>
		e.attributes
			.map((a) => {
				const n = goName(a.name);
				const t = GO_TYPE[a.type];
				const padN = " ".repeat(widestName - n.length + 1);
				const padT = " ".repeat(widestType - t.length + 1);
				return `\t${n}${padN}${t}${padT}\`json:${JSON.stringify(jsonTag(a))}\``;
			})
			.join("\n");

	// gofmt aligns the `key:` column of a composite literal: the key + ":" padded to
	// (widest key + 1). Mirror it for the input map and the response struct literals.
	const inputKeys = e.attributes.map((a) => `${JSON.stringify(a.name)}:`);
	const widestInputKey = inputKeys.reduce((m, k) => Math.max(m, k.length), 0);
	const inputLines = e.attributes
		.map((a) => {
			const k = `${JSON.stringify(a.name)}:`;
			const pad = " ".repeat(widestInputKey - k.length + 1);
			return `\t\t\t${k}${pad}req.${goName(a.name)},`;
		})
		.join("\n");
	const respKeys = e.attributes.map((a) => `${goName(a.name)}:`);
	const widestRespKey = respKeys.reduce((m, k) => Math.max(m, k.length), 0);
	const respLines = e.attributes
		.map((a) => {
			const k = `${goName(a.name)}:`;
			const pad = " ".repeat(widestRespKey - k.length + 1);
			return `\t\t\t${k}${pad}req.${goName(a.name)},`;
		})
		.join("\n");

	// gofmt sorts the FIRST import group alphabetically (stdlib + third-party together),
	// then a blank line, then the local operation import.
	const firstGroup = needsPgtype
		? ['"encoding/json"', '"github.com/jackc/pgx/v5/pgtype"', '"net/http"']
		: ['"encoding/json"', '"net/http"'];
	const imports = `${firstGroup
		.map((i) => `\t${i}`)
		.join("\n")}\n\n\t"github.com/steph-frtech/aidos/back/kernel/operation"`;

	const src =
		`// ${PROTECTED_MARKER}. source: ${hash}\n` +
		`// API projection (S36): ${method} ${route} — operation ${JSON.stringify(op.name)} over entity ${JSON.stringify(e.name)}.\n` +
		`package apigen\n\n` +
		`import (\n${imports}\n)\n\n` +
		`// ${typeName}Request is the JSON request body for ${method} ${route}. One field per\n` +
		`// ${typeName} attribute (S35 entity source), in source order — never re-typed.\n` +
		`type ${typeName}Request struct {\n${structBody()}\n}\n\n` +
		`// ${typeName}Response is the JSON response body — the created ${typeName} resource.\n` +
		`type ${typeName}Response struct {\n${structBody()}\n}\n\n` +
		`// ${typeName}Handler is the generated transport adapter for ${method} ${route}.\n` +
		`// It decodes the JSON request, delegates the body to the S10 operation\n` +
		`// interpreter (operation.Interpret of ${JSON.stringify(op.name)}), and encodes the result as JSON.\n` +
		`// It re-implements no business rule and re-types no entity.\n` +
		`func ${typeName}Handler(op operation.Operation, deps operation.Deps) http.HandlerFunc {\n` +
		`\treturn func(w http.ResponseWriter, r *http.Request) {\n` +
		`\t\tif r.Method != ${JSON.stringify(method)} {\n` +
		`\t\t\thttp.Error(w, "method not allowed", http.StatusMethodNotAllowed)\n` +
		`\t\t\treturn\n\t\t}\n` +
		`\t\tvar req ${typeName}Request\n` +
		`\t\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {\n` +
		`\t\t\thttp.Error(w, "bad request", http.StatusBadRequest)\n` +
		`\t\t\treturn\n\t\t}\n` +
		`\t\tinput := map[string]any{\n${inputLines}\n\t\t}\n` +
		`\t\tstate := operation.NewState(input, map[string]any{})\n` +
		`\t\t_, result, err := operation.Interpret(op, state, deps)\n` +
		`\t\tif err != nil {\n` +
		`\t\t\thttp.Error(w, "operation failed", http.StatusUnprocessableEntity)\n` +
		`\t\t\treturn\n\t\t}\n` +
		`\t\tresp := ${typeName}Response{\n${respLines}\n\t\t}\n` +
		`\t\t_ = result\n` +
		`\t\tw.Header().Set("Content-Type", "application/json")\n` +
		`\t\tw.WriteHeader(http.StatusCreated)\n` +
		`\t\t_ = json.NewEncoder(w).Encode(resp)\n` +
		`\t}\n}\n`;

	return {
		path: "back/gen/api/order.go",
		target: "api",
		bytes: src,
		source_hash: hash,
		output_hash: sha256(src),
		protected: true,
	};
}

const EXAMPLE_VALUE: Record<ScalarType, unknown> = {
	string: "example",
	int: 1,
	decimal: "0",
	bool: false,
	timestamptz: "1970-01-01T00:00:00Z",
};

/** EmitContract — the Pact-v3 contract, byte-identical (when JSON-stringified canonically). */
export function emitContract(op: Operation, e: Entity): PactContract {
	const hash = sourceHash(op, e);
	const { method, route } = methodRoute(e.name);
	const reqBody: Record<string, unknown> = {};
	const respBody: Record<string, unknown> = {};
	for (const a of e.attributes) {
		respBody[a.name] = EXAMPLE_VALUE[a.type];
		if (a.required) reqBody[a.name] = EXAMPLE_VALUE[a.type];
	}
	return {
		consumer: { name: "aidos-workbench" },
		provider: { name: `${op.name}-provider` },
		source_hash: hash,
		interactions: [
			{
				description: `${op.name} creates a ${e.name}`,
				request: { method, path: route, body: reqBody },
				response: { status: 201, body: respBody },
			},
		],
		metadata: { pactSpecification: { version: "3.0.0" } },
	};
}

/** The Pact contract as canonical, pretty JSON — byte-identical to Go ContractJSON. */
export function contractJSON(c: PactContract): string {
	const wire = {
		consumer: c.consumer,
		interactions: c.interactions,
		metadata: c.metadata,
		provider: c.provider,
	};
	// Canonicalize (sort keys recursively) then pretty-print with 2-space indent — the
	// same shape Go's records.Canonicalize + json.Indent produce.
	return JSON.stringify(JSON.parse(canon(wire)), null, 2);
}

/**
 * VerifyContract — the in-process provider verification verdict. The twin reproduces the
 * Go verifier deterministically: the reference provider echoes the entity attribute set
 * as the response, so the response field set == the contract field set ⇒ PASS. (The twin
 * does not stand an HTTP server up; it computes the SAME field-set/status assertion.)
 */
export function verifyContract(c: PactContract, e: Entity): VerifyResult {
	const verified: string[] = [];
	for (const it of c.interactions) {
		const providerKeys = e.attributes.map((a) => a.name).sort();
		const wantKeys = Object.keys(it.response.body).sort();
		if (it.response.status !== 201)
			return {
				pass: false,
				reason: `interaction "${it.description}": status mismatch`,
				interactions: [],
			};
		if (
			providerKeys.length !== wantKeys.length ||
			providerKeys.some((k, i) => k !== wantKeys[i])
		)
			return {
				pass: false,
				reason: `interaction "${it.description}": response field set ${JSON.stringify(providerKeys)} != contract ${JSON.stringify(wantKeys)}`,
				interactions: [],
			};
		verified.push(it.description);
	}
	return {
		pass: true,
		reason: "all interactions honoured the contract",
		interactions: verified,
	};
}
