/**
 * db-projection — the BYTE-IDENTICAL TypeScript twin of the Go db-projection emitter
 * (back/gen/db.{EmitMigration,RequireMigration,DataTruthScope}). It is a PURE,
 * deterministic projection: no I/O, no clock, no RNG, no LLM. The Workbench
 * /db-projection panel re-emits + evaluates the SAME twin so what is on screen matches
 * the engine. The authoritative bytes/hashes are the Go ones (GO_* constants below);
 * the fast-check mirror (db-projection.test.ts) pins the twin to them.
 *
 * THE WALL (the wall, §2): the entity is a SOURCE above the line (read SELECT-only);
 * back/gen/db is generated-only (never hand-edited); a DataTruthScope is written via
 * propose → ChangeSet → approval, never from the screen. This twin renders + evaluates,
 * it never writes truth.
 */

/** One pinned entity field (the db projection reads exactly what the AST pins). */
export interface Field {
	name: string;
	type: "text" | "numeric" | "int" | "bool" | "timestamptz";
}

/** The entity source the emitter projects (the agent-side mirror of kernel.entity). */
export interface EntitySource {
	name: string;
	fields: Field[];
}

export const PROTECTED_MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

/** The closed §44.3 migration.strategy set — declared, never discovered. */
export const STRATEGIES = [
	"expand_contract",
	"backfill",
	"dual_read",
	"dual_write",
] as const;
export type Strategy = (typeof STRATEGIES)[number];

/** The closed §44.3 applies_to set. */
export const APPLIES_TO = [
	"new_records",
	"existing_records",
	"historical_records",
] as const;
export type AppliesTo = (typeof APPLIES_TO)[number];

export interface DataTruthScope {
	applies_to: AppliesTo[];
	migration: { required: boolean; strategy: string };
	audit: { preserve_old_truth: boolean };
}

export interface Change {
	change_type: string;
	entity: string;
	applies_to: AppliesTo[];
	scope?: DataTruthScope;
}

/** A BlockReason code surfaced by the guard (S13 shape; the two S37 codes). */
export type BlockCode =
	| "HISTORICAL_IMPACT_REQUIRES_MIGRATION"
	| "UNKNOWN_MIGRATION_STRATEGY";

export interface BlockReason {
	code: BlockCode;
	severity: "blocking";
	how_to_fix: string[];
}

const DDL_TYPE: Record<Field["type"], string> = {
	text: "TEXT",
	numeric: "NUMERIC",
	int: "BIGINT",
	bool: "BOOLEAN",
	timestamptz: "TIMESTAMPTZ",
};

function header(sourceHash: string): string {
	return `-- ${PROTECTED_MARKER}. source: ${sourceHash}\n`;
}

function sortedFields(e: EntitySource): Field[] {
	return [...e.fields].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
}

export interface MigrationArtifact {
	bytes: string;
	sourceHash: string;
	shape: "create" | "expand" | "expand_contract";
}

/**
 * EmitMigration — the byte-identical twin. The sourceHash is the Go-computed content
 * address (passed in by the caller from the pinned GO_* constants — the twin does not
 * re-hash in the browser; the cross-language anchor is the Go hash). prior == undefined
 * ⇒ the full CREATE TABLE; an added-only diff ⇒ EXPAND; any dropped column ⇒
 * EXPAND→BACKFILL→CONTRACT (forward-only).
 */
export function emitMigration(
	entity: EntitySource,
	prior: EntitySource | undefined,
	sourceHash: string,
): MigrationArtifact {
	if (!prior) {
		const fields = sortedFields(entity);
		let b = header(sourceHash);
		b += `CREATE TABLE "${entity.name.toLowerCase()}" (\n`;
		fields.forEach((f, i) => {
			const comma = i === fields.length - 1 ? "" : ",";
			b += `    "${f.name}" ${DDL_TYPE[f.type]} NOT NULL${comma}\n`;
		});
		b += ");\n";
		return { bytes: b, sourceHash, shape: "create" };
	}
	const oldNames = new Set(prior.fields.map((f) => f.name));
	const newNames = new Set(entity.fields.map((f) => f.name));
	// Added fields: in the new entity, not in the prior — in stable (sorted) order.
	const added: Field[] = entity.fields
		.filter((f) => !oldNames.has(f.name))
		.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
	// Dropped names: in the prior, not in the new — in stable (sorted) order.
	const dropped: string[] = prior.fields
		.map((f) => f.name)
		.filter((n) => !newNames.has(n))
		.sort();
	const table = entity.name.toLowerCase();
	if (dropped.length === 0) {
		let b = header(sourceHash);
		b +=
			"-- expand-contract / forward-only: an additive column add is an EXPAND step.\n";
		b +=
			"-- New columns are NULLable so no historical row is rewritten or dropped (KRD §44.3).\n";
		for (const f of added) {
			b += `ALTER TABLE "${table}" ADD COLUMN IF NOT EXISTS "${f.name}" ${DDL_TYPE[f.type]};\n`;
		}
		return { bytes: b, sourceHash, shape: "expand" };
	}
	let b = header(sourceHash);
	b +=
		"-- expand-contract / forward-only: a NARROWING change is split EXPAND → BACKFILL → CONTRACT.\n";
	b +=
		"-- A destructive change is NEVER a single silent step (KRD §44.3 — les données ont leur propre inertie).\n";
	b +=
		"\n-- [1/3] EXPAND — add the new shape additively (NULLable, no historical rewrite).\n";
	if (added.length === 0)
		b += "-- (no new columns to add in this narrowing change)\n";
	for (const f of added) {
		b += `ALTER TABLE "${table}" ADD COLUMN IF NOT EXISTS "${f.name}" ${DDL_TYPE[f.type]};\n`;
	}
	b +=
		"\n-- [2/3] BACKFILL — declared (DataTruthScope.strategy), human-gated, NOT executed here.\n";
	b +=
		"-- The backfill of existing/historical rows is a SEPARATE forward-only step run by the\n";
	b +=
		"-- aidos writer under an approved DataTruthScope (preserve_old_truth:true); emitting it\n";
	b +=
		"-- silently here would rewrite historical data — forbidden. Placeholder only:\n";
	for (const n of dropped)
		b += `-- backfill_then_drop: ${table}.${n} — preserve_old_truth before the contract step.\n`;
	b +=
		"\n-- [3/3] CONTRACT — drop the removed column(s) in a SEPARATE forward step, AFTER backfill,\n";
	b +=
		"-- gated by the declared DataTruthScope (RequireMigration). Emitted as a guarded, idempotent\n";
	b +=
		"-- forward step so the dry-run validates its SHAPE without destroying historical truth.\n";
	for (const n of dropped)
		b += `ALTER TABLE "${table}" DROP COLUMN IF EXISTS "${n}";\n`;
	return { bytes: b, sourceHash, shape: "expand_contract" };
}

function touchesHistorical(set: AppliesTo[]): boolean {
	return set.some(
		(a) => a === "existing_records" || a === "historical_records",
	);
}

function isKnownStrategy(s: string): boolean {
	return (STRATEGIES as readonly string[]).includes(s);
}

export interface RequireResult {
	required: boolean;
	block?: BlockReason;
}

/**
 * requireMigration — the byte-identical twin of the pure Go guard. A historical-impact
 * change with no declared migration ⇒ Blocked(HISTORICAL_IMPACT_REQUIRES_MIGRATION); an
 * unknown strategy ⇒ Blocked(UNKNOWN_MIGRATION_STRATEGY); a required migration must
 * carry preserve_old_truth; a new-records-only change ⇒ allowed.
 */
export function requireMigration(c: Change): RequireResult {
	const historical = touchesHistorical(c.applies_to);
	if (c.scope && !isKnownStrategy(c.scope.migration.strategy)) {
		return {
			required: historical,
			block: {
				code: "UNKNOWN_MIGRATION_STRATEGY",
				severity: "blocking",
				how_to_fix: [
					"use_a_known_strategy : expand_contract | backfill | dual_read | dual_write.",
					"do_not_invent : aucune stratégie hors de ce jeu n'est acceptée.",
					"rerun aidos check : le blocage se lève dès que la stratégie est membre du jeu fermé.",
				],
			},
		};
	}
	if (!historical) return { required: false };
	if (
		!c.scope ||
		!c.scope.migration.required ||
		!c.scope.audit.preserve_old_truth
	) {
		return {
			required: true,
			block: {
				code: "HISTORICAL_IMPACT_REQUIRES_MIGRATION",
				severity: "blocking",
				how_to_fix: [
					"declare_data_truth_scope : migration.required:true + une stratégie ∈ {expand_contract, backfill, dual_read, dual_write}.",
					"preserve_old_truth : audit.preserve_old_truth:true — l'ancienne vérité n'est jamais détruite.",
					"rerun aidos check : le blocage se lève dès que le changement porte sa migration déclarée.",
				],
			},
		};
	}
	return { required: true };
}

/**
 * The AUTHORITATIVE Go outputs (back/gen/db) the twin reproduces byte-identically — the
 * cross-language equality anchors (the same role as S35's entityId / S36's source hash).
 */
export const GO_CREATE_SOURCE_HASH =
	"f09ccd24ec6c661ffd93b8235a1b70f4e3f03e848d225679b1d88a64db609e72";
export const GO_CREATE_OUTPUT_HASH =
	"0d87b1613ea7c1956aa2604743b53bcc2a3f3b5af1a5ba420b6b8b9fb4b65026";
export const GO_EXPAND_OUTPUT_HASH =
	"32910b8f450eb4ee7661ace0d3c93a1aa824958513e7b4c603435ed17521683b";
export const GO_NARROW_SOURCE_HASH =
	"ae5116525efda38cf143e97335219f581390c752d8002995ce5839fc6332b7ad";
export const GO_NARROW_OUTPUT_HASH =
	"05815fae7a46694bac07c7fe8b63435adb8b0e1666a2750b83409d997c6b7717";
export const GO_SCOPE_ID =
	"90f716bcf23ddb0188ceffdd535f87752e0c82ff7dd972f28bd72ad85af8ff44";
