/**
 * The canonical entity AST examples for the /emitters panel (AIDOS step S34).
 *
 * The SAME entities the Go fixture (back/runtime/generators/example.go) pins —
 * Order (id / total / discount) and Thin (id) — reused from prior pinned artifacts.
 * The emitter coins no field beyond these (honesty). The panel projects each across
 * the three targets via the pure twin lib/emitters.ts, byte-identical to the Go
 * emitter (verified). The "head" hash of each entity is what the panel compares an
 * artifact's source_hash against to compute the deterministic / stale badge.
 *
 * READ-ONLY (the wall): the entity AST is a prior truth (S02). The panel reads it;
 * it never authors it.
 */

import { type EntitySource, sourceHash } from "./emitters";

/** Order — the worked example (id / total / discount). */
export const ENTITY_ORDER: EntitySource = {
	id: "entity-order",
	kind: "entity",
	name: "Order",
	fields: [
		{ name: "id", type: "text" },
		{ name: "total", type: "numeric" },
		{ name: "discount", type: "numeric" },
	],
};

/** Order with `discount` removed — the "changed source" (the head moved ahead). A prior
 *  artifact emitted from the full Order is now STALE relative to this head. */
export const ENTITY_ORDER_CHANGED: EntitySource = {
	id: "entity-order",
	kind: "entity",
	name: "Order",
	fields: [
		{ name: "id", type: "text" },
		{ name: "total", type: "numeric" },
	],
};

/** Thin — the minimal honest entity (only id): the emitter emits ONLY the pinned field. */
export const ENTITY_THIN: EntitySource = {
	id: "entity-thin",
	kind: "entity",
	name: "Thin",
	fields: [{ name: "id", type: "text" }],
};

/** The entities the panel projects, in a stable order. */
export const ENTITIES: EntitySource[] = [ENTITY_ORDER, ENTITY_THIN];

/**
 * FN06 — a sample of the EMITTED APP's functional code (the "code émis", not the AIDOS Go itself):
 * pure functions, zero global mutable, an acyclic call graph (the FN02 mandate, ADR 0036). It carries
 * the AIDOS protected marker so callGraphIndex treats it as in-scope (FN05). The functions form the
 * worked checkout slice (S46) in the functional style: priceLine → applyDiscount → total; total →
 * priceLine. This is what the /emitters panel VISUALISES as a functional graph (FN06). Static byte
 * literal — no clock, no randomness — so the graph (and its hash) is reproducible.
 */
export const EMITTED_FUNCTIONAL_GO = `// CODE GENERATED BY AIDOS — DO NOT EDIT. source: emitted-checkout-functional
package checkout

func priceLine(qty int, unit int) int { return qty * unit }

func applyDiscount(amount int, pct int) int { return amount - priceLine(amount, pct)/100 }

func total(qty int, unit int, pct int) int {
	line := priceLine(qty, unit)
	return applyDiscount(line, pct)
}
`;

/** A pre-recorded ledger row: the prior Order artifact (full Order) — kept for the
 *  STALE demo. Its source_hash is the FULL Order head; once the head moves to
 *  ENTITY_ORDER_CHANGED, this artifact is stale (its source_hash != the new head). */
export const PRIOR_ORDER_SOURCE_HASH = sourceHash(ENTITY_ORDER);

/** The "current head" the panel uses for the STALE demo: the changed Order. */
export const ORDER_HEAD_AFTER_CHANGE = sourceHash(ENTITY_ORDER_CHANGED);
