/**
 * The Emitters twin — the Workbench /emitters source (AIDOS step S34).
 *
 * The DECLARED projection of the Go package back/runtime/generators: the same
 * deterministic emitter set, one per `kind × target` (kind = entity; target ∈
 * {go-sqlc, pg-ddl, ts-types}), the same protected header, the same content-address
 * (source_hash = SHA-256 over the canonical entity body — byte-equal to Go's
 * records.Hash(records.Canonicalize(body)), verified) and the same output_hash
 * (SHA-256 over the emitted bytes). One source → N projections, never double-typed
 * (CONTEXT-MAP). /emitters renders exactly what Emit/Project compute — no drift.
 *
 * DETERMINISM-FIRST (CLAUDE.md §6/§8): pure functions over their input — no clock,
 * no rng, no I/O, no LLM — so the same entity always yields byte-identical output
 * and the same hashes. The reproducibility mirror lib/emitters.test.ts (fast-check)
 * pins determinism, the content-addressed source, the protected header,
 * order-independence, no inter-target drift, no silent stale hash, and the
 * BlockReason-on-malformed totality. The byte-stability of the Go output is the
 * authoritative truth; this twin reproduces it for the screen.
 *
 * READ-ONLY (CLAUDE.md §7 ui-completeness, the wall): /emitters PROJECTS the emitted
 * artifacts; it never writes truth. The emitter READS the entity AST (SELECT-only on
 * kernel) and the emit ledger; truth-writes go via propose → ChangeSet → approval,
 * never a screen. Hand-editing gen/ is forbidden — the panel shows the drift instead.
 */

import { createHash } from "node:crypto";

/** The CLOSED set of emitter targets (grows only additively — mobile/api are later teeth). */
export type Target = "go-sqlc" | "pg-ddl" | "ts-types";

/** The canonical target order — declared, never derived from iteration (determinism). */
export const TARGETS: readonly Target[] = [
	"go-sqlc",
	"pg-ddl",
	"ts-types",
] as const;

/** The source kind an emitter reads. Currently only `entity` (the N3 contract AST, S02). */
export type Kind = "entity";

/** The CLOSED set of canonical entity field types, mapped per target (never guessed). */
export type FieldType = "text" | "numeric" | "int" | "bool" | "timestamptz";

/** One pinned field of an entity AST — the emitter renders EXACTLY these, never an invented one. */
export interface Field {
	name: string;
	type: FieldType;
}

/** The entity AST the emitter CONSUMES (OQ-S34-entity-kind: not yet a kernel record kind). */
export interface EntitySource {
	id: string;
	kind: Kind;
	name: string;
	fields: Field[];
}

/** One emitted projection — content-addressed by source (source_hash) and output (output_hash). */
export interface Artifact {
	path: string;
	target: Target;
	kind: Kind;
	bytes: string;
	source_hash: string;
	output_hash: string;
	protected: true;
}

/** The S13 BlockReason shape (reused, never a new code beyond a human red). */
export interface BlockReason {
	code: string;
	severity: "blocking";
	explanation: string;
	how_to_fix: string[];
}

/** The exact protected marker every emitted file carries (byte-equal to the Go const). */
export const PROTECTED_MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

/** The per-type, per-target binding (text→string→TEXT, numeric→pgtype.Numeric→NUMERIC, …). */
const TYPE_MAP: Record<FieldType, { ddl: string; gos: string; ts: string }> = {
	text: { ddl: "TEXT", gos: "string", ts: "string" },
	numeric: { ddl: "NUMERIC", gos: "pgtype.Numeric", ts: "string" },
	int: { ddl: "BIGINT", gos: "int64", ts: "number" },
	bool: { ddl: "BOOLEAN", gos: "bool", ts: "boolean" },
	timestamptz: { ddl: "TIMESTAMPTZ", gos: "pgtype.Timestamptz", ts: "string" },
};

const KNOWN_TYPES = Object.keys(TYPE_MAP) as FieldType[];

/** SHA-256 hex — the same content hash Go uses (records.Hash). */
function sha256(s: string): string {
	return createHash("sha256").update(s).digest("hex");
}

/**
 * canonicalSourceBody mirrors Go's records.Canonicalize(json.Marshal(EntitySource)):
 * object keys sorted lexicographically (recursively), array order preserved, no
 * insignificant whitespace. Verified byte-equal to the Go SourceBody.
 */
function canonicalSourceBody(s: EntitySource): string {
	const canon = (v: unknown): string => {
		if (Array.isArray(v)) return `[${v.map(canon).join(",")}]`;
		if (v && typeof v === "object") {
			const keys = Object.keys(v as Record<string, unknown>).sort();
			return `{${keys
				.map(
					(k) =>
						`${JSON.stringify(k)}:${canon((v as Record<string, unknown>)[k])}`,
				)
				.join(",")}}`;
		}
		return JSON.stringify(v);
	};
	// Sort fields by name FIRST so field-array order is not semantic — reordering the
	// pinned fields yields the SAME source_hash (mirrors Go's SourceBody). An entity's
	// identity is its field SET + types, not the order they were written.
	return canon({
		fields: sortedFields(s),
		id: s.id,
		kind: s.kind,
		name: s.name,
	});
}

/** The content address of an entity source body (= Go's records.Hash(Canonicalize(body))). */
export function sourceHash(s: EntitySource): string {
	return sha256(canonicalSourceBody(s));
}

/** Fields in STABLE (by-name) order — determinism: output never depends on input order. */
function sortedFields(s: EntitySource): Field[] {
	return [...s.fields].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
}

function goName(s: string): string {
	return s ? s[0].toUpperCase() + s.slice(1) : s;
}

function header(prefix: string, hash: string): string {
	return `${prefix} ${PROTECTED_MARKER}. source: ${hash}\n`;
}

function renderPgDDL(s: EntitySource, hash: string): string {
	const fields = sortedFields(s);
	const cols = fields
		.map(
			(f, i) =>
				`    ${JSON.stringify(f.name)} ${TYPE_MAP[f.type].ddl} NOT NULL${i === fields.length - 1 ? "" : ","}`,
		)
		.join("\n");
	return `${header("--", hash)}CREATE TABLE ${JSON.stringify(s.name.toLowerCase())} (\n${cols}\n);\n`;
}

function renderGoSqlc(s: EntitySource, hash: string): string {
	const fields = sortedFields(s);
	const needsPgtype = fields.some((f) =>
		TYPE_MAP[f.type].gos.startsWith("pgtype."),
	);
	const imp = needsPgtype
		? 'import (\n\t"github.com/jackc/pgx/v5/pgtype"\n)\n\n'
		: "";
	// gofmt aligns struct field types into a SPACE-padded column (after the leading
	// tab indent): name + spaces to (widest name + 1) + type. Mirror it exactly so the
	// go-sqlc projection is byte-identical to the Go emitter (which runs go/format.Source).
	const names = fields.map((f) => goName(f.name));
	const widest = names.reduce((m, n) => Math.max(m, n.length), 0);
	const body = fields
		.map((f) => {
			const n = goName(f.name);
			const pad = " ".repeat(widest - n.length + 1);
			return `\t${n}${pad}${TYPE_MAP[f.type].gos}`;
		})
		.join("\n");
	return `${header("//", hash)}package ${s.name.toLowerCase()}gen\n\n${imp}type ${goName(s.name)} struct {\n${body}\n}\n`;
}

function renderTSTypes(s: EntitySource, hash: string): string {
	const body = sortedFields(s)
		.map((f) => `\t${f.name}: ${TYPE_MAP[f.type].ts};`)
		.join("\n");
	return `${header("//", hash)}export interface ${goName(s.name)} {\n${body}\n}\n`;
}

function artifactPath(s: EntitySource, t: Target): string {
	const name = s.name.toLowerCase();
	switch (t) {
		case "go-sqlc":
			return `back/gen/${name}/${name}.go`;
		case "pg-ddl":
			return `back/gen/${name}/schema.sql`;
		case "ts-types":
			return `front/web/gen/${name}/${name}.ts`;
	}
}

/** A non-empty, well-typed entity is projectable; otherwise Emit returns a BlockReason. */
function validate(s: EntitySource): string | null {
	if (s.kind !== "entity") return `unknown source kind: ${s.kind}`;
	if (!s.name) return "entity AST pins no name";
	if (s.fields.length === 0) return "entity AST pins no fields";
	for (const f of s.fields) {
		if (!f.name) return "entity AST pins an unnamed field";
		if (!KNOWN_TYPES.includes(f.type))
			return `entity field pins an unknown type: ${f.type}`;
	}
	return null;
}

function blockMalformed(cause: string): BlockReason {
	return {
		code: "OUT_OF_SCOPE",
		severity: "blocking",
		explanation: `Émission refusée : l'AST d'entité est malformé ou vide (${cause}). Un emitter REND exactement les champs épinglés par la source ; il n'invente jamais un champ, une colonne ou un type (honnêteté).`,
		how_to_fix: [
			"pin_the_entity_ast : complétez l'AST d'entité dans le kernel (nom + champs typés).",
			"use_a_known_type : chaque champ porte un type du jeu fermé (text | numeric | int | bool | timestamptz).",
			"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
		],
	};
}

/** A type guard the panel uses to discriminate an Artifact (or Artifact[]) from a BlockReason. */
export function isBlocked(
	x: Artifact | Artifact[] | BlockReason,
): x is BlockReason {
	return !Array.isArray(x) && (x as BlockReason).code !== undefined;
}

/** Emit — the pure emitter for one target. Byte-identical to the Go Emit. */
export function emit(s: EntitySource, t: Target): Artifact | BlockReason {
	if (!TARGETS.includes(t)) return blockMalformed(`unknown target: ${t}`);
	const cause = validate(s);
	if (cause) return blockMalformed(cause);
	const hash = sourceHash(s);
	const bytes =
		t === "go-sqlc"
			? renderGoSqlc(s, hash)
			: t === "pg-ddl"
				? renderPgDDL(s, hash)
				: renderTSTypes(s, hash);
	return {
		path: artifactPath(s, t),
		target: t,
		kind: "entity",
		bytes,
		source_hash: hash,
		output_hash: sha256(bytes),
		protected: true,
	};
}

/** Project — fan one or more sources across targets, in canonical (stable) order. */
export function project(
	sources: EntitySource[],
	targets: readonly Target[],
): Artifact[] | BlockReason {
	const ordered = TARGETS.filter((t) => targets.includes(t));
	const out: Artifact[] = [];
	for (const s of sources) {
		for (const t of ordered) {
			const a = emit(s, t);
			if (isBlocked(a)) return a;
			out.push(a);
		}
	}
	return out;
}

/** Drifted — a gen/ file hand-edited diverges from the ledger output_hash (computed, not hunted). */
export function drifted(
	ledgerOutputHash: string,
	onDiskBytes: string,
): boolean {
	return sha256(onDiskBytes) !== ledgerOutputHash;
}

/** Stale — an artifact whose source_hash no longer equals the entity's current head (feeds S22). */
export function stale(
	artifactSourceHash: string,
	headSourceHash: string,
): boolean {
	return artifactSourceHash !== headSourceHash;
}
