/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: the DP08 mirror asserts LITERAL ${VAR} env-references (never values) throughout. */
import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { ENVIRONMENTS, resolveFor } from "./connections";
import {
	classifyLiteral,
	DEMO_EMITTED_TREE,
	hashVerdict,
	LEAK_PATH,
	LEAK_SOURCE,
	REASONS,
	RULE,
	scanSource,
	sense,
} from "./endpoint-fitness";

/**
 * Reproducibility mirror (vitest + fast-check): reflects=DP08-endpoint-fitness,
 * test_kind=property, cert_language=vitest, liveness=live.
 *
 * DP08 — the TS AST pass of the EMITTED_NO_HARDCODED_ENDPOINT arch-fitness
 * invariant (A7: the REAL TypeScript compiler API, never an LLM judge, never
 * an ad-hoc prose check). The Go pass back/runtime/endpointfitness is the
 * byte-parity-pinned twin: the canonical demo sandbox tree must hash to the
 * EXACT Go addresses GO_GREEN_ADDRESS / GO_RED_ADDRESS.
 *
 * Laws (the DP08 done-criteria, twin side):
 *   L1 byte parity with Go — green and red (injected) demo verdicts hash to
 *      the pinned Go addresses;
 *   L2 determinism — same tree → same verdict, same address, ∀ (the
 *      reproducibility mirror: même arbre → même verdict);
 *   L3 a resolved DP07 endpoint always passes — every resolveFor(env)
 *      EndpointPattern embedded in emitted source scans green;
 *   L4 fault-injection — injecting a hardcoded endpoint reddens the sensor
 *      naming the file; removing the literal turns it green again;
 *   L5 closed reasons — every finding reason is in the closed four-member set;
 *   L6 AST semantics — template ${expr} spans poison adjacency, comments are
 *      not literals, literals inside ${expr} spans are still scanned.
 */

// The Go-AUTHORITATIVE content addresses (back/runtime/endpointfitness —
// pinned by the fixture mirror endpointfitness_fixture_test.go).
const GO_GREEN_ADDRESS =
	"43f2e914534d162173904514b6e5e0d916584092df50ce47944564a264a52970";
const GO_RED_ADDRESS =
	"5164a99a4a7d189cbbe25d0741ffee776720f841328e4c4c80e86e87d5546a0a";

describe("DP08 — L1 byte parity with the authoritative Go sensor", () => {
	it("the green demo sandbox tree hashes to the Go-pinned address", async () => {
		const v = sense(DEMO_EMITTED_TREE);
		expect(v.state).toBe("green");
		expect(v.findings).toEqual([]);
		expect(await hashVerdict(v)).toBe(GO_GREEN_ADDRESS);
	});

	it("the injected (red) demo tree hashes to the Go-pinned address", async () => {
		const v = sense({ ...DEMO_EMITTED_TREE, [LEAK_PATH]: LEAK_SOURCE });
		expect(v.state).toBe("red");
		expect(v.findings).toEqual([
			{
				file: LEAK_PATH,
				line: 2,
				literal: "https://1.2.3.4:5432",
				reason: "ip_literal",
			},
		]);
		expect(await hashVerdict(v)).toBe(GO_RED_ADDRESS);
	});
});

const arbLeak: fc.Arbitrary<string> = fc.oneof(
	fc
		.tuple(
			fc.integer({ min: 0, max: 255 }),
			fc.integer({ min: 0, max: 255 }),
			fc.integer({ min: 0, max: 255 }),
			fc.integer({ min: 0, max: 255 }),
			fc.integer({ min: 10, max: 65535 }),
		)
		.map(([a, b, c, d, p]) => `https://${a}.${b}.${c}.${d}:${p}`),
	fc.integer({ min: 10, max: 65535 }).map((p) => `localhost:${p}`),
	fc
		.tuple(
			fc.stringMatching(/^[a-z][a-z0-9-]{0,11}$/),
			fc.integer({ min: 10, max: 65535 }),
		)
		.map(([h, p]) => `${h}.sagedesk.fr:${p}`),
);

describe("DP08 — L2 determinism (même arbre → même verdict)", () => {
	it("∀ tree: sense twice → identical verdict and identical address", async () => {
		await fc.assert(
			fc.asyncProperty(
				fc.dictionary(
					fc.stringMatching(/^gen\/app\/[a-z]{1,8}\.ts$/),
					fc.oneof(
						fc.constant(DEMO_EMITTED_TREE["gen/app/worker.ts"]),
						arbLeak.map((l) => `export const LEAK = "${l}";\n`),
					),
					{ maxKeys: 4 },
				),
				async (tree) => {
					const v1 = sense(tree);
					const v2 = sense(tree);
					expect(v2).toEqual(v1);
					expect(await hashVerdict(v2)).toBe(await hashVerdict(v1));
				},
			),
			{ numRuns: 50 },
		);
	});
});

describe("DP08 — L3 a resolved DP07 endpoint always passes", () => {
	it("every resolveFor(env) endpoint pattern scans green, all five environments", () => {
		for (const env of ENVIRONMENTS) {
			for (const r of resolveFor(env)) {
				if ("code" in r) continue;
				const src = `// Code generated by AIDOS — DO NOT EDIT.\nexport const endpoint = "${r.endpoint_pattern}";\n`;
				expect(scanSource("gen/app/endpoint.ts", src)).toEqual([]);
			}
		}
	});
});

describe("DP08 — L4 fault-injection: red on injection, green on removal", () => {
	it("∀ hardcoded leak: inject → red naming the file; remove → green", () => {
		fc.assert(
			fc.property(arbLeak, (leak) => {
				const injected = {
					...DEMO_EMITTED_TREE,
					"gen/app/leak.ts": `// fault injection\nexport const LEAK = "${leak}";\n`,
				};
				const red = sense(injected);
				expect(red.state).toBe("red");
				expect(red.findings.some((f) => f.file === "gen/app/leak.ts")).toBe(
					true,
				);
				const green = sense(DEMO_EMITTED_TREE);
				expect(green.state).toBe("green");
			}),
			{ numRuns: 60 },
		);
	});
});

describe("DP08 — L5 closed reasons", () => {
	it("∀ leak: every finding reason is in the closed set", () => {
		fc.assert(
			fc.property(arbLeak, (leak) => {
				const findings = scanSource(
					"gen/app/leak.ts",
					`export const LEAK = "${leak}";\n`,
				);
				expect(findings.length).toBeGreaterThan(0);
				for (const f of findings) {
					expect(REASONS).toContain(f.reason);
				}
			}),
			{ numRuns: 60 },
		);
	});

	it("the rule and the closed set are the declared ones", () => {
		expect(RULE).toBe("EMITTED_NO_HARDCODED_ENDPOINT");
		expect(REASONS).toEqual([
			"localhost_literal",
			"ip_literal",
			"url_concrete_host",
			"host_port_literal",
		]);
	});
});

describe("DP08 — L6 AST semantics (the real TypeScript compiler pass)", () => {
	it("env-derived endpoints pass: ${expr} spans and ${VAR} placeholders poison adjacency", () => {
		const src =
			'const db = `${requireEnv("APP_NAME")}-db:5432`;\n' +
			'const url = `https://${requireEnv("APP_SUBDOMAIN")}.${requireEnv("DOMAIN")}`;\n' +
			'const compose = "${APP_NAME}-cache:6379";\n' +
			'const managed = "${CRM_MANAGED_URL}";\n';
		expect(scanSource("gen/app/ok.ts", src)).toEqual([]);
	});

	it("comments are not literals; concrete literals are caught with file and line", () => {
		const src =
			"// localhost:9999 in a comment is not an endpoint\n" +
			"/* https://1.2.3.4:5432 */\n" +
			'const leak = "db.sagedesk.fr:5432";\n';
		expect(scanSource("gen/app/bad.ts", src)).toEqual([
			{
				file: "gen/app/bad.ts",
				line: 3,
				literal: "db.sagedesk.fr:5432",
				reason: "host_port_literal",
			},
		]);
	});

	it("a literal inside a template ${expr} span is still scanned", () => {
		const src = 'const x = `${connect("localhost:5432")}`;\n';
		const findings = scanSource("gen/app/inner.ts", src);
		expect(findings).toHaveLength(1);
		expect(findings[0]?.reason).toBe("localhost_literal");
	});

	it("classifyLiteral pins the canonical SPEC-stack-2026 table", () => {
		for (const ok of [
			"${APP_NAME}-db:5432",
			"${CRM_MANAGED_URL}",
			"https://${APP_SUBDOMAIN}.${DOMAIN}",
			"docker_internal",
			"MISSING_ENV_AT_BOOT: ",
		]) {
			expect(classifyLiteral(ok)).toBeNull();
		}
		expect(classifyLiteral("https://1.2.3.4:5432")).toBe("ip_literal");
		expect(classifyLiteral("localhost:3000")).toBe("localhost_literal");
		expect(classifyLiteral("postgres://localhost:5432/app")).toBe(
			"localhost_literal",
		);
		expect(classifyLiteral("https://aidos.sagedesk.fr")).toBe(
			"url_concrete_host",
		);
		expect(classifyLiteral("alphashop-db:5432")).toBe("host_port_literal");
	});
});
