/**
 * The Entity-source twin — the Workbench /entity-map source (AIDOS step S35).
 *
 * The DECLARED projection of the Go package back/kernel/entities: the SAME entity
 * SOURCE AST (name + ORDERED attributes[] {name, type, required, identifier?,
 * multivalued?} over the closed scalar set string|int|decimal|bool|timestamptz) and
 * the SAME three deterministic emitters — EmitGo (sqlc-shaped struct), EmitTS (the
 * shared type), EmitDDL (the expand-contract CREATE TABLE). One source → three
 * projections, never double-typed (CLAUDE.md §3). /entity-map renders exactly what
 * the Go emitters compute — byte-identical (verified on all three Order artifacts).
 *
 * DISTINCT FROM lib/emitters.ts (S34): that twin sorts fields and emits NOT NULL on
 * every column (an order-free, thin projection). THIS twin PRESERVES attribute order
 * (the order is semantic) and is required-aware (required → NOT NULL / TS non-optional,
 * identifier → PRIMARY KEY). The two never share a gen/ path.
 *
 * DETERMINISM-FIRST (CLAUDE.md §6/§8): pure functions over their input — no clock, no
 * rng, no I/O, no LLM — so the same entity always yields byte-identical output and the
 * same content hash. The reproducibility mirror lib/entity-source.test.ts (fast-check)
 * pins determinism, the content-addressed source, the protected header, no add/drop/
 * rename, order preservation, the required⇔NOT NULL⇔non-optional law, the single PK,
 * and the BlockReason-on-unknown-type totality. The Go output is the AUTHORITATIVE
 * truth; this twin reproduces it for the screen.
 *
 * READ-ONLY (the wall): /entity-map PROJECTS the emitted artifacts; it never writes
 * truth. The entity AST is a SOURCE above the line (the agent reads it SELECT-only);
 * gen/ is never hand-edited; truth-writes go via propose → ChangeSet → approval.
 */

import { createHash } from "node:crypto";

/** The CLOSED entity scalar type set — the ubiquitous domain types, never invented. */
export type ScalarType = "string" | "int" | "decimal" | "bool" | "timestamptz";

/** The canonical scalar order — declared, never derived from iteration (determinism). */
export const SCALAR_TYPES: readonly ScalarType[] = [
	"string",
	"int",
	"decimal",
	"bool",
	"timestamptz",
] as const;

/** One ORDERED attribute of an entity. Its position is SEMANTIC (struct/field/column order). */
export interface Attribute {
	name: string;
	type: ScalarType;
	required: boolean;
	identifier?: boolean;
	multivalued?: boolean;
}

/** The entity SOURCE AST (KRD §23): name + an ORDERED slice of attributes. */
export interface Entity {
	name: string;
	attributes: Attribute[];
}

/** One emitted projection — content-addressed by source (source_hash) and output (output_hash). */
export interface Artifact {
	path: string;
	target: Target;
	bytes: string;
	source_hash: string;
	output_hash: string;
	protected: true;
}

/** The closed projection target set (one source → exactly these three at S35). */
export type Target = "go-sqlc" | "ts-types" | "pg-ddl";

/** The canonical target order — Go, TS, DDL. */
export const TARGETS: readonly Target[] = [
	"go-sqlc",
	"ts-types",
	"pg-ddl",
] as const;

/** The S13 BlockReason shape (reused, never a new code beyond a human red). */
export interface BlockReason {
	code: string;
	severity: "blocking";
	explanation: string;
	how_to_fix: string[];
}

/** The exact protected marker every emitted file carries (byte-equal to the Go const). */
export const PROTECTED_MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

/** The per-scalar, per-target binding (string→string→TEXT, decimal→pgtype.Numeric→NUMERIC, …). */
const TYPE_MAP: Record<ScalarType, { ddl: string; gos: string; ts: string }> = {
	string: { ddl: "TEXT", gos: "string", ts: "string" },
	int: { ddl: "BIGINT", gos: "int64", ts: "number" },
	decimal: { ddl: "NUMERIC", gos: "pgtype.Numeric", ts: "string" },
	bool: { ddl: "BOOLEAN", gos: "bool", ts: "boolean" },
	timestamptz: { ddl: "TIMESTAMPTZ", gos: "pgtype.Timestamptz", ts: "string" },
};

const KNOWN_TYPES = Object.keys(TYPE_MAP) as ScalarType[];

/** SHA-256 hex — the same content hash Go uses (records.Hash). */
function sha256(s: string): string {
	return createHash("sha256").update(s).digest("hex");
}

/**
 * canonicalBody mirrors Go's records.Canonicalize(json.Marshal(Entity)): object keys
 * sorted lexicographically (recursively), array order PRESERVED (attribute order is
 * semantic), no insignificant whitespace, omitempty for false identifier/multivalued.
 * Verified byte-equal to the Go entities.Body.
 */
function canonicalBody(e: Entity): string {
	const canon = (v: unknown): string => {
		if (Array.isArray(v)) return `[${v.map(canon).join(",")}]`;
		if (v && typeof v === "object") {
			const keys = Object.keys(v as Record<string, unknown>).sort();
			return `{${keys
				.map(
					(k) =>
						`${JSON.stringify(k)}:${canon((v as Record<string, unknown>)[k])}`,
				)
				.join(",")}}`;
		}
		return JSON.stringify(v);
	};
	// Mirror Go's json.Marshal of Entity with `omitempty` on identifier/multivalued:
	// a false identifier/multivalued key is ABSENT (so the canonical body matches Go's).
	const attrs = e.attributes.map((a) => {
		const o: Record<string, unknown> = {
			name: a.name,
			type: a.type,
			required: a.required,
		};
		if (a.identifier) o.identifier = true;
		if (a.multivalued) o.multivalued = true;
		return o;
	});
	return canon({ attributes: attrs, name: e.name });
}

/** The content address of an entity (= Go's records.Hash(records.Canonicalize(body))). */
export function entityId(e: Entity): string {
	return sha256(canonicalBody(e));
}

function goName(s: string): string {
	return s ? s[0].toUpperCase() + s.slice(1) : s;
}

function header(prefix: string, hash: string): string {
	return `${prefix} ${PROTECTED_MARKER}. source: ${hash}\n`;
}

/** The single identifier attribute, or undefined. */
function identifier(e: Entity): Attribute | undefined {
	return e.attributes.find((a) => a.identifier);
}

function renderGo(e: Entity, hash: string): string {
	const needsPgtype = e.attributes.some((a) =>
		TYPE_MAP[a.type].gos.startsWith("pgtype."),
	);
	const imp = needsPgtype
		? 'import (\n\t"github.com/jackc/pgx/v5/pgtype"\n)\n\n'
		: "";
	// gofmt aligns struct field types into a SPACE-padded column (after the leading
	// tab): name + spaces to (widest name + 1) + type. Mirror it exactly so the Go
	// projection is byte-identical to the Go emitter (which runs go/format.Source).
	const names = e.attributes.map((a) => goName(a.name));
	const widest = names.reduce((m, n) => Math.max(m, n.length), 0);
	const body = e.attributes
		.map((a) => {
			const n = goName(a.name);
			const pad = " ".repeat(widest - n.length + 1);
			return `\t${n}${pad}${TYPE_MAP[a.type].gos}`;
		})
		.join("\n");
	return `${header("//", hash)}package ${e.name.toLowerCase()}gen\n\n${imp}type ${goName(e.name)} struct {\n${body}\n}\n`;
}

function renderTS(e: Entity, hash: string): string {
	const body = e.attributes
		.map((a) => `\t${a.name}${a.required ? "" : "?"}: ${TYPE_MAP[a.type].ts};`)
		.join("\n");
	return `${header("//", hash)}export type ${goName(e.name)} = {\n${body}\n};\n`;
}

function renderDDL(e: Entity, hash: string): string {
	const id = identifier(e);
	const cols = e.attributes
		.map((a, i) => {
			const pk = id && a.name === id.name ? " PRIMARY KEY" : "";
			const nn = a.required ? " NOT NULL" : "";
			const comma = i === e.attributes.length - 1 ? "" : ",";
			return `    ${JSON.stringify(a.name)} ${TYPE_MAP[a.type].ddl}${pk}${nn}${comma}`;
		})
		.join("\n");
	return `${header("--", hash)}CREATE TABLE ${JSON.stringify(e.name.toLowerCase())} (\n${cols}\n);\n`;
}

function artifactPath(e: Entity, t: Target): string {
	const name = `${e.name.toLowerCase()}-entity`;
	switch (t) {
		case "go-sqlc":
			return `back/gen/${name}/${e.name.toLowerCase()}.go`;
		case "pg-ddl":
			return `back/gen/${name}/schema.sql`;
		case "ts-types":
			return `front/web/gen/${name}/${e.name.toLowerCase()}.ts`;
	}
}

/** A well-typed, projectable entity returns null; otherwise the cause string. */
function validate(e: Entity): string | null {
	if (!e.name) return "entity pins no name";
	if (e.attributes.length === 0) return "entity pins no attributes";
	let ids = 0;
	for (const a of e.attributes) {
		if (!a.name) return "an attribute pins no name";
		if (!KNOWN_TYPES.includes(a.type))
			return `unknown attribute type: ${a.type}`;
		if (a.identifier) ids++;
	}
	if (ids > 1) return "more than one attribute is marked identifier";
	return null;
}

function blockUnknownType(cause: string): BlockReason {
	return {
		code: "OUT_OF_SCOPE",
		severity: "blocking",
		explanation: `Émission refusée (UNKNOWN_ATTRIBUTE_TYPE) : l'AST d'entité est malformé, ou un attribut porte un type hors du jeu scalaire fermé (${cause}). Un emitter REND exactement les attributs épinglés par la source ; il ne retombe JAMAIS silencieusement sur any/text (honnêteté).`,
		how_to_fix: [
			"use_a_known_type : chaque attribut porte un type du jeu fermé (string | int | decimal | bool | timestamptz).",
			"pin_the_entity_ast : complétez l'AST d'entité (nom + attributs typés, au plus un identifier).",
			"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
		],
	};
}

/** A type guard discriminating an Artifact (or Artifact[]) from a BlockReason. */
export function isBlocked(
	x: Artifact | Artifact[] | BlockReason,
): x is BlockReason {
	return !Array.isArray(x) && (x as BlockReason).code !== undefined;
}

/** Emit — the pure emitter for one target. Byte-identical to the Go Emit. */
export function emit(e: Entity, t: Target): Artifact | BlockReason {
	if (!TARGETS.includes(t)) return blockUnknownType(`unknown target: ${t}`);
	const cause = validate(e);
	if (cause) return blockUnknownType(cause);
	const hash = entityId(e);
	const bytes =
		t === "go-sqlc"
			? renderGo(e, hash)
			: t === "ts-types"
				? renderTS(e, hash)
				: renderDDL(e, hash);
	return {
		path: artifactPath(e, t),
		target: t,
		bytes,
		source_hash: hash,
		output_hash: sha256(bytes),
		protected: true,
	};
}

/** Project — fan an entity across targets, in canonical (stable) order. */
export function project(
	entity: Entity,
	targets: readonly Target[],
): Artifact[] | BlockReason {
	const ordered = TARGETS.filter((t) => targets.includes(t));
	const out: Artifact[] = [];
	for (const t of ordered) {
		const a = emit(entity, t);
		if (isBlocked(a)) return a;
		out.push(a);
	}
	return out;
}

/** The attribute name set in source order — the field/column set each projection must agree on. */
export function attributeSet(e: Entity): string[] {
	return e.attributes.map((a) => a.name);
}

/** Stale — an artifact whose source_hash no longer equals the entity head (feeds S22's red wave). */
export function stale(
	artifactSourceHash: string,
	headSourceHash: string,
): boolean {
	return artifactSourceHash !== headSourceHash;
}
