/**
 * The emitted-app FRONT-END emitter twin — the Workbench /front-emitter source (AIDOS S93).
 *
 * The DECLARED projection of the Go package back/runtime/frontemit: the deterministic emitter
 * that projects the project's Kernel entities + controls into the emitted app's FRONT-END
 * (Hono JSX/SSR — OQ-0040-front DECIDED): an index page, one create-form per entity (scalars
 * + blob uploads + relation selects), and the control+action verticale rendered to REAL
 * buttons, each carrying its control-spec fixture as a data-aidos-fixture SENSOR.
 *
 * DETERMINISM-FIRST (CLAUDE.md §6/§8): every emit is a PURE function of its input — no clock,
 * no rng, no I/O, no LLM — and CANONICALISES (entities/controls by name) before rendering, so
 * the SAME Kernel cut → byte-identical output, INVARIANT to input order. The Go output is the
 * AUTHORITATIVE truth; this twin reproduces the bytes for the screen so the panel shows a live,
 * deterministic preview. The reproducibility mirror lib/front-emitter.test.ts (fast-check) pins
 * determinism, input-order invariance, FN02 purity (no module-scope mutable binding), and the
 * every-control-carries-its-fixture honesty.
 *
 * READ-ONLY (the wall): /front-emitter PROJECTS; it never writes truth. The emitted bytes are a
 * projection (S78 owns regeneration), never a kernel write.
 */

export type ScalarType = "string" | "int" | "decimal" | "bool" | "timestamptz";

/** The closed scalar→HTML input map (mirrors Go frontemit.scalarInput). */
export const SCALAR_INPUT: Record<ScalarType, string> = {
	string: "text",
	int: "number",
	decimal: "text",
	bool: "checkbox",
	timestamptz: "datetime-local",
};

export type Cardinality = "1-1" | "1-N" | "N-N";

export interface ScalarAttr {
	name: string;
	type: ScalarType;
	required?: boolean;
	identifier?: boolean;
}
export interface BlobAttr {
	name: string;
	allowedMime: string[];
	maxBytes: number;
	required?: boolean;
}
export interface RelationAttr {
	name: string;
	target: string;
	cardinality: Cardinality;
	required?: boolean;
}
export interface EntityModel {
	name: string;
	attributes: ScalarAttr[];
	blobs?: BlobAttr[];
	refs?: RelationAttr[];
}

export interface FixtureRow {
	given: string;
	visible: boolean;
	enabled: boolean;
}
export interface ControlModel {
	name: string;
	view: string;
	label: string;
	operation: string;
	fixtures: FixtureRow[];
}

export interface FrontSpec {
	project: string;
	entities: EntityModel[];
	controls: ControlModel[];
}

export interface BlockReason {
	code: string;
	severity: "blocking";
	explanation: string;
	how_to_fix: string[];
}

export function isBlocked<T>(v: T | BlockReason): v is BlockReason {
	return (
		typeof v === "object" && v !== null && "code" in v && "how_to_fix" in v
	);
}

const MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

const HOW_TO_FIX = [
	"pin_the_source : complétez la source dans le Kernel (entités nommées avec attributs / contrôles avec opération liée).",
	"bind_the_button : chaque contrôle lie une opération via son action (triggers) ; un bouton sans opération n'est jamais deviné.",
	"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
];

function fail(msg: string): BlockReason {
	return {
		code: "OUT_OF_SCOPE",
		severity: "blocking",
		explanation: `Émission du front refusée : ${msg}. Un emitter REND exactement ce que la source épingle ; il n'invente jamais un formulaire, un champ, une route ni un bouton (honnêteté).`,
		how_to_fix: HOW_TO_FIX,
	};
}

/** byName canonicalises input order (name-sorted) so bytes never leak it. */
function byNameEntities(e: EntityModel[]): EntityModel[] {
	return [...e].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
}
function byNameControls(c: ControlModel[]): ControlModel[] {
	return [...c].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
}

/** A small deterministic FNV-1a digest for the preview header (display only — the Go
 * content-hash is authoritative). Same bytes → same digest, no clock/rng. */
export function digest(s: string): string {
	let h = 0x811c9dc5;
	for (let i = 0; i < s.length; i++) {
		h ^= s.charCodeAt(i);
		h = Math.imul(h, 0x01000193) >>> 0;
	}
	return h.toString(16).padStart(8, "0");
}

/** tsName: first rune upper, rest verbatim (mirrors Go frontemit.tsName). */
function tsName(s: string): string {
	return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

/** routeOf: /<lowercased name> (mirrors Go frontemit.routeOf and honoemit). */
function routeOf(name: string): string {
	return `/${name.toLowerCase()}`;
}

/** jsStr / jsxAttr: a JSON double-quoted literal (mirrors Go frontemit.jsStr). */
function jsStr(s: string): string {
	return JSON.stringify(s);
}
const jsxAttr = jsStr;

/** esc: the five XML metacharacters (mirrors Go frontemit.esc). */
function esc(s: string): string {
	return s
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#39;");
}

function header(sourceHash: string): string {
	return `// ${MARKER}. source: ${sourceHash}\n`;
}

/** controlSensorJSON: the compact fixture sensor (mirrors Go frontemit.controlSensorJSON). */
function controlSensorJSON(c: ControlModel): string {
	const rows = c.fixtures
		.map(
			(f) =>
				`{"given":${jsStr(f.given)},"visible":${f.visible},"enabled":${f.enabled}}`,
		)
		.join(",");
	return `{"name":${jsStr(c.name)},"op":${jsStr(c.operation)},"rows":[${rows}]}`;
}

export interface FrontFile {
	path: string;
	target: string;
	bytes: string;
}

function validate(s: FrontSpec): BlockReason | null {
	if (!s.project) return fail("la source n'épingle aucun projet");
	if (s.entities.length === 0 && s.controls.length === 0)
		return fail("la source n'épingle ni entité ni contrôle");
	for (const e of s.entities) {
		if (!e.name) return fail("une entité n'épingle aucun nom");
		for (const r of e.refs ?? [])
			if (!r.name) return fail("une relation n'épingle aucun nom");
	}
	for (const c of s.controls) {
		if (!c.name) return fail("un contrôle n'épingle aucun nom");
		if (!c.view) return fail("un contrôle n'épingle aucune vue");
		if (!c.operation)
			return fail("un bouton ne lie aucune opération (trigger orphelin)");
	}
	return null;
}

/** sourceHash: a display digest of the canonical spec (the Go content-hash is authoritative). */
export function sourceHash(s: FrontSpec): string {
	const ents = byNameEntities(s.entities).map((e) => ({
		name: e.name,
		fields: [
			...e.attributes.map((a) => ({
				name: a.name,
				type: a.type,
				kind: "scalar",
				required: !!a.required,
			})),
			...(e.blobs ?? []).map((b) => ({
				name: b.name,
				kind: "blob",
				required: !!b.required,
			})),
			...(e.refs ?? []).map((r) => ({
				name: r.name,
				kind: "relation",
				required: !!r.required,
				target: r.target,
				card: r.cardinality,
			})),
		],
	}));
	const ctrls = byNameControls(s.controls).map((c) => ({
		name: c.name,
		view: c.view,
		label: c.label,
		op: c.operation,
		fixtures: c.fixtures.map((f) => ({
			given: f.given,
			visible: f.visible,
			enabled: f.enabled,
		})),
	}));
	return digest(
		JSON.stringify({ project: s.project, entities: ents, controls: ctrls }),
	);
}

function emitIndex(s: FrontSpec, h: string): FrontFile {
	const lines: string[] = [];
	lines.push(header(h).trimEnd());
	lines.push(
		"// S93 emitted app FRONT index (Hono JSX/SSR). Navigation over the project's entities.",
	);
	lines.push("/** @jsxImportSource hono/jsx */");
	lines.push("");
	lines.push("export const IndexPage = () => (");
	lines.push('\t<main class="aidos-app bg-background text-foreground">');
	lines.push(`\t\t<h1 class="text-2xl font-semibold">${esc(s.project)}</h1>`);
	lines.push('\t\t<nav class="aidos-nav">');
	for (const e of byNameEntities(s.entities)) {
		lines.push(
			`\t\t\t<a class="text-blue-600" href=${jsxAttr(routeOf(e.name) + "/new")} data-aidos-entity=${jsxAttr(e.name)}>${esc(tsName(e.name))}</a>`,
		);
	}
	lines.push("\t\t</nav>");
	lines.push("\t</main>");
	lines.push(");");
	return {
		path: `gen/${s.project}/web/index.tsx`,
		target: "front-index",
		bytes: `${lines.join("\n")}\n`,
	};
}

function emitEntityForm(project: string, e: EntityModel, h: string): FrontFile {
	const hasBlob = (e.blobs ?? []).length > 0;
	const enctype = hasBlob
		? "multipart/form-data"
		: "application/x-www-form-urlencoded";
	const lines: string[] = [];
	lines.push(header(h).trimEnd());
	lines.push(
		`// S93 emitted app FRONT form for entity ${e.name} (Hono JSX/SSR). Posts to the emitted API route.`,
	);
	lines.push("/** @jsxImportSource hono/jsx */");
	lines.push("");
	lines.push(`export const ${tsName(e.name)}Form = () => (`);
	lines.push(
		`\t<form class="aidos-form" method="post" action=${jsxAttr(routeOf(e.name))} enctype=${jsxAttr(enctype)} data-aidos-entity=${jsxAttr(e.name)}>`,
	);
	lines.push(`\t\t<h2 class="text-xl font-medium">${esc(tsName(e.name))}</h2>`);
	for (const a of e.attributes) {
		if (a.identifier) continue;
		const inputType = SCALAR_INPUT[a.type];
		const req = a.required ? " required" : "";
		lines.push(
			`\t\t<label class="aidos-field" data-aidos-field=${jsxAttr(a.name)}>${esc(a.name)}`,
		);
		lines.push(
			`\t\t\t<input class="aidos-input" name=${jsxAttr(a.name)} type=${jsxAttr(inputType)}${req} />`,
		);
		lines.push("\t\t</label>");
	}
	for (const b of e.blobs ?? []) {
		const accept = b.allowedMime.join(",");
		const req = b.required ? " required" : "";
		lines.push(
			`\t\t<label class="aidos-field aidos-blob" data-aidos-field=${jsxAttr(b.name)} data-aidos-blob="true" data-aidos-max-bytes=${jsxAttr(String(b.maxBytes))}>${esc(b.name)}`,
		);
		lines.push(
			`\t\t\t<input class="aidos-input" name=${jsxAttr(b.name)} type="file" accept=${jsxAttr(accept)}${req} />`,
		);
		lines.push("\t\t</label>");
	}
	for (const r of e.refs ?? []) {
		const multiple = r.cardinality === "N-N" ? " multiple" : "";
		const req = r.required ? " required" : "";
		lines.push(
			`\t\t<label class="aidos-field" data-aidos-field=${jsxAttr(r.name)} data-aidos-relation=${jsxAttr(r.cardinality)} data-aidos-target=${jsxAttr(r.target)}>${esc(r.name)}`,
		);
		lines.push(
			`\t\t\t<select class="aidos-input" name=${jsxAttr(r.name + "_id")}${multiple}${req}></select>`,
		);
		lines.push("\t\t</label>");
	}
	lines.push(
		`\t\t<button class="aidos-submit bg-blue-600 text-white" type="submit" data-aidos-submit=${jsxAttr(e.name)}>Submit</button>`,
	);
	lines.push("\t</form>");
	lines.push(");");
	return {
		path: `gen/${project}/web/${e.name.toLowerCase()}.form.tsx`,
		target: "front-entity-form",
		bytes: `${lines.join("\n")}\n`,
	};
}

function emitControls(s: FrontSpec, h: string): FrontFile {
	const lines: string[] = [];
	lines.push(header(h).trimEnd());
	lines.push(
		"// S93 emitted app FRONT controls (Hono JSX/SSR). The control+action verticale rendered to real buttons,",
	);
	lines.push(
		"// each carrying its control-spec fixture as a data-aidos-control sensor.",
	);
	lines.push("/** @jsxImportSource hono/jsx */");
	lines.push("");
	lines.push("export const ControlsPanel = () => (");
	lines.push('\t<section class="aidos-controls">');
	for (const c of byNameControls(s.controls)) {
		const fixtureJSON = controlSensorJSON(c);
		lines.push('\t\t<button class="aidos-control bg-blue-600 text-white"');
		lines.push(`\t\t\tdata-aidos-control=${jsxAttr(c.name)}`);
		lines.push(`\t\t\tdata-aidos-view=${jsxAttr(c.view)}`);
		lines.push(`\t\t\tdata-aidos-invoke=${jsxAttr(c.operation)}`);
		lines.push(`\t\t\tdata-aidos-fixture=${jsxAttr(fixtureJSON)}`);
		lines.push(`\t\t\ttype="button">${esc(c.label)}</button>`);
	}
	lines.push("\t</section>");
	lines.push(");");
	return {
		path: `gen/${s.project}/web/controls.tsx`,
		target: "front-controls",
		bytes: `${lines.join("\n")}\n`,
	};
}

/** emitFront renders the whole front: index, one form per entity, controls. */
export function emitFront(s: FrontSpec): FrontFile[] | BlockReason {
	const br = validate(s);
	if (br) return br;
	const h = sourceHash(s);
	const out: FrontFile[] = [emitIndex(s, h)];
	for (const e of byNameEntities(s.entities))
		out.push(emitEntityForm(s.project, e, h));
	out.push(emitControls(s, h));
	return out;
}

/** emitBundle concatenates every front file under a banner — the byte-identity surface. */
export function emitBundle(s: FrontSpec): string | BlockReason {
	const files = emitFront(s);
	if (isBlocked(files)) return files;
	const h = sourceHash(s);
	const parts = [
		header(h).trimEnd(),
		"// S93 emitted app FRONT bundle (Hono JSX/SSR, ADR 0040 / OQ-0040-front DECIDED): index + per-entity forms + controls.",
	];
	for (const f of files) {
		parts.push(`\n// ===== ${f.path} =====`);
		parts.push(f.bytes.replace(/\n$/, ""));
	}
	return `${parts.join("\n")}\n`;
}
