/**
 * The Hono/TS server + Pulumi/TS infra emitter twin — the Workbench /hono-emitter source
 * (AIDOS S87).
 *
 * The DECLARED projection of the Go package back/runtime/honoemit: the deterministic emitter
 * that projects the project's Kernel operations into a BOOTABLE Hono/TS server (ADR 0040) and
 * the StackManifest into a Pulumi/TS infra program (ADR 0043):
 *   - server → main + router + middleware + GET /healthz + one POST handler per SYNC operation
 *              (delegating to the Go interpreter callback, ADR 0040 Déc.7).
 *   - worker → the async worker (TS): drains the outbox, dispatches typed effects (S73/S74).
 *   - pulumi → one docker.Container per service on the shared Traefik network (FN02-pure).
 *
 * DETERMINISM-FIRST (CLAUDE.md §6/§8): every emit is a PURE function of its input — no clock,
 * no rng, no I/O, no LLM — and CANONICALISES (ops/services by name) before rendering, so the
 * SAME Kernel cut → byte-identical output, INVARIANT to input order. The Go output is the
 * AUTHORITATIVE truth; this twin reproduces the bytes for the screen so the panel can show a
 * live, deterministic preview. The reproducibility mirror lib/hono-emitter.test.ts (fast-check)
 * pins determinism, the input-order invariance, the FN02 purity (no module-scope mutable
 * binding), and the every-sync-op-wired honesty.
 *
 * READ-ONLY (the wall): /hono-emitter PROJECTS; it never writes truth. The emitted bytes are a
 * projection (S78 owns regeneration), never a kernel write.
 */

export type TriggerKind = "cron" | "queue" | "webhook_out" | "notification";

/** The closed trigger set, canonical order (mirrors Go operation.TriggerKinds). */
export const TRIGGER_KINDS: TriggerKind[] = [
	"cron",
	"queue",
	"webhook_out",
	"notification",
];

export interface Op {
	name: string;
	async?: boolean;
	trigger?: TriggerKind;
	/** the cron echeance (RFC3339) for a cron trigger; empty otherwise. */
	at?: string;
}

export interface ServerSpec {
	project: string;
	ops: Op[];
}

export type ServiceRole =
	| "server"
	| "datastore"
	| "cache"
	| "pooler"
	| "interpreter"
	| "workflow"
	| "bus";

/** The closed service-role set, canonical order (mirrors Go honoemit.ServiceRoles). */
export const SERVICE_ROLES: ServiceRole[] = [
	"server",
	"datastore",
	"cache",
	"pooler",
	"interpreter",
	"workflow",
	"bus",
];

export interface Service {
	name: string;
	role: ServiceRole;
	image: string;
	internalPort: number;
}

export interface StackManifest {
	app: string;
	services: Service[];
	network: { name: string; external: boolean };
}

export interface BlockReason {
	code: string;
	severity: "blocking";
	explanation: string;
	how_to_fix: string[];
}

export function isBlocked<T>(v: T | BlockReason): v is BlockReason {
	return (
		typeof v === "object" && v !== null && "code" in v && "how_to_fix" in v
	);
}

const MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

const HOW_TO_FIX = [
	"pin_the_source : complétez la source dans le Kernel (operations nommées / manifest avec services typés).",
	"use_a_known_role : chaque service porte un rôle du jeu fermé ; un rôle inconnu n'est jamais deviné.",
	"rerun aidos project : relancez l'émission une fois la source complète et bien typée.",
];

function fail(msg: string): BlockReason {
	return {
		code: "OUT_OF_SCOPE",
		severity: "blocking",
		explanation: `Émission refusée : ${msg}. Un emitter REND exactement ce que la source épingle ; il n'invente jamais une route, un service, un rôle ni un trigger (honnêteté).`,
		how_to_fix: HOW_TO_FIX,
	};
}

/** byNameOps / byNameServices canonicalise input order (name-sorted) so bytes never leak it. */
function byNameOps(ops: Op[]): Op[] {
	return [...ops].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
}
function byNameServices(s: Service[]): Service[] {
	return [...s].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
}

/** A small deterministic FNV-1a digest for the preview header (display only — the Go
 * content-hash is authoritative). Same bytes → same digest, no clock/rng. */
export function digest(s: string): string {
	let h = 0x811c9dc5;
	for (let i = 0; i < s.length; i++) {
		h ^= s.charCodeAt(i);
		h = Math.imul(h, 0x01000193) >>> 0;
	}
	return h.toString(16).padStart(8, "0");
}

function header(body: string): string {
	return `// ${MARKER}. source: ${digest(body)}\n`;
}

/** validateServer mirrors Go honoemit.validateServer. */
export function validateServer(s: ServerSpec): BlockReason | null {
	if (!s.project) return fail("le spec n'épingle aucun projet");
	if (!s.ops || s.ops.length === 0)
		return fail("le spec n'épingle aucune operation");
	for (const op of s.ops) {
		if (!op.name) return fail("une operation n'épingle aucun nom");
		if (op.async && !TRIGGER_KINDS.includes(op.trigger as TriggerKind))
			return fail(`l'op async ${op.name} a un trigger inconnu`);
	}
	return null;
}

/** emitServer renders the bootable Hono/TS server (mirrors Go honoemit.EmitServer). */
export function emitServer(s: ServerSpec): string | BlockReason {
	const bad = validateServer(s);
	if (bad) return bad;
	const sync = byNameOps(s.ops.filter((o) => !o.async));
	const out: string[] = [];
	out.push(
		"// S87 emitted app server (Hono/functional TS, ADR 0040). main+router+middleware+health+",
		"// one handler per SYNC operation; async ops are wired in worker.ts.",
		"",
		'import { Hono } from "hono";',
		"",
		"export type OperationInterpreter = (operation: string, input: unknown) => Promise<unknown>;",
		"export type Deps = { interpret: OperationInterpreter };",
		"",
		"export function createApp(deps: Deps): Hono {",
		"\tconst app = new Hono();",
		'\tapp.use("*", async (c, next) => {',
		`\t\tc.header("x-app", ${JSON.stringify(s.project)});`,
		"\t\tawait next();",
		"\t});",
		'\tapp.get("/healthz", (c) => c.json({ status: "ok" }, 200));',
	);
	for (const op of sync) {
		const route = `/${op.name.toLowerCase()}`;
		out.push(
			`\tapp.post(${JSON.stringify(route)}, async (c) => {`,
			"\t\tconst input = await c.req.json().catch(() => ({}));",
			`\t\tconst result = await deps.interpret(${JSON.stringify(op.name)}, input);`,
			"\t\treturn c.json(result, 201);",
			"\t});",
		);
	}
	out.push("\treturn app;", "}");
	const body = `${out.join("\n")}\n`;
	return header(body) + body;
}

/** emitWorker renders the async worker (mirrors Go honoemit.EmitWorker). */
export function emitWorker(s: ServerSpec): string | BlockReason {
	const bad = validateServer(s);
	if (bad) return bad;
	const async = byNameOps(s.ops.filter((o) => o.async));
	const out: string[] = [];
	out.push(
		"// S87 emitted app worker (Hono/TS, ADR 0040): drains the outbox, dispatches typed effects.",
		"",
		"export type OutboxRow = { effect_id: string; operation: string; kind: string; target: string; payload: unknown; dispatched: boolean };",
		"export type Outbox = {",
		"\tpending(operation: string): Promise<OutboxRow[]>;",
		"\tmarkDispatched(effectId: string): Promise<void>;",
		"};",
		"export type Dispatcher = {",
	);
	for (const tk of TRIGGER_KINDS)
		out.push(`\t${tk}(target: string, payload: unknown): Promise<void>;`);
	out.push("};", "");
	for (const op of async) {
		const opConst = op.name[0].toUpperCase() + op.name.slice(1);
		if (op.trigger === "cron")
			out.push(
				`export const ${op.name.toUpperCase()}_SCHEDULED_AT = ${JSON.stringify(op.at ?? "")};`,
			);
		out.push(
			`export async function dispatch${opConst}(outbox: Outbox, dispatcher: Dispatcher): Promise<number> {`,
			`\tconst rows = await outbox.pending(${JSON.stringify(op.name)});`,
			"\tlet dispatched = 0;",
			"\tfor (const row of rows) {",
			"\t\tif (row.dispatched) continue;",
			"\t\tswitch (row.kind) {",
		);
		for (const tk of TRIGGER_KINDS)
			out.push(
				`\t\t\tcase ${JSON.stringify(tk)}: await dispatcher.${tk}(row.target, row.payload); break;`,
			);
		out.push(
			"\t\t\tdefault: continue;",
			"\t\t}",
			"\t\tawait outbox.markDispatched(row.effect_id);",
			"\t\tdispatched++;",
			"\t}",
			"\treturn dispatched;",
			"}",
			"",
		);
	}
	const body = `${out.join("\n").replace(/\n+$/, "")}\n`;
	return header(body) + body;
}

/** validateManifest mirrors Go honoemit.validateManifest. */
export function validateManifest(m: StackManifest): BlockReason | null {
	if (!m.app) return fail("le manifest n'épingle aucune app");
	if (!m.services || m.services.length === 0)
		return fail("le manifest n'épingle aucun service");
	const seen = new Set<number>();
	let hasServer = false;
	for (const s of m.services) {
		if (!s.name) return fail("un service n'épingle aucun nom");
		if (!s.image) return fail(`le service ${s.name} n'épingle aucune image`);
		if (!SERVICE_ROLES.includes(s.role))
			return fail(`le service ${s.name} a un rôle inconnu`);
		if (s.role === "server") hasServer = true;
		if (s.internalPort) {
			if (seen.has(s.internalPort))
				return fail("deux services partagent le même port interne");
			seen.add(s.internalPort);
		}
	}
	if (!hasServer)
		return fail("le manifest ne déclare aucun service role=server");
	return null;
}

function tsIdent(name: string): string {
	let out = "";
	for (let i = 0; i < name.length; i++) {
		const ch = name[i];
		if (/[a-zA-Z_]/.test(ch)) out += ch;
		else if (/[0-9]/.test(ch)) out += (i === 0 ? "_" : "") + ch;
		else out += "_";
	}
	return out || "_";
}

/** emitPulumi renders the Pulumi/TS infra program (mirrors Go honoemit.EmitPulumiProgram). */
export function emitPulumi(m: StackManifest): string | BlockReason {
	const bad = validateManifest(m);
	if (bad) return bad;
	const svcs = byNameServices(m.services);
	const out: string[] = [];
	out.push(
		"// S87 emitted app infra program (Pulumi/functional TS, ADR 0043). StackManifest →",
		"// one docker.Container per service on the shared Traefik network. One program → all targets.",
		"",
		'import * as docker from "@pulumi/docker";',
		"",
		"export function program() {",
		`\tconst networkName = ${JSON.stringify(m.network.name)};`,
		`\tconst network = new docker.Network(${JSON.stringify(m.network.name)}, { name: networkName });`,
		"",
	);
	const vars: string[] = [];
	for (const s of svcs) {
		const v = tsIdent(s.name);
		vars.push(v);
		out.push(
			`\tconst ${v} = new docker.Container(${JSON.stringify(s.name)}, {`,
			`\t\timage: ${JSON.stringify(s.image)},`,
			`\t\tname: ${JSON.stringify(s.name)},`,
			'\t\trestart: "unless-stopped",',
			"\t\tnetworksAdvanced: [{ name: networkName }],",
		);
		if (s.role === "server") {
			out.push(
				"\t\tlabels: [",
				'\t\t\t{ label: "traefik.enable", value: "true" },',
				`\t\t\t{ label: "traefik.http.services.${s.name}.loadbalancer.server.port", value: ${JSON.stringify(String(s.internalPort))} },`,
				`\t\t\t{ label: "traefik.http.routers.${s.name}.entrypoints", value: "websecure" },`,
				`\t\t\t{ label: "traefik.http.routers.${s.name}.tls", value: "true" },`,
				"\t\t],",
			);
		}
		out.push("\t}, { dependsOn: [network] });", "");
	}
	out.push(`\treturn { network, containers: { ${vars.join(", ")} } };`, "}");
	const body = `${out.join("\n").replace(/\n+$/, "")}\n`;
	return header(body) + body;
}

/** A canonical demo server spec: two sync ops + one async notification op. */
export const DEMO_SPEC: ServerSpec = {
	project: "shop",
	ops: [
		{ name: "createOrder" },
		{ name: "cancelOrder" },
		{ name: "sendReceipt", async: true, trigger: "notification" },
	],
};

/** A canonical demo StackManifest: server + interpreter sidecar + Postgres + Valkey. */
export const DEMO_MANIFEST: StackManifest = {
	app: "shop",
	services: [
		{
			name: "server",
			role: "server",
			image: "shop-server:latest",
			internalPort: 3000,
		},
		{
			name: "interpreter",
			role: "interpreter",
			image: "aidos-interpreter:latest",
			internalPort: 8080,
		},
		{
			name: "postgres",
			role: "datastore",
			image: "postgres:16",
			internalPort: 5432,
		},
		{
			name: "valkey",
			role: "cache",
			image: "valkey/valkey:8",
			internalPort: 6379,
		},
	],
	network: { name: "traefik_default", external: true },
};
