import fc from "fast-check";
import { describe, expect, it } from "vitest";
import {
	driftDetected,
	emitCompose,
	renderCompose,
	TARGET_DOCKER_COMPOSE,
} from "./stack-emit";
import {
	exampleManifest,
	PROFILES,
	ROLES,
	type StackManifest,
} from "./stack-manifest";

/**
 * Reproducibility mirror (vitest + fast-check): reflects=DP03-compose-emitter,
 * test_kind=property, cert_language=vitest, liveness=live.
 *
 * DP03 — the TS twin of the authoritative Go emitter
 * (back/runtime/composeemit): Emit(stack_manifest) → docker-compose.yml,
 * /data/dockers conventions. The twin is BYTE-PARITY-PINNED to Go: the pinned
 * Example manifest must emit bytes whose sha-256 is the EXACT output_hash the
 * Go side measured (GO_OUTPUT_HASH below). Any one-byte divergence reds.
 *
 * Laws (the DP03 done-criteria, twin side):
 *   L1 byte parity with Go (output_hash + source_hash + path);
 *   L2 reproducibility ×100 — same manifest → byte-identical compose;
 *   L3 role=server emits the Traefik HTTPS router + HTTP→HTTPS redirect;
 *   L4 a volume emits the named bind device ${<DEVICE_VAR>};
 *   L5 traefik_default is external:true — except the deployment that OWNS it;
 *   L6 no published ports — exposure is Traefik labels only;
 *   L7 an invalid manifest is REFUSED with its closed DP02 code;
 *   L8 a hand-edited emission is detected as drift (one flipped byte).
 */

// The Go-authoritative output_hash of Emit(stackmanifest.Example()) —
// records.Hash(bytes), printed by the Go side, pinned here verbatim.
const GO_OUTPUT_HASH =
	"efea2247cc8634350680d6e0eb419af6637dade0a76369b8af3f38be6fea24c1";

// The Go-authoritative source_hash (== DP02's GO_MANIFEST_HASH — the emitter
// reuses the kernel content address, never a fork).
const GO_SOURCE_HASH =
	"8011728e4f9c01130c151d5c49b89b28afa1e3dc5e741fcc12c04c38062acdd2";

const serviceName = fc
	.tuple(
		fc.constantFrom(..."abcdefghijklmnopqrstuvwxyz"),
		fc.stringMatching(/^[a-z0-9]{0,9}$/),
	)
	.map(([h, t]) => h + t);

const validManifest: fc.Arbitrary<StackManifest> = fc
	.record({
		app: serviceName,
		names: fc.uniqueArray(serviceName, { minLength: 1, maxLength: 5 }),
		ports: fc.uniqueArray(fc.integer({ min: 1024, max: 65535 }), {
			minLength: 5,
			maxLength: 5,
		}),
		roles: fc.array(fc.constantFrom(...ROLES), {
			minLength: 5,
			maxLength: 5,
		}),
		profiles: fc.array(fc.constantFrom(...PROFILES), {
			minLength: 5,
			maxLength: 5,
		}),
		external: fc.boolean(),
		volumes: fc.uniqueArray(serviceName, { maxLength: 2 }),
	})
	.map(({ app, names, ports, roles, profiles, external, volumes }) => ({
		app,
		services: names.map((name, i) => ({
			name,
			role: i === 0 ? "server" : roles[i],
			image: i % 2 === 0 ? "node:22-alpine" : "",
			internal_port: ports[i],
			profile: profiles[i],
		})),
		volumes: volumes.map((name, i) => ({
			name,
			device_var: i === 0 ? "APP_DATA_PATH" : "EXTRA_DATA_PATH",
		})),
		network: { name: "traefik_default", external },
	}));

describe("DP03 — docker-compose emitter TS twin pinned to the authoritative Go emitter", () => {
	it("L1 — the seeded Example manifest emits EXACTLY the Go bytes (output_hash + source_hash + path parity)", async () => {
		const a = await emitCompose(exampleManifest());
		if ("refusal" in a) throw new Error("Example refused");
		expect(a.outputHash).toBe(GO_OUTPUT_HASH);
		expect(a.sourceHash).toBe(GO_SOURCE_HASH);
		expect(a.path).toBe("back/gen/alphashop/docker-compose.yml");
		expect(a.target).toBe(TARGET_DOCKER_COMPOSE);
		expect(
			a.yaml.startsWith(
				`# CODE GENERATED BY AIDOS — DO NOT EDIT. source: ${GO_SOURCE_HASH}\n`,
			),
		).toBe(true);
	});

	it("L2 — reproducibility: same manifest → byte-identical compose, ×100 (pure)", async () => {
		const first = await emitCompose(exampleManifest());
		if ("refusal" in first) throw new Error("Example refused");
		for (let i = 0; i < 100; i++) {
			const again = await emitCompose(exampleManifest());
			if ("refusal" in again) throw new Error("Example refused");
			expect(again.yaml).toBe(first.yaml);
			expect(again.outputHash).toBe(first.outputHash);
		}
	});

	it("L2∀ — reproducibility over arbitrary valid manifests (fast-check)", () => {
		fc.assert(
			fc.property(validManifest, (m) => {
				const y1 = renderCompose(m, "deadbeef");
				const y2 = renderCompose(m, "deadbeef");
				expect(y1).toBe(y2);
			}),
		);
	});

	// biome-ignore-start lint/suspicious/noTemplateCurlyInString: the mirror asserts the LITERAL compose env-var placeholders (never hardcoded values)
	it("L3 — ∀ manifest: role=server emits the HTTPS router (websecure/tls/certresolver) + the redirect middleware", () => {
		fc.assert(
			fc.property(validManifest, (m) => {
				const y = renderCompose(m, "deadbeef");
				expect(y).toContain(
					"traefik.http.routers.${APP_NAME}.entrypoints=websecure",
				);
				expect(y).toContain("traefik.http.routers.${APP_NAME}.tls=true");
				expect(y).toContain(
					"traefik.http.routers.${APP_NAME}.tls.certresolver=${CERT_RESOLVER_NAME}",
				);
				expect(y).toContain(
					"traefik.http.middlewares.${APP_NAME}-https-redirect.redirectscheme.scheme=https",
				);
			}),
		);
	});

	it("L4 — ∀ manifest: every volume emits the named bind device ${<DEVICE_VAR>} (env-var reference, never a path)", () => {
		fc.assert(
			fc.property(validManifest, (m) => {
				const y = renderCompose(m, "deadbeef");
				for (const v of m.volumes ?? []) {
					expect(y).toContain(`device: \${${v.device_var}}`);
				}
				if ((m.volumes ?? []).length > 0) {
					expect(y).toContain("type: none");
					expect(y).toContain("o: bind");
				}
			}),
		);
	});

	it("L5 — ∀ manifest: traefik_default is external:true, EXCEPT the deployment that OWNS it", () => {
		fc.assert(
			fc.property(validManifest, (m) => {
				const y = renderCompose(m, "deadbeef");
				expect(y.includes("external: true")).toBe(m.network.external);
				expect(y).toContain("name: ${TRAEFIK_NETWORK_NAME}");
			}),
		);
	});

	// biome-ignore-end lint/suspicious/noTemplateCurlyInString: literal compose placeholders
	it("L6 — ∀ manifest: NO published ports (exposure is Traefik labels only)", () => {
		fc.assert(
			fc.property(validManifest, (m) => {
				const y = renderCompose(m, "deadbeef");
				for (const line of y.split("\n")) {
					expect(line.trim()).not.toBe("ports:");
				}
			}),
		);
	});

	it("L7 — an invalid manifest is REFUSED with its closed DP02 code (never a guessed compose)", async () => {
		const unknownRole = exampleManifest();
		unknownRole.services[1].role = "teleporter";
		const r1 = await emitCompose(unknownRole);
		if (!("refusal" in r1)) throw new Error("unknown role emitted anyway");
		expect(r1.refusal.code).toBe("UNKNOWN_SERVICE_ROLE");

		const dupPort = exampleManifest();
		dupPort.services[1].internal_port = dupPort.services[0].internal_port;
		const r2 = await emitCompose(dupPort);
		if (!("refusal" in r2)) throw new Error("duplicate port emitted anyway");
		expect(r2.refusal.code).toBe("DUPLICATE_INTERNAL_PORT");

		const noServer = exampleManifest();
		noServer.services = noServer.services.map((s) => ({
			...s,
			role: "cache",
		}));
		const r3 = await emitCompose(noServer);
		if (!("refusal" in r3)) throw new Error("serverless stack emitted anyway");
		expect(r3.refusal.code).toBe("STACK_HAS_NO_SERVER");
	});

	it("L8 — a hand-edited emission is detected as drift (one flipped byte)", async () => {
		const a = await emitCompose(exampleManifest());
		if ("refusal" in a) throw new Error("Example refused");
		expect(await driftDetected(a.outputHash, a.yaml)).toBe(false);
		const tampered = `${a.yaml} `;
		expect(await driftDetected(a.outputHash, tampered)).toBe(true);
	});

	it("L9 — the kind × target matrix stays closed: the additive target is declared, never invented", () => {
		expect(TARGET_DOCKER_COMPOSE).toBe("docker-compose");
	});
});
