/**
 * web-projection reproducibility mirror (∀, fast-check + worked example).
 *
 *   reflects: front.web-preview emitter twin (lib/web-projection.ts) ·
 *   test_kind: property + example · cert_language: fast-check/vitest · authority: below · liveness: live
 *
 * Pins the TS twin to the AUTHORITATIVE Go bytes/hashes (the webcomponent emitter):
 *   - sourceHash(control, action) == the Go source_hash (8ebfb46f…) — content-addressed;
 *   - emitWeb(...).output_hash == the Go output_hash (96b5d172…) — byte-identical re-emit;
 *   - the emitted bytes equal the materialized _generated/checkout-button.tsx on disk;
 *   - determinism: emitWeb(c,a) == emitWeb(c,a) byte-for-byte over generated specs;
 *   - the embedded aidos-expr evalState honours the S11 state fixture (given → visible/enabled);
 *   - a click on the enabled button declares invoke == createOrder (the action fixture).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { evalState } from "./aidos-expr";
import { emitWeb, sourceHash } from "./web-projection";
import {
	CHECKOUT_BUTTON,
	CHECKOUT_FIXTURE,
	CHECKOUT_SUBMIT,
	EXPECTED_INVOKE,
} from "./web-projection-data";

// The authoritative Go hashes (back/runtime/generators/webcomponent).
const GO_SOURCE_HASH =
	"8ebfb46ff10c0dc68ee53be000e9965466e7effa666703f870fce027fbae5cf6";
const GO_OUTPUT_HASH =
	"5b428d00a19c01d565697f076bf2770f34c3ab0ce32c379233e3f6fd68030f76";

describe("web-projection twin is byte-identical to the Go webcomponent emitter", () => {
	it("source_hash matches the Go source hash (content-addressed)", () => {
		expect(sourceHash(CHECKOUT_BUTTON, CHECKOUT_SUBMIT)).toBe(GO_SOURCE_HASH);
	});

	it("output_hash matches the Go output hash (byte-identical re-emit)", () => {
		const art = emitWeb(CHECKOUT_BUTTON, CHECKOUT_SUBMIT);
		expect(art.output_hash).toBe(GO_OUTPUT_HASH);
		expect(art.source_hash).toBe(GO_SOURCE_HASH);
		expect(art.target).toBe("ts-next");
		expect(art.kind).toBe("control");
		expect(art.protected).toBe(true);
	});

	it("emitted bytes equal the materialized _generated/ file on disk", () => {
		const onDisk = readFileSync(
			join(process.cwd(), "app/web-preview/_generated/checkout-button.tsx"),
			"utf8",
		);
		expect(emitWeb(CHECKOUT_BUTTON, CHECKOUT_SUBMIT).bytes).toBe(onDisk);
	});

	it("starts with the protected header carrying the source hash", () => {
		const art = emitWeb(CHECKOUT_BUTTON, CHECKOUT_SUBMIT);
		expect(
			art.bytes.startsWith(
				`// CODE GENERATED BY AIDOS — DO NOT EDIT. source: ${art.source_hash}`,
			),
		).toBe(true);
	});

	it("is deterministic byte-for-byte over varied (view, label, invoke)", () => {
		fc.assert(
			fc.property(
				fc
					.string({ minLength: 1, maxLength: 8 })
					.filter((s) => /^[a-z]/.test(s)),
				fc.string({ minLength: 1, maxLength: 12 }),
				fc.string({ minLength: 1, maxLength: 16 }),
				(view, label, invoke) => {
					const c = { ...CHECKOUT_BUTTON, view, label };
					const a = { ...CHECKOUT_SUBMIT, invoke };
					expect(emitWeb(c, a).bytes).toBe(emitWeb(c, a).bytes);
					expect(emitWeb(c, a).output_hash).toBe(emitWeb(c, a).output_hash);
				},
			),
		);
	});
});

describe("the embedded aidos-expr render honours the S11 fixtures", () => {
	for (const row of CHECKOUT_FIXTURE) {
		it(`given "${row.id}" → visible=${row.wantVisible} enabled=${row.wantEnabled}`, () => {
			const st = evalState(
				CHECKOUT_BUTTON.visible_when,
				CHECKOUT_BUTTON.enabled_when,
				row.given,
			);
			expect(st.visible).toBe(row.wantVisible);
			expect(st.enabled).toBe(row.wantEnabled);
		});
	}

	it("the bound action declares invoke createOrder (the event fixture)", () => {
		expect(CHECKOUT_SUBMIT.invoke).toBe(EXPECTED_INVOKE);
		expect(CHECKOUT_SUBMIT.on.control).toBe(CHECKOUT_BUTTON.name);
		expect(CHECKOUT_BUTTON.triggers).toBe(CHECKOUT_SUBMIT.name);
	});
});
