/**
 * web-projection — the BYTE-IDENTICAL TypeScript twin of the Go web-projection emitter
 * (back/runtime/generators/webcomponent.{Emit,SourceHash,render}). It is a PURE,
 * deterministic projection: no I/O, no clock, no RNG, no LLM. The Workbench /web-preview
 * panel re-emits the SAME twin so what is on screen matches the engine. The authoritative
 * bytes/hashes are the Go ones (GO_* constants); the fast-check mirror
 * (web-projection.test.ts) pins the twin to them.
 *
 * ONE SOURCE → N PROJECTIONS, NEVER DOUBLE-TYPED (KRD LIVRE V). A control-spec + the
 * action it binds (S11, prior truth, read-only) emit ONE Next component whose
 * visible/enabled are EvalState(control, given) (the lib/aidos-expr twin embedded in the
 * .tsx) and whose click DECLARES the bound operation (Plan(action, click).invoke). The
 * source_hash = Hash(Canonicalize(control.body ⊕ action.body)) — S02/S11 reused, byte-
 * identical to Go.
 *
 * THE WALL (§2): the control/action are SOURCES above the line (read SELECT-only);
 * _generated/ is generated-only (never hand-edited); a ledger row is written via
 * propose → ChangeSet → approval, never from the screen. This twin renders, it never
 * writes truth.
 */

import { createHash } from "node:crypto";
import type { ExprNode } from "./aidos-expr";

export const PROTECTED_MARKER = "CODE GENERATED BY AIDOS — DO NOT EDIT";

/** The control-spec the emitter projects (the agent-side mirror of kernel.control, S11). */
export interface ControlSpec {
	name: string;
	view: string;
	label: string;
	visible_when: ExprNode;
	enabled_when: ExprNode;
	triggers: string; // the action ref this control fires (the control→action link)
}

/** The action-spec the control binds (the agent-side mirror of kernel.action, S11). */
export interface ActionSpec {
	name: string;
	on: { kind: "click"; control: string };
	invoke: string; // the bound operation ref (Plan(action, click).invoke)
	with?: Record<string, ExprNode>;
	on_success?: { verb: string; arg: ExprNode }[];
	on_error?: { verb: string; arg: ExprNode }[];
}

export interface WebArtifact {
	path: string;
	target: "ts-next";
	kind: "control";
	bytes: string;
	source_hash: string;
	output_hash: string;
	protected: true;
}

function sha256(s: string): string {
	return createHash("sha256").update(s, "utf8").digest("hex");
}

/**
 * goJSONString — Go's json.Marshal string escaping: it HTML-escapes `<`, `>`, `&` as
 * <, >, & (the default SetEscapeHTML(true)). This is what makes the
 * embedded Expr AST JSON byte-identical to Go's expr.Canonicalize output (the `>` and
 * `&&` function names appear escaped).
 */
function goJSONString(s: string): string {
	const base = JSON.stringify(s);
	return base
		.replace(/</g, "\\u003c")
		.replace(/>/g, "\\u003e")
		.replace(/&/g, "\\u0026");
}

/**
 * canonExpr — the byte-identical twin of back/kernel/expr.Canonicalize (encodeNode): a
 * lit is {"kind":"lit","value":<v>}, a ref {"kind":"ref","path":<p>}, a call
 * {"args":[...],"fn":<f>,"kind":"call"} (note the FIXED key order Go writes). Strings
 * are HTML-escaped exactly as Go does.
 */
export function canonExpr(node: ExprNode): string {
	switch (node.kind) {
		case "lit":
			return `{"kind":"lit","value":${JSON.stringify(node.value)}}`;
		case "ref":
			return `{"kind":"ref","path":${goJSONString(node.path)}}`;
		case "call": {
			const args = node.args.map(canonExpr).join(",");
			return `{"args":[${args}],"fn":${goJSONString(node.fn)},"kind":"call"}`;
		}
	}
}

/** Canonical JSON: object keys sorted recursively (= Go records.Canonicalize). */
function canon(v: unknown): string {
	if (Array.isArray(v)) return `[${v.map(canon).join(",")}]`;
	if (v && typeof v === "object") {
		const keys = Object.keys(v as Record<string, unknown>).sort();
		return `{${keys
			.map(
				(k) => `${goJSONString(k)}:${canon((v as Record<string, unknown>)[k])}`,
			)
			.join(",")}}`;
	}
	if (typeof v === "string") return goJSONString(v);
	return JSON.stringify(v);
}

/** The canonical control body (= Go control.Canonicalize): the wire shape, keys sorted. */
function controlBody(c: ControlSpec): string {
	// The wire shape embeds visible_when/enabled_when as their canonical Expr ASTs.
	const obj = {
		kind: "control",
		name: c.name,
		view: c.view,
		label: c.label,
		visible_when: JSON.parse(canonExpr(c.visible_when)),
		enabled_when: JSON.parse(canonExpr(c.enabled_when)),
		triggers: c.triggers,
	};
	return canon(obj);
}

/** The canonical action body (= Go action.Canonicalize): the wire shape, keys sorted. */
function actionBody(a: ActionSpec): string {
	const withCanon: Record<string, unknown> = {};
	for (const [k, e] of Object.entries(a.with ?? {})) {
		withCanon[k] = JSON.parse(canonExpr(e));
	}
	const effects = (es: { verb: string; arg: ExprNode }[] | undefined) =>
		(es ?? []).map((e) => ({
			verb: e.verb,
			arg: JSON.parse(canonExpr(e.arg)),
		}));
	const obj = {
		kind: "action",
		name: a.name,
		on: { kind: a.on.kind, control: a.on.control },
		invoke: a.invoke,
		with: withCanon,
		on_success: effects(a.on_success),
		on_error: effects(a.on_error),
	};
	return canon(obj);
}

/**
 * sourceHash — Hash(Canonicalize(control.body ⊕ action.body)), byte-identical to Go's
 * webcomponent.SourceHash. The ⊕ is the {"action":<canon(a)>,"control":<canon(c)>}
 * envelope re-canonicalized (the two sub-bodies are already canonical; the top keys are
 * sorted action < control).
 */
export function sourceHash(c: ControlSpec, a: ActionSpec): string {
	const cb = controlBody(c);
	const ab = actionBody(a);
	const combined = `{${goJSONString("action")}:${ab},${goJSONString("control")}:${cb}}`;
	return sha256(combined);
}

/** componentName — pascal-cases a control name (= Go componentName). */
function componentName(name: string): string {
	const parts = name.split(/[-_ ]/).filter(Boolean);
	const out = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join("");
	return out || "Control";
}

/**
 * emitWeb — the .tsx bytes, byte-identical to the Go renderer. Tabs for indentation,
 * normalized "\n" newlines, the embedded Expr ASTs as canonical JSON, the protected
 * header carrying the source hash.
 */
export function emitWeb(c: ControlSpec, a: ActionSpec): WebArtifact {
	const hash = sourceHash(c, a);
	const name = componentName(c.name);
	const base = c.name.toLowerCase();
	const vw = canonExpr(c.visible_when);
	const ew = canonExpr(c.enabled_when);

	const src =
		`// ${PROTECTED_MARKER}. source: ${hash}\n` +
		`// Web projection (S38): the control-spec ${goJSONString(c.name)} bound to action ${goJSONString(a.name)}.\n` +
		`// One source → N projections, never double-typed (KRD LIVRE V). The button is a\n` +
		`// PROJECTION of the control-spec (S11): visible/enabled are EvalState(control, given)\n` +
		`// embedded as the control's Expr ASTs; the click DECLARES the bound operation\n` +
		`// (Plan(action, click).invoke) via data-aidos-invoke — it does NOT execute it.\n` +
		`"use client";\n\n` +
		`import { type ExprNode, evalState } from "@/lib/aidos-expr";\n\n` +
		`// visible_when / enabled_when — the control's Expr DSL ASTs (back/kernel/expr), embedded verbatim.\n` +
		`const VISIBLE_WHEN: ExprNode = ${vw};\n` +
		`const ENABLED_WHEN: ExprNode = ${ew};\n` +
		`const INVOKE = ${goJSONString(a.invoke)};\n` +
		`const LABEL = ${goJSONString(c.label)};\n\n` +
		`export interface ${name}Props {\n` +
		`\t/** The $-rooted situation state — the fixture \`given\` (S11). */\n` +
		`\tgiven: Record<string, unknown>;\n` +
		`\t/** Called with the bound operation ref when the enabled button is clicked. */\n` +
		`\tonInvoke?: (invoke: string) => void;\n` +
		`}\n\n` +
		`/** ${name} — the emitted web projection of control ${goJSONString(c.name)}. */\n` +
		`export function ${name}({ given, onInvoke }: ${name}Props) {\n` +
		`\tconst { visible, enabled } = evalState(VISIBLE_WHEN, ENABLED_WHEN, given);\n` +
		`\tif (!visible) return null;\n` +
		`\treturn (\n` +
		`\t\t<button\n` +
		`\t\t\tdata-testid=${goJSONString("aidos-control-" + base)}\n` +
		`\t\t\ttype="button"\n` +
		`\t\t\tdisabled={!enabled}\n` +
		`\t\t\tdata-aidos-visible={visible ? "true" : "false"}\n` +
		`\t\t\tdata-aidos-enabled={enabled ? "true" : "false"}\n` +
		`\t\t\tdata-aidos-invoke={INVOKE}\n` +
		`\t\t\tonClick={() => {\n` +
		`\t\t\t\tif (enabled) onInvoke?.(INVOKE);\n` +
		`\t\t\t}}\n` +
		`\t\t\tclassName="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"\n` +
		`\t\t>\n` +
		`\t\t\t{LABEL}\n` +
		`\t\t</button>\n` +
		`\t);\n` +
		`}\n`;

	return {
		path: `front/web/app/web-preview/_generated/${base}.tsx`,
		target: "ts-next",
		kind: "control",
		bytes: src,
		source_hash: hash,
		output_hash: sha256(src),
		protected: true,
	};
}
